#include <WinDef.h>

#pragma comment(linker, "/export:A_SHAFinal=advapi32.A_SHAFinal") // XP
#pragma comment(linker, "/export:A_SHAInit=advapi32.A_SHAInit") // XP
#pragma comment(linker, "/export:A_SHAUpdate=advapi32.A_SHAUpdate") // XP
#pragma comment(linker, "/export:AbortSystemShutdownA=advapi32.AbortSystemShutdownA") // XP
#pragma comment(linker, "/export:AbortSystemShutdownW=advapi32.AbortSystemShutdownW") // XP
#pragma comment(linker, "/export:AccessCheck=advapi32.AccessCheck") // XP
#pragma comment(linker, "/export:AccessCheckAndAuditAlarmA=advapi32.AccessCheckAndAuditAlarmA") // XP
#pragma comment(linker, "/export:AccessCheckAndAuditAlarmW=advapi32.AccessCheckAndAuditAlarmW") // XP
#pragma comment(linker, "/export:AccessCheckByType=advapi32.AccessCheckByType") // XP
#pragma comment(linker, "/export:AccessCheckByTypeAndAuditAlarmA=advapi32.AccessCheckByTypeAndAuditAlarmA") // XP
#pragma comment(linker, "/export:AccessCheckByTypeAndAuditAlarmW=advapi32.AccessCheckByTypeAndAuditAlarmW") // XP
#pragma comment(linker, "/export:AccessCheckByTypeResultList=advapi32.AccessCheckByTypeResultList") // XP
#pragma comment(linker, "/export:AccessCheckByTypeResultListAndAuditAlarmA=advapi32.AccessCheckByTypeResultListAndAuditAlarmA") // XP
#pragma comment(linker, "/export:AccessCheckByTypeResultListAndAuditAlarmByHandleA=advapi32.AccessCheckByTypeResultListAndAuditAlarmByHandleA") // XP
#pragma comment(linker, "/export:AccessCheckByTypeResultListAndAuditAlarmByHandleW=advapi32.AccessCheckByTypeResultListAndAuditAlarmByHandleW") // XP
#pragma comment(linker, "/export:AccessCheckByTypeResultListAndAuditAlarmW=advapi32.AccessCheckByTypeResultListAndAuditAlarmW") // XP
#pragma comment(linker, "/export:AddAccessAllowedAce=advapi32.AddAccessAllowedAce") // XP
#pragma comment(linker, "/export:AddAccessAllowedAceEx=advapi32.AddAccessAllowedAceEx") // XP
#pragma comment(linker, "/export:AddAccessAllowedObjectAce=advapi32.AddAccessAllowedObjectAce") // XP
#pragma comment(linker, "/export:AddAccessDeniedAce=advapi32.AddAccessDeniedAce") // XP
#pragma comment(linker, "/export:AddAccessDeniedAceEx=advapi32.AddAccessDeniedAceEx") // XP
#pragma comment(linker, "/export:AddAccessDeniedObjectAce=advapi32.AddAccessDeniedObjectAce") // XP
#pragma comment(linker, "/export:AddAce=advapi32.AddAce") // XP
#pragma comment(linker, "/export:AddAuditAccessAce=advapi32.AddAuditAccessAce") // XP
#pragma comment(linker, "/export:AddAuditAccessAceEx=advapi32.AddAuditAccessAceEx") // XP
#pragma comment(linker, "/export:AddAuditAccessObjectAce=advapi32.AddAuditAccessObjectAce") // XP
#pragma comment(linker, "/export:AddConditionalAce=advapi32.AddConditionalAce")
#pragma comment(linker, "/export:AddMandatoryAce=advapi32.AddMandatoryAce")
#pragma comment(linker, "/export:AddUsersToEncryptedFile=advapi32.AddUsersToEncryptedFile") // XP
#pragma comment(linker, "/export:AddUsersToEncryptedFileEx=advapi32.AddUsersToEncryptedFileEx")
#pragma comment(linker, "/export:AdjustTokenGroups=advapi32.AdjustTokenGroups") // XP
#pragma comment(linker, "/export:AdjustTokenPrivileges=advapi32.AdjustTokenPrivileges") // XP
#pragma comment(linker, "/export:AllocateAndInitializeSid=advapi32.AllocateAndInitializeSid") // XP
#pragma comment(linker, "/export:AllocateLocallyUniqueId=advapi32.AllocateLocallyUniqueId") // XP
#pragma comment(linker, "/export:AreAllAccessesGranted=advapi32.AreAllAccessesGranted") // XP
#pragma comment(linker, "/export:AreAnyAccessesGranted=advapi32.AreAnyAccessesGranted") // XP
#pragma comment(linker, "/export:AuditComputeEffectivePolicyBySid=advapi32.AuditComputeEffectivePolicyBySid")
#pragma comment(linker, "/export:AuditComputeEffectivePolicyByToken=advapi32.AuditComputeEffectivePolicyByToken")
#pragma comment(linker, "/export:AuditEnumerateCategories=advapi32.AuditEnumerateCategories")
#pragma comment(linker, "/export:AuditEnumeratePerUserPolicy=advapi32.AuditEnumeratePerUserPolicy")
#pragma comment(linker, "/export:AuditEnumerateSubCategories=advapi32.AuditEnumerateSubCategories")
#pragma comment(linker, "/export:AuditFree=advapi32.AuditFree")
#pragma comment(linker, "/export:AuditLookupCategoryGuidFromCategoryId=advapi32.AuditLookupCategoryGuidFromCategoryId")
#pragma comment(linker, "/export:AuditLookupCategoryIdFromCategoryGuid=advapi32.AuditLookupCategoryIdFromCategoryGuid")
#pragma comment(linker, "/export:AuditLookupCategoryNameA=advapi32.AuditLookupCategoryNameA")
#pragma comment(linker, "/export:AuditLookupCategoryNameW=advapi32.AuditLookupCategoryNameW")
#pragma comment(linker, "/export:AuditLookupSubCategoryNameA=advapi32.AuditLookupSubCategoryNameA")
#pragma comment(linker, "/export:AuditLookupSubCategoryNameW=advapi32.AuditLookupSubCategoryNameW")
#pragma comment(linker, "/export:AuditQueryGlobalSaclA=advapi32.AuditQueryGlobalSaclA")
#pragma comment(linker, "/export:AuditQueryGlobalSaclW=advapi32.AuditQueryGlobalSaclW")
#pragma comment(linker, "/export:AuditQueryPerUserPolicy=advapi32.AuditQueryPerUserPolicy")
#pragma comment(linker, "/export:AuditQuerySecurity=advapi32.AuditQuerySecurity")
#pragma comment(linker, "/export:AuditQuerySystemPolicy=advapi32.AuditQuerySystemPolicy")
#pragma comment(linker, "/export:AuditSetGlobalSaclA=advapi32.AuditSetGlobalSaclA")
#pragma comment(linker, "/export:AuditSetGlobalSaclW=advapi32.AuditSetGlobalSaclW")
#pragma comment(linker, "/export:AuditSetPerUserPolicy=advapi32.AuditSetPerUserPolicy")
#pragma comment(linker, "/export:AuditSetSecurity=advapi32.AuditSetSecurity")
#pragma comment(linker, "/export:AuditSetSystemPolicy=advapi32.AuditSetSystemPolicy")
#pragma comment(linker, "/export:BackupEventLogA=advapi32.BackupEventLogA") // XP
#pragma comment(linker, "/export:BackupEventLogW=advapi32.BackupEventLogW") // XP
#pragma comment(linker, "/export:BaseRegCloseKey=advapi32.BaseRegCloseKey")
#pragma comment(linker, "/export:BaseRegCreateKey=advapi32.BaseRegCreateKey")
#pragma comment(linker, "/export:BaseRegDeleteKeyEx=advapi32.BaseRegDeleteKeyEx")
#pragma comment(linker, "/export:BaseRegDeleteValue=advapi32.BaseRegDeleteValue")
#pragma comment(linker, "/export:BaseRegFlushKey=advapi32.BaseRegFlushKey")
#pragma comment(linker, "/export:BaseRegGetVersion=advapi32.BaseRegGetVersion")
#pragma comment(linker, "/export:BaseRegLoadKey=advapi32.BaseRegLoadKey")
#pragma comment(linker, "/export:BaseRegOpenKey=advapi32.BaseRegOpenKey")
#pragma comment(linker, "/export:BaseRegRestoreKey=advapi32.BaseRegRestoreKey")
#pragma comment(linker, "/export:BaseRegSaveKeyEx=advapi32.BaseRegSaveKeyEx")
#pragma comment(linker, "/export:BaseRegSetKeySecurity=advapi32.BaseRegSetKeySecurity")
#pragma comment(linker, "/export:BaseRegSetValue=advapi32.BaseRegSetValue")
#pragma comment(linker, "/export:BaseRegUnLoadKey=advapi32.BaseRegUnLoadKey")
#pragma comment(linker, "/export:BuildExplicitAccessWithNameA=advapi32.BuildExplicitAccessWithNameA") // XP
#pragma comment(linker, "/export:BuildExplicitAccessWithNameW=advapi32.BuildExplicitAccessWithNameW") // XP
#pragma comment(linker, "/export:BuildImpersonateExplicitAccessWithNameA=advapi32.BuildImpersonateExplicitAccessWithNameA") // XP
#pragma comment(linker, "/export:BuildImpersonateExplicitAccessWithNameW=advapi32.BuildImpersonateExplicitAccessWithNameW") // XP
#pragma comment(linker, "/export:BuildImpersonateTrusteeA=advapi32.BuildImpersonateTrusteeA") // XP
#pragma comment(linker, "/export:BuildImpersonateTrusteeW=advapi32.BuildImpersonateTrusteeW") // XP
#pragma comment(linker, "/export:BuildSecurityDescriptorA=advapi32.BuildSecurityDescriptorA") // XP
#pragma comment(linker, "/export:BuildSecurityDescriptorW=advapi32.BuildSecurityDescriptorW") // XP
#pragma comment(linker, "/export:BuildTrusteeWithNameA=advapi32.BuildTrusteeWithNameA") // XP
#pragma comment(linker, "/export:BuildTrusteeWithNameW=advapi32.BuildTrusteeWithNameW") // XP
#pragma comment(linker, "/export:BuildTrusteeWithObjectsAndNameA=advapi32.BuildTrusteeWithObjectsAndNameA") // XP
#pragma comment(linker, "/export:BuildTrusteeWithObjectsAndNameW=advapi32.BuildTrusteeWithObjectsAndNameW") // XP
#pragma comment(linker, "/export:BuildTrusteeWithObjectsAndSidA=advapi32.BuildTrusteeWithObjectsAndSidA") // XP
#pragma comment(linker, "/export:BuildTrusteeWithObjectsAndSidW=advapi32.BuildTrusteeWithObjectsAndSidW") // XP
#pragma comment(linker, "/export:BuildTrusteeWithSidA=advapi32.BuildTrusteeWithSidA") // XP
#pragma comment(linker, "/export:BuildTrusteeWithSidW=advapi32.BuildTrusteeWithSidW") // XP
#pragma comment(linker, "/export:CancelOverlappedAccess=advapi32.CancelOverlappedAccess") // XP
#pragma comment(linker, "/export:ChangeServiceConfig2A=advapi32.ChangeServiceConfig2A") // XP
#pragma comment(linker, "/export:ChangeServiceConfig2W=advapi32.ChangeServiceConfig2W") // XP
#pragma comment(linker, "/export:ChangeServiceConfigA=advapi32.ChangeServiceConfigA") // XP
#pragma comment(linker, "/export:ChangeServiceConfigW=advapi32.ChangeServiceConfigW") // XP
#pragma comment(linker, "/export:CheckForHiberboot=advapi32.CheckForHiberboot")
#pragma comment(linker, "/export:CheckTokenMembership=advapi32.CheckTokenMembership") // XP
#pragma comment(linker, "/export:ClearEventLogA=advapi32.ClearEventLogA") // XP
#pragma comment(linker, "/export:ClearEventLogW=advapi32.ClearEventLogW") // XP
#pragma comment(linker, "/export:CloseCodeAuthzLevel=advapi32.CloseCodeAuthzLevel") // XP
#pragma comment(linker, "/export:CloseEncryptedFileRaw=advapi32.CloseEncryptedFileRaw") // XP
#pragma comment(linker, "/export:CloseEventLog=advapi32.CloseEventLog") // XP
#pragma comment(linker, "/export:CloseServiceHandle=advapi32.CloseServiceHandle") // XP
#pragma comment(linker, "/export:CloseThreadWaitChainSession=advapi32.CloseThreadWaitChainSession")
#pragma comment(linker, "/export:CloseTrace=advapi32.CloseTrace") // XP
#pragma comment(linker, "/export:CommandLineFromMsiDescriptor=advapi32.CommandLineFromMsiDescriptor") // XP
#pragma comment(linker, "/export:ComputeAccessTokenFromCodeAuthzLevel=advapi32.ComputeAccessTokenFromCodeAuthzLevel") // XP
#pragma comment(linker, "/export:ControlService=advapi32.ControlService") // XP
#pragma comment(linker, "/export:ControlServiceExA=advapi32.ControlServiceExA")
#pragma comment(linker, "/export:ControlServiceExW=advapi32.ControlServiceExW")
#pragma comment(linker, "/export:ControlTraceA=advapi32.ControlTraceA") // XP
#pragma comment(linker, "/export:ControlTraceW=advapi32.ControlTraceW") // XP
#pragma comment(linker, "/export:ConvertAccessToSecurityDescriptorA=advapi32.ConvertAccessToSecurityDescriptorA") // XP
#pragma comment(linker, "/export:ConvertAccessToSecurityDescriptorW=advapi32.ConvertAccessToSecurityDescriptorW") // XP
#pragma comment(linker, "/export:ConvertSDToStringSDDomainW=advapi32.ConvertSDToStringSDDomainW")
#pragma comment(linker, "/export:ConvertSDToStringSDRootDomainA=advapi32.ConvertSDToStringSDRootDomainA") // XP
#pragma comment(linker, "/export:ConvertSDToStringSDRootDomainW=advapi32.ConvertSDToStringSDRootDomainW") // XP
#pragma comment(linker, "/export:ConvertSecurityDescriptorToAccessA=advapi32.ConvertSecurityDescriptorToAccessA") // XP
#pragma comment(linker, "/export:ConvertSecurityDescriptorToAccessNamedA=advapi32.ConvertSecurityDescriptorToAccessNamedA") // XP
#pragma comment(linker, "/export:ConvertSecurityDescriptorToAccessNamedW=advapi32.ConvertSecurityDescriptorToAccessNamedW") // XP
#pragma comment(linker, "/export:ConvertSecurityDescriptorToAccessW=advapi32.ConvertSecurityDescriptorToAccessW") // XP
#pragma comment(linker, "/export:ConvertSecurityDescriptorToStringSecurityDescriptorA=advapi32.ConvertSecurityDescriptorToStringSecurityDescriptorA") // XP
#pragma comment(linker, "/export:ConvertSecurityDescriptorToStringSecurityDescriptorW=advapi32.ConvertSecurityDescriptorToStringSecurityDescriptorW") // XP
#pragma comment(linker, "/export:ConvertSidToStringSidA=advapi32.ConvertSidToStringSidA") // XP
#pragma comment(linker, "/export:ConvertSidToStringSidW=advapi32.ConvertSidToStringSidW") // XP
#pragma comment(linker, "/export:ConvertStringSDToSDDomainA=advapi32.ConvertStringSDToSDDomainA") // XP
#pragma comment(linker, "/export:ConvertStringSDToSDDomainW=advapi32.ConvertStringSDToSDDomainW") // XP
#pragma comment(linker, "/export:ConvertStringSDToSDRootDomainA=advapi32.ConvertStringSDToSDRootDomainA") // XP
#pragma comment(linker, "/export:ConvertStringSDToSDRootDomainW=advapi32.ConvertStringSDToSDRootDomainW") // XP
#pragma comment(linker, "/export:ConvertStringSecurityDescriptorToSecurityDescriptorA=advapi32.ConvertStringSecurityDescriptorToSecurityDescriptorA") // XP
#pragma comment(linker, "/export:ConvertStringSecurityDescriptorToSecurityDescriptorW=advapi32.ConvertStringSecurityDescriptorToSecurityDescriptorW") // XP
#pragma comment(linker, "/export:ConvertStringSidToSidA=advapi32.ConvertStringSidToSidA") // XP
#pragma comment(linker, "/export:ConvertStringSidToSidW=advapi32.ConvertStringSidToSidW") // XP
#pragma comment(linker, "/export:ConvertToAutoInheritPrivateObjectSecurity=advapi32.ConvertToAutoInheritPrivateObjectSecurity") // XP
#pragma comment(linker, "/export:CopySid=advapi32.CopySid") // XP
#pragma comment(linker, "/export:CreateCodeAuthzLevel=advapi32.CreateCodeAuthzLevel") // XP
#pragma comment(linker, "/export:CreatePrivateObjectSecurity=advapi32.CreatePrivateObjectSecurity") // XP
#pragma comment(linker, "/export:CreatePrivateObjectSecurityEx=advapi32.CreatePrivateObjectSecurityEx") // XP
#pragma comment(linker, "/export:CreatePrivateObjectSecurityWithMultipleInheritance=advapi32.CreatePrivateObjectSecurityWithMultipleInheritance") // XP
#pragma comment(linker, "/export:CreateProcessAsUserA=advapi32.CreateProcessAsUserA") // XP
#pragma comment(linker, "/export:CreateProcessAsUserW=advapi32.CreateProcessAsUserW") // XP
#pragma comment(linker, "/export:CreateProcessWithLogonW=advapi32.CreateProcessWithLogonW") // XP
#pragma comment(linker, "/export:CreateProcessWithTokenW=advapi32.CreateProcessWithTokenW")
#pragma comment(linker, "/export:CreateRestrictedToken=advapi32.CreateRestrictedToken") // XP
#pragma comment(linker, "/export:CreateServiceA=advapi32.CreateServiceA") // XP
#pragma comment(linker, "/export:CreateServiceW=advapi32.CreateServiceW") // XP
#pragma comment(linker, "/export:CreateTraceInstanceId=advapi32.CreateTraceInstanceId") // XP
#pragma comment(linker, "/export:CreateWellKnownSid=advapi32.CreateWellKnownSid") // XP
#pragma comment(linker, "/export:CredBackupCredentials=advapi32.CredBackupCredentials")
#pragma comment(linker, "/export:CredDeleteA=advapi32.CredDeleteA") // XP
#pragma comment(linker, "/export:CredDeleteW=advapi32.CredDeleteW") // XP
#pragma comment(linker, "/export:CredEncryptAndMarshalBinaryBlob=advapi32.CredEncryptAndMarshalBinaryBlob")
#pragma comment(linker, "/export:CredEnumerateA=advapi32.CredEnumerateA") // XP
#pragma comment(linker, "/export:CredEnumerateW=advapi32.CredEnumerateW") // XP
#pragma comment(linker, "/export:CredFindBestCredentialA=advapi32.CredFindBestCredentialA")
#pragma comment(linker, "/export:CredFindBestCredentialW=advapi32.CredFindBestCredentialW")
#pragma comment(linker, "/export:CredFree=advapi32.CredFree") // XP
#pragma comment(linker, "/export:CredGetSessionTypes=advapi32.CredGetSessionTypes") // XP
#pragma comment(linker, "/export:CredGetTargetInfoA=advapi32.CredGetTargetInfoA") // XP
#pragma comment(linker, "/export:CredGetTargetInfoW=advapi32.CredGetTargetInfoW") // XP
#pragma comment(linker, "/export:CredIsMarshaledCredentialA=advapi32.CredIsMarshaledCredentialA") // XP
#pragma comment(linker, "/export:CredIsMarshaledCredentialW=advapi32.CredIsMarshaledCredentialW") // XP
#pragma comment(linker, "/export:CredIsProtectedA=advapi32.CredIsProtectedA")
#pragma comment(linker, "/export:CredIsProtectedW=advapi32.CredIsProtectedW")
#pragma comment(linker, "/export:CredMarshalCredentialA=advapi32.CredMarshalCredentialA") // XP
#pragma comment(linker, "/export:CredMarshalCredentialW=advapi32.CredMarshalCredentialW") // XP
#pragma comment(linker, "/export:CredProfileLoaded=advapi32.CredProfileLoaded") // XP
#pragma comment(linker, "/export:CredProfileLoadedEx=advapi32.CredProfileLoadedEx")
#pragma comment(linker, "/export:CredProfileUnloaded=advapi32.CredProfileUnloaded")
#pragma comment(linker, "/export:CredProtectA=advapi32.CredProtectA")
#pragma comment(linker, "/export:CredProtectW=advapi32.CredProtectW")
#pragma comment(linker, "/export:CredReadA=advapi32.CredReadA") // XP
#pragma comment(linker, "/export:CredReadByTokenHandle=advapi32.CredReadByTokenHandle")
#pragma comment(linker, "/export:CredReadDomainCredentialsA=advapi32.CredReadDomainCredentialsA") // XP
#pragma comment(linker, "/export:CredReadDomainCredentialsW=advapi32.CredReadDomainCredentialsW") // XP
#pragma comment(linker, "/export:CredReadW=advapi32.CredReadW") // XP
#pragma comment(linker, "/export:CredRenameA=advapi32.CredRenameA") // XP
#pragma comment(linker, "/export:CredRenameW=advapi32.CredRenameW") // XP
#pragma comment(linker, "/export:CredRestoreCredentials=advapi32.CredRestoreCredentials")
#pragma comment(linker, "/export:CredUnmarshalCredentialA=advapi32.CredUnmarshalCredentialA") // XP
#pragma comment(linker, "/export:CredUnmarshalCredentialW=advapi32.CredUnmarshalCredentialW") // XP
#pragma comment(linker, "/export:CredUnprotectA=advapi32.CredUnprotectA")
#pragma comment(linker, "/export:CredUnprotectW=advapi32.CredUnprotectW")
#pragma comment(linker, "/export:CredWriteA=advapi32.CredWriteA") // XP
#pragma comment(linker, "/export:CredWriteDomainCredentialsA=advapi32.CredWriteDomainCredentialsA") // XP
#pragma comment(linker, "/export:CredWriteDomainCredentialsW=advapi32.CredWriteDomainCredentialsW") // XP
#pragma comment(linker, "/export:CredWriteW=advapi32.CredWriteW") // XP
#pragma comment(linker, "/export:CredpConvertCredential=advapi32.CredpConvertCredential") // XP
#pragma comment(linker, "/export:CredpConvertOneCredentialSize=advapi32.CredpConvertOneCredentialSize")
#pragma comment(linker, "/export:CredpConvertTargetInfo=advapi32.CredpConvertTargetInfo") // XP
#pragma comment(linker, "/export:CredpDecodeCredential=advapi32.CredpDecodeCredential") // XP
#pragma comment(linker, "/export:CredpEncodeCredential=advapi32.CredpEncodeCredential") // XP
#pragma comment(linker, "/export:CredpEncodeSecret=advapi32.CredpEncodeSecret")
#pragma comment(linker, "/export:CryptAcquireContextA=advapi32.CryptAcquireContextA") // XP
#pragma comment(linker, "/export:CryptAcquireContextW=advapi32.CryptAcquireContextW") // XP
#pragma comment(linker, "/export:CryptContextAddRef=advapi32.CryptContextAddRef") // XP
#pragma comment(linker, "/export:CryptCreateHash=advapi32.CryptCreateHash") // XP
#pragma comment(linker, "/export:CryptDecrypt=advapi32.CryptDecrypt") // XP
#pragma comment(linker, "/export:CryptDeriveKey=advapi32.CryptDeriveKey") // XP
#pragma comment(linker, "/export:CryptDestroyHash=advapi32.CryptDestroyHash") // XP
#pragma comment(linker, "/export:CryptDestroyKey=advapi32.CryptDestroyKey") // XP
#pragma comment(linker, "/export:CryptDuplicateHash=advapi32.CryptDuplicateHash") // XP
#pragma comment(linker, "/export:CryptDuplicateKey=advapi32.CryptDuplicateKey") // XP
#pragma comment(linker, "/export:CryptEncrypt=advapi32.CryptEncrypt") // XP
#pragma comment(linker, "/export:CryptEnumProviderTypesA=advapi32.CryptEnumProviderTypesA") // XP
#pragma comment(linker, "/export:CryptEnumProviderTypesW=advapi32.CryptEnumProviderTypesW") // XP
#pragma comment(linker, "/export:CryptEnumProvidersA=advapi32.CryptEnumProvidersA") // XP
#pragma comment(linker, "/export:CryptEnumProvidersW=advapi32.CryptEnumProvidersW") // XP
#pragma comment(linker, "/export:CryptExportKey=advapi32.CryptExportKey") // XP
#pragma comment(linker, "/export:CryptGenKey=advapi32.CryptGenKey") // XP
#pragma comment(linker, "/export:CryptGenRandom=advapi32.CryptGenRandom") // XP
#pragma comment(linker, "/export:CryptGetDefaultProviderA=advapi32.CryptGetDefaultProviderA") // XP
#pragma comment(linker, "/export:CryptGetDefaultProviderW=advapi32.CryptGetDefaultProviderW") // XP
#pragma comment(linker, "/export:CryptGetHashParam=advapi32.CryptGetHashParam") // XP
#pragma comment(linker, "/export:CryptGetKeyParam=advapi32.CryptGetKeyParam") // XP
#pragma comment(linker, "/export:CryptGetProvParam=advapi32.CryptGetProvParam") // XP
#pragma comment(linker, "/export:CryptGetUserKey=advapi32.CryptGetUserKey") // XP
#pragma comment(linker, "/export:CryptHashData=advapi32.CryptHashData") // XP
#pragma comment(linker, "/export:CryptHashSessionKey=advapi32.CryptHashSessionKey") // XP
#pragma comment(linker, "/export:CryptImportKey=advapi32.CryptImportKey") // XP
#pragma comment(linker, "/export:CryptReleaseContext=advapi32.CryptReleaseContext") // XP
#pragma comment(linker, "/export:CryptSetHashParam=advapi32.CryptSetHashParam") // XP
#pragma comment(linker, "/export:CryptSetKeyParam=advapi32.CryptSetKeyParam") // XP
#pragma comment(linker, "/export:CryptSetProvParam=advapi32.CryptSetProvParam") // XP
#pragma comment(linker, "/export:CryptSetProviderA=advapi32.CryptSetProviderA") // XP
#pragma comment(linker, "/export:CryptSetProviderExA=advapi32.CryptSetProviderExA") // XP
#pragma comment(linker, "/export:CryptSetProviderExW=advapi32.CryptSetProviderExW") // XP
#pragma comment(linker, "/export:CryptSetProviderW=advapi32.CryptSetProviderW") // XP
#pragma comment(linker, "/export:CryptSignHashA=advapi32.CryptSignHashA") // XP
#pragma comment(linker, "/export:CryptSignHashW=advapi32.CryptSignHashW") // XP
#pragma comment(linker, "/export:CryptVerifySignatureA=advapi32.CryptVerifySignatureA") // XP
#pragma comment(linker, "/export:CryptVerifySignatureW=advapi32.CryptVerifySignatureW") // XP
#pragma comment(linker, "/export:CveEventWrite=advapi32.CveEventWrite")
#pragma comment(linker, "/export:DecryptFileA=advapi32.DecryptFileA") // XP
#pragma comment(linker, "/export:DecryptFileW=advapi32.DecryptFileW") // XP
#pragma comment(linker, "/export:DeleteAce=advapi32.DeleteAce") // XP
#pragma comment(linker, "/export:DeleteService=advapi32.DeleteService") // XP
#pragma comment(linker, "/export:DeregisterEventSource=advapi32.DeregisterEventSource") // XP
#pragma comment(linker, "/export:DestroyPrivateObjectSecurity=advapi32.DestroyPrivateObjectSecurity") // XP
#pragma comment(linker, "/export:DuplicateEncryptionInfoFile=advapi32.DuplicateEncryptionInfoFile") // XP
#pragma comment(linker, "/export:DuplicateToken=advapi32.DuplicateToken") // XP
#pragma comment(linker, "/export:DuplicateTokenEx=advapi32.DuplicateTokenEx") // XP
#pragma comment(linker, "/export:ElfBackupEventLogFileA=advapi32.ElfBackupEventLogFileA") // XP
#pragma comment(linker, "/export:ElfBackupEventLogFileW=advapi32.ElfBackupEventLogFileW") // XP
#pragma comment(linker, "/export:ElfChangeNotify=advapi32.ElfChangeNotify") // XP
#pragma comment(linker, "/export:ElfClearEventLogFileA=advapi32.ElfClearEventLogFileA") // XP
#pragma comment(linker, "/export:ElfClearEventLogFileW=advapi32.ElfClearEventLogFileW") // XP
#pragma comment(linker, "/export:ElfCloseEventLog=advapi32.ElfCloseEventLog") // XP
#pragma comment(linker, "/export:ElfDeregisterEventSource=advapi32.ElfDeregisterEventSource") // XP
#pragma comment(linker, "/export:ElfFlushEventLog=advapi32.ElfFlushEventLog") // XP
#pragma comment(linker, "/export:ElfNumberOfRecords=advapi32.ElfNumberOfRecords") // XP
#pragma comment(linker, "/export:ElfOldestRecord=advapi32.ElfOldestRecord") // XP
#pragma comment(linker, "/export:ElfOpenBackupEventLogA=advapi32.ElfOpenBackupEventLogA") // XP
#pragma comment(linker, "/export:ElfOpenBackupEventLogW=advapi32.ElfOpenBackupEventLogW") // XP
#pragma comment(linker, "/export:ElfOpenEventLogA=advapi32.ElfOpenEventLogA") // XP
#pragma comment(linker, "/export:ElfOpenEventLogW=advapi32.ElfOpenEventLogW") // XP
#pragma comment(linker, "/export:ElfReadEventLogA=advapi32.ElfReadEventLogA") // XP
#pragma comment(linker, "/export:ElfReadEventLogW=advapi32.ElfReadEventLogW") // XP
#pragma comment(linker, "/export:ElfRegisterEventSourceA=advapi32.ElfRegisterEventSourceA") // XP
#pragma comment(linker, "/export:ElfRegisterEventSourceW=advapi32.ElfRegisterEventSourceW") // XP
#pragma comment(linker, "/export:ElfReportEventA=advapi32.ElfReportEventA") // XP
#pragma comment(linker, "/export:ElfReportEventAndSourceW=advapi32.ElfReportEventAndSourceW")
#pragma comment(linker, "/export:ElfReportEventW=advapi32.ElfReportEventW") // XP
#pragma comment(linker, "/export:EnableTrace=advapi32.EnableTrace") // XP
#pragma comment(linker, "/export:EnableTraceEx=advapi32.EnableTraceEx")
#pragma comment(linker, "/export:EnableTraceEx2=advapi32.EnableTraceEx2")
#pragma comment(linker, "/export:EncryptFileA=advapi32.EncryptFileA") // XP
#pragma comment(linker, "/export:EncryptFileW=advapi32.EncryptFileW") // XP
#pragma comment(linker, "/export:EncryptedFileKeyInfo=advapi32.EncryptedFileKeyInfo") // XP
#pragma comment(linker, "/export:EncryptionDisable=advapi32.EncryptionDisable") // XP
#pragma comment(linker, "/export:EnumDependentServicesA=advapi32.EnumDependentServicesA") // XP
#pragma comment(linker, "/export:EnumDependentServicesW=advapi32.EnumDependentServicesW") // XP
#pragma comment(linker, "/export:EnumDynamicTimeZoneInformation=advapi32.EnumDynamicTimeZoneInformation")
#pragma comment(linker, "/export:EnumServiceGroupW=advapi32.EnumServiceGroupW") // XP
#pragma comment(linker, "/export:EnumServicesStatusA=advapi32.EnumServicesStatusA") // XP
#pragma comment(linker, "/export:EnumServicesStatusExA=advapi32.EnumServicesStatusExA") // XP
#pragma comment(linker, "/export:EnumServicesStatusExW=advapi32.EnumServicesStatusExW") // XP
#pragma comment(linker, "/export:EnumServicesStatusW=advapi32.EnumServicesStatusW") // XP
#pragma comment(linker, "/export:EnumerateTraceGuids=advapi32.EnumerateTraceGuids") // XP
#pragma comment(linker, "/export:EnumerateTraceGuidsEx=advapi32.EnumerateTraceGuidsEx")
#pragma comment(linker, "/export:EqualDomainSid=advapi32.EqualDomainSid") // XP
#pragma comment(linker, "/export:EqualPrefixSid=advapi32.EqualPrefixSid") // XP
#pragma comment(linker, "/export:EqualSid=advapi32.EqualSid") // XP
#pragma comment(linker, "/export:EventAccessControl=advapi32.EventAccessControl")
#pragma comment(linker, "/export:EventAccessQuery=advapi32.EventAccessQuery")
#pragma comment(linker, "/export:EventAccessRemove=advapi32.EventAccessRemove")
#pragma comment(linker, "/export:EventActivityIdControl=advapi32.EventActivityIdControl")
#pragma comment(linker, "/export:EventEnabled=advapi32.EventEnabled")
#pragma comment(linker, "/export:EventProviderEnabled=advapi32.EventProviderEnabled")
#pragma comment(linker, "/export:EventRegister=advapi32.EventRegister")
#pragma comment(linker, "/export:EventSetInformation=advapi32.EventSetInformation")
#pragma comment(linker, "/export:EventUnregister=advapi32.EventUnregister")
#pragma comment(linker, "/export:EventWrite=advapi32.EventWrite")
#pragma comment(linker, "/export:EventWriteEndScenario=advapi32.EventWriteEndScenario")
#pragma comment(linker, "/export:EventWriteEx=advapi32.EventWriteEx")
#pragma comment(linker, "/export:EventWriteStartScenario=advapi32.EventWriteStartScenario")
#pragma comment(linker, "/export:EventWriteString=advapi32.EventWriteString")
#pragma comment(linker, "/export:EventWriteTransfer=advapi32.EventWriteTransfer")
#pragma comment(linker, "/export:FileEncryptionStatusA=advapi32.FileEncryptionStatusA") // XP
#pragma comment(linker, "/export:FileEncryptionStatusW=advapi32.FileEncryptionStatusW") // XP
#pragma comment(linker, "/export:FindFirstFreeAce=advapi32.FindFirstFreeAce") // XP
#pragma comment(linker, "/export:FlushEfsCache=advapi32.FlushEfsCache")
#pragma comment(linker, "/export:FlushTraceA=advapi32.FlushTraceA") // XP
#pragma comment(linker, "/export:FlushTraceW=advapi32.FlushTraceW") // XP
#pragma comment(linker, "/export:FreeEncryptedFileKeyInfo=advapi32.FreeEncryptedFileKeyInfo") // XP
#pragma comment(linker, "/export:FreeEncryptedFileMetadata=advapi32.FreeEncryptedFileMetadata")
#pragma comment(linker, "/export:FreeEncryptionCertificateHashList=advapi32.FreeEncryptionCertificateHashList") // XP
#pragma comment(linker, "/export:FreeInheritedFromArray=advapi32.FreeInheritedFromArray") // XP
#pragma comment(linker, "/export:FreeSid=advapi32.FreeSid") // XP
#pragma comment(linker, "/export:GetAccessPermissionsForObjectA=advapi32.GetAccessPermissionsForObjectA") // XP
#pragma comment(linker, "/export:GetAccessPermissionsForObjectW=advapi32.GetAccessPermissionsForObjectW") // XP
#pragma comment(linker, "/export:GetAce=advapi32.GetAce") // XP
#pragma comment(linker, "/export:GetAclInformation=advapi32.GetAclInformation") // XP
#pragma comment(linker, "/export:GetAuditedPermissionsFromAclA=advapi32.GetAuditedPermissionsFromAclA") // XP
#pragma comment(linker, "/export:GetAuditedPermissionsFromAclW=advapi32.GetAuditedPermissionsFromAclW") // XP
#pragma comment(linker, "/export:GetCurrentHwProfileA=advapi32.GetCurrentHwProfileA") // XP
#pragma comment(linker, "/export:GetCurrentHwProfileW=advapi32.GetCurrentHwProfileW") // XP
#pragma comment(linker, "/export:GetDynamicTimeZoneInformationEffectiveYears=advapi32.GetDynamicTimeZoneInformationEffectiveYears")
#pragma comment(linker, "/export:GetEffectiveRightsFromAclA=advapi32.GetEffectiveRightsFromAclA") // XP
#pragma comment(linker, "/export:GetEffectiveRightsFromAclW=advapi32.GetEffectiveRightsFromAclW") // XP
#pragma comment(linker, "/export:GetEncryptedFileMetadata=advapi32.GetEncryptedFileMetadata")
#pragma comment(linker, "/export:GetEventLogInformation=advapi32.GetEventLogInformation") // XP
#pragma comment(linker, "/export:GetExplicitEntriesFromAclA=advapi32.GetExplicitEntriesFromAclA") // XP
#pragma comment(linker, "/export:GetExplicitEntriesFromAclW=advapi32.GetExplicitEntriesFromAclW") // XP
#pragma comment(linker, "/export:GetFileSecurityA=advapi32.GetFileSecurityA") // XP
#pragma comment(linker, "/export:GetFileSecurityW=advapi32.GetFileSecurityW") // XP
#pragma comment(linker, "/export:GetInformationCodeAuthzLevelW=advapi32.GetInformationCodeAuthzLevelW") // XP
#pragma comment(linker, "/export:GetInformationCodeAuthzPolicyW=advapi32.GetInformationCodeAuthzPolicyW") // XP
#pragma comment(linker, "/export:GetInheritanceSourceA=advapi32.GetInheritanceSourceA") // XP
#pragma comment(linker, "/export:GetInheritanceSourceW=advapi32.GetInheritanceSourceW") // XP
#pragma comment(linker, "/export:GetKernelObjectSecurity=advapi32.GetKernelObjectSecurity") // XP
#pragma comment(linker, "/export:GetLengthSid=advapi32.GetLengthSid") // XP
#pragma comment(linker, "/export:GetLocalManagedApplicationData=advapi32.GetLocalManagedApplicationData") // XP
#pragma comment(linker, "/export:GetLocalManagedApplications=advapi32.GetLocalManagedApplications") // XP
#pragma comment(linker, "/export:GetManagedApplicationCategories=advapi32.GetManagedApplicationCategories") // XP
#pragma comment(linker, "/export:GetManagedApplications=advapi32.GetManagedApplications") // XP
#pragma comment(linker, "/export:GetMultipleTrusteeA=advapi32.GetMultipleTrusteeA") // XP
#pragma comment(linker, "/export:GetMultipleTrusteeOperationA=advapi32.GetMultipleTrusteeOperationA") // XP
#pragma comment(linker, "/export:GetMultipleTrusteeOperationW=advapi32.GetMultipleTrusteeOperationW") // XP
#pragma comment(linker, "/export:GetMultipleTrusteeW=advapi32.GetMultipleTrusteeW") // XP
#pragma comment(linker, "/export:GetNamedSecurityInfoA=advapi32.GetNamedSecurityInfoA") // XP
#pragma comment(linker, "/export:GetNamedSecurityInfoExA=advapi32.GetNamedSecurityInfoExA") // XP
#pragma comment(linker, "/export:GetNamedSecurityInfoExW=advapi32.GetNamedSecurityInfoExW") // XP
#pragma comment(linker, "/export:GetNamedSecurityInfoW=advapi32.GetNamedSecurityInfoW") // XP
#pragma comment(linker, "/export:GetNumberOfEventLogRecords=advapi32.GetNumberOfEventLogRecords") // XP
#pragma comment(linker, "/export:GetOldestEventLogRecord=advapi32.GetOldestEventLogRecord") // XP
#pragma comment(linker, "/export:GetOverlappedAccessResults=advapi32.GetOverlappedAccessResults") // XP
#pragma comment(linker, "/export:GetPrivateObjectSecurity=advapi32.GetPrivateObjectSecurity") // XP
#pragma comment(linker, "/export:GetSecurityDescriptorControl=advapi32.GetSecurityDescriptorControl") // XP
#pragma comment(linker, "/export:GetSecurityDescriptorDacl=advapi32.GetSecurityDescriptorDacl") // XP
#pragma comment(linker, "/export:GetSecurityDescriptorGroup=advapi32.GetSecurityDescriptorGroup") // XP
#pragma comment(linker, "/export:GetSecurityDescriptorLength=advapi32.GetSecurityDescriptorLength") // XP
#pragma comment(linker, "/export:GetSecurityDescriptorOwner=advapi32.GetSecurityDescriptorOwner") // XP
#pragma comment(linker, "/export:GetSecurityDescriptorRMControl=advapi32.GetSecurityDescriptorRMControl") // XP
#pragma comment(linker, "/export:GetSecurityDescriptorSacl=advapi32.GetSecurityDescriptorSacl") // XP
#pragma comment(linker, "/export:GetSecurityInfo=advapi32.GetSecurityInfo") // XP
#pragma comment(linker, "/export:GetSecurityInfoExA=advapi32.GetSecurityInfoExA") // XP
#pragma comment(linker, "/export:GetSecurityInfoExW=advapi32.GetSecurityInfoExW") // XP
#pragma comment(linker, "/export:GetServiceDisplayNameA=advapi32.GetServiceDisplayNameA") // XP
#pragma comment(linker, "/export:GetServiceDisplayNameW=advapi32.GetServiceDisplayNameW") // XP
#pragma comment(linker, "/export:GetServiceKeyNameA=advapi32.GetServiceKeyNameA") // XP
#pragma comment(linker, "/export:GetServiceKeyNameW=advapi32.GetServiceKeyNameW") // XP
#pragma comment(linker, "/export:GetSidIdentifierAuthority=advapi32.GetSidIdentifierAuthority") // XP
#pragma comment(linker, "/export:GetSidLengthRequired=advapi32.GetSidLengthRequired") // XP
#pragma comment(linker, "/export:GetSidSubAuthority=advapi32.GetSidSubAuthority") // XP
#pragma comment(linker, "/export:GetSidSubAuthorityCount=advapi32.GetSidSubAuthorityCount") // XP
#pragma comment(linker, "/export:GetStringConditionFromBinary=advapi32.GetStringConditionFromBinary")
#pragma comment(linker, "/export:GetThreadWaitChain=advapi32.GetThreadWaitChain")
#pragma comment(linker, "/export:GetTokenInformation=advapi32.GetTokenInformation") // XP
#pragma comment(linker, "/export:GetTraceEnableFlags=advapi32.GetTraceEnableFlags") // XP
#pragma comment(linker, "/export:GetTraceEnableLevel=advapi32.GetTraceEnableLevel") // XP
#pragma comment(linker, "/export:GetTraceLoggerHandle=advapi32.GetTraceLoggerHandle") // XP
#pragma comment(linker, "/export:GetTrusteeFormA=advapi32.GetTrusteeFormA") // XP
#pragma comment(linker, "/export:GetTrusteeFormW=advapi32.GetTrusteeFormW") // XP
#pragma comment(linker, "/export:GetTrusteeNameA=advapi32.GetTrusteeNameA") // XP
#pragma comment(linker, "/export:GetTrusteeNameW=advapi32.GetTrusteeNameW") // XP
#pragma comment(linker, "/export:GetTrusteeTypeA=advapi32.GetTrusteeTypeA") // XP
#pragma comment(linker, "/export:GetTrusteeTypeW=advapi32.GetTrusteeTypeW") // XP
#pragma comment(linker, "/export:GetUserNameA=advapi32.GetUserNameA") // XP
#pragma comment(linker, "/export:GetUserNameW=advapi32.GetUserNameW") // XP
#pragma comment(linker, "/export:GetWindowsAccountDomainSid=advapi32.GetWindowsAccountDomainSid") // XP
#pragma comment(linker, "/export:I_QueryTagInformation=advapi32.I_QueryTagInformation")
#pragma comment(linker, "/export:I_ScGetCurrentGroupStateW=advapi32.I_ScGetCurrentGroupStateW") // XP
#pragma comment(linker, "/export:I_ScIsSecurityProcess=advapi32.I_ScIsSecurityProcess") // XP
#pragma comment(linker, "/export:I_ScPnPGetServiceName=advapi32.I_ScPnPGetServiceName") // XP
#pragma comment(linker, "/export:I_ScQueryServiceConfig=advapi32.I_ScQueryServiceConfig")
#pragma comment(linker, "/export:I_ScRegisterPreshutdownRestart=advapi32.I_ScRegisterPreshutdownRestart")
#pragma comment(linker, "/export:I_ScReparseServiceDatabase=advapi32.I_ScReparseServiceDatabase")
#pragma comment(linker, "/export:I_ScSendPnPMessage=advapi32.I_ScSendPnPMessage")
#pragma comment(linker, "/export:I_ScSendTSMessage=advapi32.I_ScSendTSMessage") // XP
#pragma comment(linker, "/export:I_ScSetServiceBitsA=advapi32.I_ScSetServiceBitsA") // XP
#pragma comment(linker, "/export:I_ScSetServiceBitsW=advapi32.I_ScSetServiceBitsW") // XP
#pragma comment(linker, "/export:I_ScValidatePnPService=advapi32.I_ScValidatePnPService")
#pragma comment(linker, "/export:IdentifyCodeAuthzLevelW=advapi32.IdentifyCodeAuthzLevelW") // XP
#pragma comment(linker, "/export:ImpersonateAnonymousToken=advapi32.ImpersonateAnonymousToken") // XP
#pragma comment(linker, "/export:ImpersonateLoggedOnUser=advapi32.ImpersonateLoggedOnUser") // XP
#pragma comment(linker, "/export:ImpersonateNamedPipeClient=advapi32.ImpersonateNamedPipeClient") // XP
#pragma comment(linker, "/export:ImpersonateSelf=advapi32.ImpersonateSelf") // XP
#pragma comment(linker, "/export:InitializeAcl=advapi32.InitializeAcl") // XP
#pragma comment(linker, "/export:InitializeSecurityDescriptor=advapi32.InitializeSecurityDescriptor") // XP
#pragma comment(linker, "/export:InitializeSid=advapi32.InitializeSid") // XP
#pragma comment(linker, "/export:InitiateShutdownA=advapi32.InitiateShutdownA")
#pragma comment(linker, "/export:InitiateShutdownW=advapi32.InitiateShutdownW")
#pragma comment(linker, "/export:InitiateSystemShutdownA=advapi32.InitiateSystemShutdownA") // XP
#pragma comment(linker, "/export:InitiateSystemShutdownExA=advapi32.InitiateSystemShutdownExA") // XP
#pragma comment(linker, "/export:InitiateSystemShutdownExW=advapi32.InitiateSystemShutdownExW") // XP
#pragma comment(linker, "/export:InitiateSystemShutdownW=advapi32.InitiateSystemShutdownW") // XP
#pragma comment(linker, "/export:InstallApplication=advapi32.InstallApplication") // XP
#pragma comment(linker, "/export:IsTextUnicode=advapi32.IsTextUnicode") // XP
#pragma comment(linker, "/export:IsTokenRestricted=advapi32.IsTokenRestricted") // XP
#pragma comment(linker, "/export:IsTokenUntrusted=advapi32.IsTokenUntrusted") // XP
#pragma comment(linker, "/export:IsValidAcl=advapi32.IsValidAcl") // XP
#pragma comment(linker, "/export:IsValidRelativeSecurityDescriptor=advapi32.IsValidRelativeSecurityDescriptor")
#pragma comment(linker, "/export:IsValidSecurityDescriptor=advapi32.IsValidSecurityDescriptor") // XP
#pragma comment(linker, "/export:IsValidSid=advapi32.IsValidSid") // XP
#pragma comment(linker, "/export:IsWellKnownSid=advapi32.IsWellKnownSid") // XP
#pragma comment(linker, "/export:LockServiceDatabase=advapi32.LockServiceDatabase") // XP
#pragma comment(linker, "/export:LogonUserA=advapi32.LogonUserA") // XP
#pragma comment(linker, "/export:LogonUserExA=advapi32.LogonUserExA") // XP
#pragma comment(linker, "/export:LogonUserExExW=advapi32.LogonUserExExW")
#pragma comment(linker, "/export:LogonUserExW=advapi32.LogonUserExW") // XP
#pragma comment(linker, "/export:LogonUserW=advapi32.LogonUserW") // XP
#pragma comment(linker, "/export:LookupAccountNameA=advapi32.LookupAccountNameA") // XP
#pragma comment(linker, "/export:LookupAccountNameW=advapi32.LookupAccountNameW") // XP
#pragma comment(linker, "/export:LookupAccountSidA=advapi32.LookupAccountSidA") // XP
#pragma comment(linker, "/export:LookupAccountSidW=advapi32.LookupAccountSidW") // XP
#pragma comment(linker, "/export:LookupPrivilegeDisplayNameA=advapi32.LookupPrivilegeDisplayNameA") // XP
#pragma comment(linker, "/export:LookupPrivilegeDisplayNameW=advapi32.LookupPrivilegeDisplayNameW") // XP
#pragma comment(linker, "/export:LookupPrivilegeNameA=advapi32.LookupPrivilegeNameA") // XP
#pragma comment(linker, "/export:LookupPrivilegeNameW=advapi32.LookupPrivilegeNameW") // XP
#pragma comment(linker, "/export:LookupPrivilegeValueA=advapi32.LookupPrivilegeValueA") // XP
#pragma comment(linker, "/export:LookupPrivilegeValueW=advapi32.LookupPrivilegeValueW") // XP
#pragma comment(linker, "/export:LookupSecurityDescriptorPartsA=advapi32.LookupSecurityDescriptorPartsA") // XP
#pragma comment(linker, "/export:LookupSecurityDescriptorPartsW=advapi32.LookupSecurityDescriptorPartsW") // XP
#pragma comment(linker, "/export:LsaAddAccountRights=advapi32.LsaAddAccountRights") // XP
#pragma comment(linker, "/export:LsaAddPrivilegesToAccount=advapi32.LsaAddPrivilegesToAccount") // XP
#pragma comment(linker, "/export:LsaClearAuditLog=advapi32.LsaClearAuditLog") // XP
#pragma comment(linker, "/export:LsaClose=advapi32.LsaClose") // XP
#pragma comment(linker, "/export:LsaCreateAccount=advapi32.LsaCreateAccount") // XP
#pragma comment(linker, "/export:LsaCreateSecret=advapi32.LsaCreateSecret") // XP
#pragma comment(linker, "/export:LsaCreateTrustedDomain=advapi32.LsaCreateTrustedDomain") // XP
#pragma comment(linker, "/export:LsaCreateTrustedDomainEx=advapi32.LsaCreateTrustedDomainEx") // XP
#pragma comment(linker, "/export:LsaDelete=advapi32.LsaDelete") // XP
#pragma comment(linker, "/export:LsaDeleteTrustedDomain=advapi32.LsaDeleteTrustedDomain") // XP
#pragma comment(linker, "/export:LsaEnumerateAccountRights=advapi32.LsaEnumerateAccountRights") // XP
#pragma comment(linker, "/export:LsaEnumerateAccounts=advapi32.LsaEnumerateAccounts") // XP
#pragma comment(linker, "/export:LsaEnumerateAccountsWithUserRight=advapi32.LsaEnumerateAccountsWithUserRight") // XP
#pragma comment(linker, "/export:LsaEnumeratePrivileges=advapi32.LsaEnumeratePrivileges") // XP
#pragma comment(linker, "/export:LsaEnumeratePrivilegesOfAccount=advapi32.LsaEnumeratePrivilegesOfAccount") // XP
#pragma comment(linker, "/export:LsaEnumerateTrustedDomains=advapi32.LsaEnumerateTrustedDomains") // XP
#pragma comment(linker, "/export:LsaEnumerateTrustedDomainsEx=advapi32.LsaEnumerateTrustedDomainsEx") // XP
#pragma comment(linker, "/export:LsaFreeMemory=advapi32.LsaFreeMemory") // XP
#pragma comment(linker, "/export:LsaGetAppliedCAPIDs=advapi32.LsaGetAppliedCAPIDs")
#pragma comment(linker, "/export:LsaGetQuotasForAccount=advapi32.LsaGetQuotasForAccount") // XP
#pragma comment(linker, "/export:LsaGetRemoteUserName=advapi32.LsaGetRemoteUserName") // XP
#pragma comment(linker, "/export:LsaGetSystemAccessAccount=advapi32.LsaGetSystemAccessAccount") // XP
#pragma comment(linker, "/export:LsaGetUserName=advapi32.LsaGetUserName") // XP
#pragma comment(linker, "/export:LsaICLookupNames=advapi32.LsaICLookupNames") // XP
#pragma comment(linker, "/export:LsaICLookupNamesWithCreds=advapi32.LsaICLookupNamesWithCreds") // XP
#pragma comment(linker, "/export:LsaICLookupSids=advapi32.LsaICLookupSids") // XP
#pragma comment(linker, "/export:LsaICLookupSidsWithCreds=advapi32.LsaICLookupSidsWithCreds") // XP
#pragma comment(linker, "/export:LsaLookupNames=advapi32.LsaLookupNames") // XP
#pragma comment(linker, "/export:LsaLookupNames2=advapi32.LsaLookupNames2") // XP
#pragma comment(linker, "/export:LsaLookupPrivilegeDisplayName=advapi32.LsaLookupPrivilegeDisplayName") // XP
#pragma comment(linker, "/export:LsaLookupPrivilegeName=advapi32.LsaLookupPrivilegeName") // XP
#pragma comment(linker, "/export:LsaLookupPrivilegeValue=advapi32.LsaLookupPrivilegeValue") // XP
#pragma comment(linker, "/export:LsaLookupSids=advapi32.LsaLookupSids") // XP
#pragma comment(linker, "/export:LsaLookupSids2=advapi32.LsaLookupSids2")
#pragma comment(linker, "/export:LsaManageSidNameMapping=advapi32.LsaManageSidNameMapping")
#pragma comment(linker, "/export:LsaNtStatusToWinError=advapi32.LsaNtStatusToWinError") // XP
#pragma comment(linker, "/export:LsaOpenAccount=advapi32.LsaOpenAccount") // XP
#pragma comment(linker, "/export:LsaOpenPolicy=advapi32.LsaOpenPolicy") // XP
#pragma comment(linker, "/export:LsaOpenPolicySce=advapi32.LsaOpenPolicySce") // XP
#pragma comment(linker, "/export:LsaOpenSecret=advapi32.LsaOpenSecret") // XP
#pragma comment(linker, "/export:LsaOpenTrustedDomain=advapi32.LsaOpenTrustedDomain") // XP
#pragma comment(linker, "/export:LsaOpenTrustedDomainByName=advapi32.LsaOpenTrustedDomainByName") // XP
#pragma comment(linker, "/export:LsaQueryCAPs=advapi32.LsaQueryCAPs")
#pragma comment(linker, "/export:LsaQueryDomainInformationPolicy=advapi32.LsaQueryDomainInformationPolicy") // XP
#pragma comment(linker, "/export:LsaQueryForestTrustInformation=advapi32.LsaQueryForestTrustInformation") // XP
#pragma comment(linker, "/export:LsaQueryInfoTrustedDomain=advapi32.LsaQueryInfoTrustedDomain") // XP
#pragma comment(linker, "/export:LsaQueryInformationPolicy=advapi32.LsaQueryInformationPolicy") // XP
#pragma comment(linker, "/export:LsaQuerySecret=advapi32.LsaQuerySecret") // XP
#pragma comment(linker, "/export:LsaQuerySecurityObject=advapi32.LsaQuerySecurityObject") // XP
#pragma comment(linker, "/export:LsaQueryTrustedDomainInfo=advapi32.LsaQueryTrustedDomainInfo") // XP
#pragma comment(linker, "/export:LsaQueryTrustedDomainInfoByName=advapi32.LsaQueryTrustedDomainInfoByName") // XP
#pragma comment(linker, "/export:LsaRemoveAccountRights=advapi32.LsaRemoveAccountRights") // XP
#pragma comment(linker, "/export:LsaRemovePrivilegesFromAccount=advapi32.LsaRemovePrivilegesFromAccount") // XP
#pragma comment(linker, "/export:LsaRetrievePrivateData=advapi32.LsaRetrievePrivateData") // XP
#pragma comment(linker, "/export:LsaSetCAPs=advapi32.LsaSetCAPs")
#pragma comment(linker, "/export:LsaSetDomainInformationPolicy=advapi32.LsaSetDomainInformationPolicy") // XP
#pragma comment(linker, "/export:LsaSetForestTrustInformation=advapi32.LsaSetForestTrustInformation") // XP
#pragma comment(linker, "/export:LsaSetInformationPolicy=advapi32.LsaSetInformationPolicy") // XP
#pragma comment(linker, "/export:LsaSetInformationTrustedDomain=advapi32.LsaSetInformationTrustedDomain") // XP
#pragma comment(linker, "/export:LsaSetQuotasForAccount=advapi32.LsaSetQuotasForAccount") // XP
#pragma comment(linker, "/export:LsaSetSecret=advapi32.LsaSetSecret") // XP
#pragma comment(linker, "/export:LsaSetSecurityObject=advapi32.LsaSetSecurityObject") // XP
#pragma comment(linker, "/export:LsaSetSystemAccessAccount=advapi32.LsaSetSystemAccessAccount") // XP
#pragma comment(linker, "/export:LsaSetTrustedDomainInfoByName=advapi32.LsaSetTrustedDomainInfoByName") // XP
#pragma comment(linker, "/export:LsaSetTrustedDomainInformation=advapi32.LsaSetTrustedDomainInformation") // XP
#pragma comment(linker, "/export:LsaStorePrivateData=advapi32.LsaStorePrivateData") // XP
#pragma comment(linker, "/export:MD4Final=advapi32.MD4Final") // XP
#pragma comment(linker, "/export:MD4Init=advapi32.MD4Init") // XP
#pragma comment(linker, "/export:MD4Update=advapi32.MD4Update") // XP
#pragma comment(linker, "/export:MD5Final=advapi32.MD5Final") // XP
#pragma comment(linker, "/export:MD5Init=advapi32.MD5Init") // XP
#pragma comment(linker, "/export:MD5Update=advapi32.MD5Update") // XP
#pragma comment(linker, "/export:MIDL_user_free_Ext=advapi32.MIDL_user_free_Ext")
#pragma comment(linker, "/export:MSChapSrvChangePassword=advapi32.MSChapSrvChangePassword") // XP
#pragma comment(linker, "/export:MSChapSrvChangePassword2=advapi32.MSChapSrvChangePassword2") // XP
#pragma comment(linker, "/export:MakeAbsoluteSD=advapi32.MakeAbsoluteSD") // XP
#pragma comment(linker, "/export:MakeAbsoluteSD2=advapi32.MakeAbsoluteSD2") // XP
#pragma comment(linker, "/export:MakeSelfRelativeSD=advapi32.MakeSelfRelativeSD") // XP
#pragma comment(linker, "/export:MapGenericMask=advapi32.MapGenericMask") // XP
#pragma comment(linker, "/export:NotifyBootConfigStatus=advapi32.NotifyBootConfigStatus") // XP
#pragma comment(linker, "/export:NotifyChangeEventLog=advapi32.NotifyChangeEventLog") // XP
#pragma comment(linker, "/export:NotifyServiceStatusChange=advapi32.NotifyServiceStatusChange")
#pragma comment(linker, "/export:NotifyServiceStatusChangeA=advapi32.NotifyServiceStatusChangeA")
#pragma comment(linker, "/export:NotifyServiceStatusChangeW=advapi32.NotifyServiceStatusChangeW")
#pragma comment(linker, "/export:NpGetUserName=advapi32.NpGetUserName")
#pragma comment(linker, "/export:ObjectCloseAuditAlarmA=advapi32.ObjectCloseAuditAlarmA") // XP
#pragma comment(linker, "/export:ObjectCloseAuditAlarmW=advapi32.ObjectCloseAuditAlarmW") // XP
#pragma comment(linker, "/export:ObjectDeleteAuditAlarmA=advapi32.ObjectDeleteAuditAlarmA") // XP
#pragma comment(linker, "/export:ObjectDeleteAuditAlarmW=advapi32.ObjectDeleteAuditAlarmW") // XP
#pragma comment(linker, "/export:ObjectOpenAuditAlarmA=advapi32.ObjectOpenAuditAlarmA") // XP
#pragma comment(linker, "/export:ObjectOpenAuditAlarmW=advapi32.ObjectOpenAuditAlarmW") // XP
#pragma comment(linker, "/export:ObjectPrivilegeAuditAlarmA=advapi32.ObjectPrivilegeAuditAlarmA") // XP
#pragma comment(linker, "/export:ObjectPrivilegeAuditAlarmW=advapi32.ObjectPrivilegeAuditAlarmW") // XP
#pragma comment(linker, "/export:OpenBackupEventLogA=advapi32.OpenBackupEventLogA") // XP
#pragma comment(linker, "/export:OpenBackupEventLogW=advapi32.OpenBackupEventLogW") // XP
#pragma comment(linker, "/export:OpenEncryptedFileRawA=advapi32.OpenEncryptedFileRawA") // XP
#pragma comment(linker, "/export:OpenEncryptedFileRawW=advapi32.OpenEncryptedFileRawW") // XP
#pragma comment(linker, "/export:OpenEventLogA=advapi32.OpenEventLogA") // XP
#pragma comment(linker, "/export:OpenEventLogW=advapi32.OpenEventLogW") // XP
#pragma comment(linker, "/export:OpenProcessToken=advapi32.OpenProcessToken") // XP
#pragma comment(linker, "/export:OpenSCManagerA=advapi32.OpenSCManagerA") // XP
#pragma comment(linker, "/export:OpenSCManagerW=advapi32.OpenSCManagerW") // XP
#pragma comment(linker, "/export:OpenServiceA=advapi32.OpenServiceA") // XP
#pragma comment(linker, "/export:OpenServiceW=advapi32.OpenServiceW") // XP
#pragma comment(linker, "/export:OpenThreadToken=advapi32.OpenThreadToken") // XP
#pragma comment(linker, "/export:OpenThreadWaitChainSession=advapi32.OpenThreadWaitChainSession")
#pragma comment(linker, "/export:OpenTraceA=advapi32.OpenTraceA") // XP
#pragma comment(linker, "/export:OpenTraceW=advapi32.OpenTraceW") // XP
#pragma comment(linker, "/export:OperationEnd=advapi32.OperationEnd")
#pragma comment(linker, "/export:OperationStart=advapi32.OperationStart")
#pragma comment(linker, "/export:PerfAddCounters=advapi32.PerfAddCounters")
#pragma comment(linker, "/export:PerfCloseQueryHandle=advapi32.PerfCloseQueryHandle")
#pragma comment(linker, "/export:PerfCreateInstance=advapi32.PerfCreateInstance")
#pragma comment(linker, "/export:PerfDecrementULongCounterValue=advapi32.PerfDecrementULongCounterValue")
#pragma comment(linker, "/export:PerfDecrementULongLongCounterValue=advapi32.PerfDecrementULongLongCounterValue")
#pragma comment(linker, "/export:PerfDeleteCounters=advapi32.PerfDeleteCounters")
#pragma comment(linker, "/export:PerfDeleteInstance=advapi32.PerfDeleteInstance")
#pragma comment(linker, "/export:PerfEnumerateCounterSet=advapi32.PerfEnumerateCounterSet")
#pragma comment(linker, "/export:PerfEnumerateCounterSetInstances=advapi32.PerfEnumerateCounterSetInstances")
#pragma comment(linker, "/export:PerfIncrementULongCounterValue=advapi32.PerfIncrementULongCounterValue")
#pragma comment(linker, "/export:PerfIncrementULongLongCounterValue=advapi32.PerfIncrementULongLongCounterValue")
#pragma comment(linker, "/export:PerfOpenQueryHandle=advapi32.PerfOpenQueryHandle")
#pragma comment(linker, "/export:PerfQueryCounterData=advapi32.PerfQueryCounterData")
#pragma comment(linker, "/export:PerfQueryCounterInfo=advapi32.PerfQueryCounterInfo")
#pragma comment(linker, "/export:PerfQueryCounterSetRegistrationInfo=advapi32.PerfQueryCounterSetRegistrationInfo")
#pragma comment(linker, "/export:PerfQueryInstance=advapi32.PerfQueryInstance")
#pragma comment(linker, "/export:PerfRegCloseKey=advapi32.PerfRegCloseKey")
#pragma comment(linker, "/export:PerfRegEnumKey=advapi32.PerfRegEnumKey")
#pragma comment(linker, "/export:PerfRegEnumValue=advapi32.PerfRegEnumValue")
#pragma comment(linker, "/export:PerfRegQueryInfoKey=advapi32.PerfRegQueryInfoKey")
#pragma comment(linker, "/export:PerfRegQueryValue=advapi32.PerfRegQueryValue")
#pragma comment(linker, "/export:PerfRegSetValue=advapi32.PerfRegSetValue")
#pragma comment(linker, "/export:PerfSetCounterRefValue=advapi32.PerfSetCounterRefValue")
#pragma comment(linker, "/export:PerfSetCounterSetInfo=advapi32.PerfSetCounterSetInfo")
#pragma comment(linker, "/export:PerfSetULongCounterValue=advapi32.PerfSetULongCounterValue")
#pragma comment(linker, "/export:PerfSetULongLongCounterValue=advapi32.PerfSetULongLongCounterValue")
#pragma comment(linker, "/export:PerfStartProvider=advapi32.PerfStartProvider")
#pragma comment(linker, "/export:PerfStartProviderEx=advapi32.PerfStartProviderEx")
#pragma comment(linker, "/export:PerfStopProvider=advapi32.PerfStopProvider")
#pragma comment(linker, "/export:PrivilegeCheck=advapi32.PrivilegeCheck") // XP
#pragma comment(linker, "/export:PrivilegedServiceAuditAlarmA=advapi32.PrivilegedServiceAuditAlarmA") // XP
#pragma comment(linker, "/export:PrivilegedServiceAuditAlarmW=advapi32.PrivilegedServiceAuditAlarmW") // XP
#pragma comment(linker, "/export:ProcessIdleTasks=advapi32.ProcessIdleTasks") // XP
#pragma comment(linker, "/export:ProcessIdleTasksW=advapi32.ProcessIdleTasksW")
#pragma comment(linker, "/export:ProcessTrace=advapi32.ProcessTrace") // XP
#pragma comment(linker, "/export:QueryAllTracesA=advapi32.QueryAllTracesA") // XP
#pragma comment(linker, "/export:QueryAllTracesW=advapi32.QueryAllTracesW") // XP
#pragma comment(linker, "/export:QueryLocalUserServiceName=advapi32.QueryLocalUserServiceName")
#pragma comment(linker, "/export:QueryRecoveryAgentsOnEncryptedFile=advapi32.QueryRecoveryAgentsOnEncryptedFile") // XP
#pragma comment(linker, "/export:QuerySecurityAccessMask=advapi32.QuerySecurityAccessMask")
#pragma comment(linker, "/export:QueryServiceConfig2A=advapi32.QueryServiceConfig2A") // XP
#pragma comment(linker, "/export:QueryServiceConfig2W=advapi32.QueryServiceConfig2W") // XP
#pragma comment(linker, "/export:QueryServiceConfigA=advapi32.QueryServiceConfigA") // XP
#pragma comment(linker, "/export:QueryServiceConfigW=advapi32.QueryServiceConfigW") // XP
#pragma comment(linker, "/export:QueryServiceDynamicInformation=advapi32.QueryServiceDynamicInformation")
#pragma comment(linker, "/export:QueryServiceLockStatusA=advapi32.QueryServiceLockStatusA") // XP
#pragma comment(linker, "/export:QueryServiceLockStatusW=advapi32.QueryServiceLockStatusW") // XP
#pragma comment(linker, "/export:QueryServiceObjectSecurity=advapi32.QueryServiceObjectSecurity") // XP
#pragma comment(linker, "/export:QueryServiceStatus=advapi32.QueryServiceStatus") // XP
#pragma comment(linker, "/export:QueryServiceStatusEx=advapi32.QueryServiceStatusEx") // XP
#pragma comment(linker, "/export:QueryTraceA=advapi32.QueryTraceA") // XP
#pragma comment(linker, "/export:QueryTraceW=advapi32.QueryTraceW") // XP
#pragma comment(linker, "/export:QueryUserServiceName=advapi32.QueryUserServiceName")
#pragma comment(linker, "/export:QueryUsersOnEncryptedFile=advapi32.QueryUsersOnEncryptedFile") // XP
#pragma comment(linker, "/export:ReadEncryptedFileRaw=advapi32.ReadEncryptedFileRaw") // XP
#pragma comment(linker, "/export:ReadEventLogA=advapi32.ReadEventLogA") // XP
#pragma comment(linker, "/export:ReadEventLogW=advapi32.ReadEventLogW") // XP
#pragma comment(linker, "/export:RegCloseKey=advapi32.RegCloseKey") // XP
#pragma comment(linker, "/export:RegConnectRegistryA=advapi32.RegConnectRegistryA") // XP
#pragma comment(linker, "/export:RegConnectRegistryExA=advapi32.RegConnectRegistryExA")
#pragma comment(linker, "/export:RegConnectRegistryExW=advapi32.RegConnectRegistryExW")
#pragma comment(linker, "/export:RegConnectRegistryW=advapi32.RegConnectRegistryW") // XP
#pragma comment(linker, "/export:RegCopyTreeA=advapi32.RegCopyTreeA")
#pragma comment(linker, "/export:RegCopyTreeW=advapi32.RegCopyTreeW")
#pragma comment(linker, "/export:RegCreateKeyA=advapi32.RegCreateKeyA") // XP
#pragma comment(linker, "/export:RegCreateKeyExA=advapi32.RegCreateKeyExA") // XP
#pragma comment(linker, "/export:RegCreateKeyExW=advapi32.RegCreateKeyExW") // XP
#pragma comment(linker, "/export:RegCreateKeyTransactedA=advapi32.RegCreateKeyTransactedA")
#pragma comment(linker, "/export:RegCreateKeyTransactedW=advapi32.RegCreateKeyTransactedW")
#pragma comment(linker, "/export:RegCreateKeyW=advapi32.RegCreateKeyW") // XP
#pragma comment(linker, "/export:RegDeleteKeyA=advapi32.RegDeleteKeyA") // XP
#pragma comment(linker, "/export:RegDeleteKeyExA=advapi32.RegDeleteKeyExA")
#pragma comment(linker, "/export:RegDeleteKeyExW=advapi32.RegDeleteKeyExW")
#pragma comment(linker, "/export:RegDeleteKeyTransactedA=advapi32.RegDeleteKeyTransactedA")
#pragma comment(linker, "/export:RegDeleteKeyTransactedW=advapi32.RegDeleteKeyTransactedW")
#pragma comment(linker, "/export:RegDeleteKeyValueA=advapi32.RegDeleteKeyValueA")
#pragma comment(linker, "/export:RegDeleteKeyValueW=advapi32.RegDeleteKeyValueW")
#pragma comment(linker, "/export:RegDeleteKeyW=advapi32.RegDeleteKeyW") // XP
#pragma comment(linker, "/export:RegDeleteTreeA=advapi32.RegDeleteTreeA")
#pragma comment(linker, "/export:RegDeleteTreeW=advapi32.RegDeleteTreeW")
#pragma comment(linker, "/export:RegDeleteValueA=advapi32.RegDeleteValueA") // XP
#pragma comment(linker, "/export:RegDeleteValueW=advapi32.RegDeleteValueW") // XP
#pragma comment(linker, "/export:RegDisablePredefinedCache=advapi32.RegDisablePredefinedCache") // XP
#pragma comment(linker, "/export:RegDisablePredefinedCacheEx=advapi32.RegDisablePredefinedCacheEx") // XP
#pragma comment(linker, "/export:RegDisableReflectionKey=advapi32.RegDisableReflectionKey")
#pragma comment(linker, "/export:RegEnableReflectionKey=advapi32.RegEnableReflectionKey")
#pragma comment(linker, "/export:RegEnumKeyA=advapi32.RegEnumKeyA") // XP
#pragma comment(linker, "/export:RegEnumKeyExA=advapi32.RegEnumKeyExA") // XP
#pragma comment(linker, "/export:RegEnumKeyExW=advapi32.RegEnumKeyExW") // XP
#pragma comment(linker, "/export:RegEnumKeyW=advapi32.RegEnumKeyW") // XP
#pragma comment(linker, "/export:RegEnumValueA=advapi32.RegEnumValueA") // XP
#pragma comment(linker, "/export:RegEnumValueW=advapi32.RegEnumValueW") // XP
#pragma comment(linker, "/export:RegFlushKey=advapi32.RegFlushKey") // XP
#pragma comment(linker, "/export:RegGetKeySecurity=advapi32.RegGetKeySecurity") // XP
#pragma comment(linker, "/export:RegGetValueA=advapi32.RegGetValueA")
#pragma comment(linker, "/export:RegGetValueW=advapi32.RegGetValueW")
#pragma comment(linker, "/export:RegLoadAppKeyA=advapi32.RegLoadAppKeyA")
#pragma comment(linker, "/export:RegLoadAppKeyW=advapi32.RegLoadAppKeyW")
#pragma comment(linker, "/export:RegLoadKeyA=advapi32.RegLoadKeyA") // XP
#pragma comment(linker, "/export:RegLoadKeyW=advapi32.RegLoadKeyW") // XP
#pragma comment(linker, "/export:RegLoadMUIStringA=advapi32.RegLoadMUIStringA")
#pragma comment(linker, "/export:RegLoadMUIStringW=advapi32.RegLoadMUIStringW")
#pragma comment(linker, "/export:RegNotifyChangeKeyValue=advapi32.RegNotifyChangeKeyValue") // XP
#pragma comment(linker, "/export:RegOpenCurrentUser=advapi32.RegOpenCurrentUser") // XP
#pragma comment(linker, "/export:RegOpenKeyA=advapi32.RegOpenKeyA") // XP
#pragma comment(linker, "/export:RegOpenKeyExA=advapi32.RegOpenKeyExA") // XP
#pragma comment(linker, "/export:RegOpenKeyExW=advapi32.RegOpenKeyExW") // XP
#pragma comment(linker, "/export:RegOpenKeyTransactedA=advapi32.RegOpenKeyTransactedA")
#pragma comment(linker, "/export:RegOpenKeyTransactedW=advapi32.RegOpenKeyTransactedW")
#pragma comment(linker, "/export:RegOpenKeyW=advapi32.RegOpenKeyW") // XP
#pragma comment(linker, "/export:RegOpenUserClassesRoot=advapi32.RegOpenUserClassesRoot") // XP
#pragma comment(linker, "/export:RegOverridePredefKey=advapi32.RegOverridePredefKey") // XP
#pragma comment(linker, "/export:RegQueryInfoKeyA=advapi32.RegQueryInfoKeyA") // XP
#pragma comment(linker, "/export:RegQueryInfoKeyW=advapi32.RegQueryInfoKeyW") // XP
#pragma comment(linker, "/export:RegQueryMultipleValuesA=advapi32.RegQueryMultipleValuesA") // XP
#pragma comment(linker, "/export:RegQueryMultipleValuesW=advapi32.RegQueryMultipleValuesW") // XP
#pragma comment(linker, "/export:RegQueryReflectionKey=advapi32.RegQueryReflectionKey")
#pragma comment(linker, "/export:RegQueryValueA=advapi32.RegQueryValueA") // XP
#pragma comment(linker, "/export:RegQueryValueExA=advapi32.RegQueryValueExA") // XP
#pragma comment(linker, "/export:RegQueryValueExW=advapi32.RegQueryValueExW") // XP
#pragma comment(linker, "/export:RegQueryValueW=advapi32.RegQueryValueW") // XP
#pragma comment(linker, "/export:RegRenameKey=advapi32.RegRenameKey")
#pragma comment(linker, "/export:RegReplaceKeyA=advapi32.RegReplaceKeyA") // XP
#pragma comment(linker, "/export:RegReplaceKeyW=advapi32.RegReplaceKeyW") // XP
#pragma comment(linker, "/export:RegRestoreKeyA=advapi32.RegRestoreKeyA") // XP
#pragma comment(linker, "/export:RegRestoreKeyW=advapi32.RegRestoreKeyW") // XP
#pragma comment(linker, "/export:RegSaveKeyA=advapi32.RegSaveKeyA") // XP
#pragma comment(linker, "/export:RegSaveKeyExA=advapi32.RegSaveKeyExA") // XP
#pragma comment(linker, "/export:RegSaveKeyExW=advapi32.RegSaveKeyExW") // XP
#pragma comment(linker, "/export:RegSaveKeyW=advapi32.RegSaveKeyW") // XP
#pragma comment(linker, "/export:RegSetKeySecurity=advapi32.RegSetKeySecurity") // XP
#pragma comment(linker, "/export:RegSetKeyValueA=advapi32.RegSetKeyValueA")
#pragma comment(linker, "/export:RegSetKeyValueW=advapi32.RegSetKeyValueW")
#pragma comment(linker, "/export:RegSetValueA=advapi32.RegSetValueA") // XP
#pragma comment(linker, "/export:RegSetValueExA=advapi32.RegSetValueExA") // XP
#pragma comment(linker, "/export:RegSetValueExW=advapi32.RegSetValueExW") // XP
#pragma comment(linker, "/export:RegSetValueW=advapi32.RegSetValueW") // XP
#pragma comment(linker, "/export:RegUnLoadKeyA=advapi32.RegUnLoadKeyA") // XP
#pragma comment(linker, "/export:RegUnLoadKeyW=advapi32.RegUnLoadKeyW") // XP
#pragma comment(linker, "/export:RegisterEventSourceA=advapi32.RegisterEventSourceA") // XP
#pragma comment(linker, "/export:RegisterEventSourceW=advapi32.RegisterEventSourceW") // XP
#pragma comment(linker, "/export:RegisterIdleTask=advapi32.RegisterIdleTask") // XP
#pragma comment(linker, "/export:RegisterServiceCtrlHandlerA=advapi32.RegisterServiceCtrlHandlerA") // XP
#pragma comment(linker, "/export:RegisterServiceCtrlHandlerExA=advapi32.RegisterServiceCtrlHandlerExA") // XP
#pragma comment(linker, "/export:RegisterServiceCtrlHandlerExW=advapi32.RegisterServiceCtrlHandlerExW") // XP
#pragma comment(linker, "/export:RegisterServiceCtrlHandlerW=advapi32.RegisterServiceCtrlHandlerW") // XP
#pragma comment(linker, "/export:RegisterTraceGuidsA=advapi32.RegisterTraceGuidsA") // XP
#pragma comment(linker, "/export:RegisterTraceGuidsW=advapi32.RegisterTraceGuidsW") // XP
#pragma comment(linker, "/export:RegisterWaitChainCOMCallback=advapi32.RegisterWaitChainCOMCallback")
#pragma comment(linker, "/export:RemoteRegEnumKeyWrapper=advapi32.RemoteRegEnumKeyWrapper")
#pragma comment(linker, "/export:RemoteRegEnumValueWrapper=advapi32.RemoteRegEnumValueWrapper")
#pragma comment(linker, "/export:RemoteRegQueryInfoKeyWrapper=advapi32.RemoteRegQueryInfoKeyWrapper")
#pragma comment(linker, "/export:RemoteRegQueryValueWrapper=advapi32.RemoteRegQueryValueWrapper")
#pragma comment(linker, "/export:RemoveTraceCallback=advapi32.RemoveTraceCallback") // XP
#pragma comment(linker, "/export:RemoveUsersFromEncryptedFile=advapi32.RemoveUsersFromEncryptedFile") // XP
#pragma comment(linker, "/export:ReportEventA=advapi32.ReportEventA") // XP
#pragma comment(linker, "/export:ReportEventW=advapi32.ReportEventW") // XP
#pragma comment(linker, "/export:RevertToSelf=advapi32.RevertToSelf") // XP
#pragma comment(linker, "/export:SafeBaseRegGetKeySecurity=advapi32.SafeBaseRegGetKeySecurity")
#pragma comment(linker, "/export:SaferCloseLevel=advapi32.SaferCloseLevel") // XP
#pragma comment(linker, "/export:SaferComputeTokenFromLevel=advapi32.SaferComputeTokenFromLevel") // XP
#pragma comment(linker, "/export:SaferCreateLevel=advapi32.SaferCreateLevel") // XP
#pragma comment(linker, "/export:SaferGetLevelInformation=advapi32.SaferGetLevelInformation") // XP
#pragma comment(linker, "/export:SaferGetPolicyInformation=advapi32.SaferGetPolicyInformation") // XP
#pragma comment(linker, "/export:SaferIdentifyLevel=advapi32.SaferIdentifyLevel") // XP
#pragma comment(linker, "/export:SaferRecordEventLogEntry=advapi32.SaferRecordEventLogEntry") // XP
#pragma comment(linker, "/export:SaferSetLevelInformation=advapi32.SaferSetLevelInformation") // XP
#pragma comment(linker, "/export:SaferSetPolicyInformation=advapi32.SaferSetPolicyInformation") // XP
#pragma comment(linker, "/export:SaferiChangeRegistryScope=advapi32.SaferiChangeRegistryScope") // XP
#pragma comment(linker, "/export:SaferiCompareTokenLevels=advapi32.SaferiCompareTokenLevels") // XP
#pragma comment(linker, "/export:SaferiIsDllAllowed=advapi32.SaferiIsDllAllowed")
#pragma comment(linker, "/export:SaferiIsExecutableFileType=advapi32.SaferiIsExecutableFileType") // XP
#pragma comment(linker, "/export:SaferiPopulateDefaultsInRegistry=advapi32.SaferiPopulateDefaultsInRegistry") // XP
#pragma comment(linker, "/export:SaferiRecordEventLogEntry=advapi32.SaferiRecordEventLogEntry") // XP
#pragma comment(linker, "/export:SaferiSearchMatchingHashRules=advapi32.SaferiSearchMatchingHashRules") // XP
#pragma comment(linker, "/export:SetAclInformation=advapi32.SetAclInformation") // XP
#pragma comment(linker, "/export:SetEncryptedFileMetadata=advapi32.SetEncryptedFileMetadata")
#pragma comment(linker, "/export:SetEntriesInAccessListA=advapi32.SetEntriesInAccessListA") // XP
#pragma comment(linker, "/export:SetEntriesInAccessListW=advapi32.SetEntriesInAccessListW") // XP
#pragma comment(linker, "/export:SetEntriesInAclA=advapi32.SetEntriesInAclA") // XP
#pragma comment(linker, "/export:SetEntriesInAclW=advapi32.SetEntriesInAclW") // XP
#pragma comment(linker, "/export:SetEntriesInAuditListA=advapi32.SetEntriesInAuditListA") // XP
#pragma comment(linker, "/export:SetEntriesInAuditListW=advapi32.SetEntriesInAuditListW") // XP
#pragma comment(linker, "/export:SetFileSecurityA=advapi32.SetFileSecurityA") // XP
#pragma comment(linker, "/export:SetFileSecurityW=advapi32.SetFileSecurityW") // XP
#pragma comment(linker, "/export:SetInformationCodeAuthzLevelW=advapi32.SetInformationCodeAuthzLevelW") // XP
#pragma comment(linker, "/export:SetInformationCodeAuthzPolicyW=advapi32.SetInformationCodeAuthzPolicyW") // XP
#pragma comment(linker, "/export:SetKernelObjectSecurity=advapi32.SetKernelObjectSecurity") // XP
#pragma comment(linker, "/export:SetNamedSecurityInfoA=advapi32.SetNamedSecurityInfoA") // XP
#pragma comment(linker, "/export:SetNamedSecurityInfoExA=advapi32.SetNamedSecurityInfoExA") // XP
#pragma comment(linker, "/export:SetNamedSecurityInfoExW=advapi32.SetNamedSecurityInfoExW") // XP
#pragma comment(linker, "/export:SetNamedSecurityInfoW=advapi32.SetNamedSecurityInfoW") // XP
#pragma comment(linker, "/export:SetPrivateObjectSecurity=advapi32.SetPrivateObjectSecurity") // XP
#pragma comment(linker, "/export:SetPrivateObjectSecurityEx=advapi32.SetPrivateObjectSecurityEx") // XP
#pragma comment(linker, "/export:SetSecurityAccessMask=advapi32.SetSecurityAccessMask")
#pragma comment(linker, "/export:SetSecurityDescriptorControl=advapi32.SetSecurityDescriptorControl") // XP
#pragma comment(linker, "/export:SetSecurityDescriptorDacl=advapi32.SetSecurityDescriptorDacl") // XP
#pragma comment(linker, "/export:SetSecurityDescriptorGroup=advapi32.SetSecurityDescriptorGroup") // XP
#pragma comment(linker, "/export:SetSecurityDescriptorOwner=advapi32.SetSecurityDescriptorOwner") // XP
#pragma comment(linker, "/export:SetSecurityDescriptorRMControl=advapi32.SetSecurityDescriptorRMControl") // XP
#pragma comment(linker, "/export:SetSecurityDescriptorSacl=advapi32.SetSecurityDescriptorSacl") // XP
#pragma comment(linker, "/export:SetSecurityInfo=advapi32.SetSecurityInfo") // XP
#pragma comment(linker, "/export:SetSecurityInfoExA=advapi32.SetSecurityInfoExA") // XP
#pragma comment(linker, "/export:SetSecurityInfoExW=advapi32.SetSecurityInfoExW") // XP
#pragma comment(linker, "/export:SetServiceBits=advapi32.SetServiceBits") // XP
#pragma comment(linker, "/export:SetServiceObjectSecurity=advapi32.SetServiceObjectSecurity") // XP
#pragma comment(linker, "/export:SetServiceStatus=advapi32.SetServiceStatus") // XP
#pragma comment(linker, "/export:SetThreadToken=advapi32.SetThreadToken") // XP
#pragma comment(linker, "/export:SetTokenInformation=advapi32.SetTokenInformation") // XP
#pragma comment(linker, "/export:SetTraceCallback=advapi32.SetTraceCallback") // XP
#pragma comment(linker, "/export:SetUserFileEncryptionKey=advapi32.SetUserFileEncryptionKey") // XP
#pragma comment(linker, "/export:SetUserFileEncryptionKeyEx=advapi32.SetUserFileEncryptionKeyEx")
#pragma comment(linker, "/export:StartServiceA=advapi32.StartServiceA") // XP
#pragma comment(linker, "/export:StartServiceCtrlDispatcherA=advapi32.StartServiceCtrlDispatcherA") // XP
#pragma comment(linker, "/export:StartServiceCtrlDispatcherW=advapi32.StartServiceCtrlDispatcherW") // XP
#pragma comment(linker, "/export:StartServiceW=advapi32.StartServiceW") // XP
#pragma comment(linker, "/export:StartTraceA=advapi32.StartTraceA") // XP
#pragma comment(linker, "/export:StartTraceW=advapi32.StartTraceW") // XP
#pragma comment(linker, "/export:StopTraceA=advapi32.StopTraceA") // XP
#pragma comment(linker, "/export:StopTraceW=advapi32.StopTraceW") // XP
#pragma comment(linker, "/export:SystemFunction001=advapi32.SystemFunction001") // XP
#pragma comment(linker, "/export:SystemFunction002=advapi32.SystemFunction002") // XP
#pragma comment(linker, "/export:SystemFunction003=advapi32.SystemFunction003") // XP
#pragma comment(linker, "/export:SystemFunction004=advapi32.SystemFunction004") // XP
#pragma comment(linker, "/export:SystemFunction005=advapi32.SystemFunction005") // XP
#pragma comment(linker, "/export:SystemFunction006=advapi32.SystemFunction006") // XP
#pragma comment(linker, "/export:SystemFunction007=advapi32.SystemFunction007") // XP
#pragma comment(linker, "/export:SystemFunction008=advapi32.SystemFunction008") // XP
#pragma comment(linker, "/export:SystemFunction009=advapi32.SystemFunction009") // XP
#pragma comment(linker, "/export:SystemFunction010=advapi32.SystemFunction010") // XP
#pragma comment(linker, "/export:SystemFunction011=advapi32.SystemFunction011") // XP
#pragma comment(linker, "/export:SystemFunction012=advapi32.SystemFunction012") // XP
#pragma comment(linker, "/export:SystemFunction013=advapi32.SystemFunction013") // XP
#pragma comment(linker, "/export:SystemFunction014=advapi32.SystemFunction014") // XP
#pragma comment(linker, "/export:SystemFunction015=advapi32.SystemFunction015") // XP
#pragma comment(linker, "/export:SystemFunction016=advapi32.SystemFunction016") // XP
#pragma comment(linker, "/export:SystemFunction017=advapi32.SystemFunction017") // XP
#pragma comment(linker, "/export:SystemFunction018=advapi32.SystemFunction018") // XP
#pragma comment(linker, "/export:SystemFunction019=advapi32.SystemFunction019") // XP
#pragma comment(linker, "/export:SystemFunction020=advapi32.SystemFunction020") // XP
#pragma comment(linker, "/export:SystemFunction021=advapi32.SystemFunction021") // XP
#pragma comment(linker, "/export:SystemFunction022=advapi32.SystemFunction022") // XP
#pragma comment(linker, "/export:SystemFunction023=advapi32.SystemFunction023") // XP
#pragma comment(linker, "/export:SystemFunction024=advapi32.SystemFunction024") // XP
#pragma comment(linker, "/export:SystemFunction025=advapi32.SystemFunction025") // XP
#pragma comment(linker, "/export:SystemFunction026=advapi32.SystemFunction026") // XP
#pragma comment(linker, "/export:SystemFunction027=advapi32.SystemFunction027") // XP
#pragma comment(linker, "/export:SystemFunction028=advapi32.SystemFunction028") // XP
#pragma comment(linker, "/export:SystemFunction029=advapi32.SystemFunction029") // XP
#pragma comment(linker, "/export:SystemFunction030=advapi32.SystemFunction030") // XP
#pragma comment(linker, "/export:SystemFunction031=advapi32.SystemFunction031") // XP
#pragma comment(linker, "/export:SystemFunction032=advapi32.SystemFunction032") // XP
#pragma comment(linker, "/export:SystemFunction033=advapi32.SystemFunction033") // XP
#pragma comment(linker, "/export:SystemFunction034=advapi32.SystemFunction034") // XP
#pragma comment(linker, "/export:SystemFunction035=advapi32.SystemFunction035") // XP
#pragma comment(linker, "/export:SystemFunction036=advapi32.SystemFunction036") // XP
#pragma comment(linker, "/export:SystemFunction040=advapi32.SystemFunction040") // XP
#pragma comment(linker, "/export:SystemFunction041=advapi32.SystemFunction041") // XP
#pragma comment(linker, "/export:TraceEvent=advapi32.TraceEvent") // XP
#pragma comment(linker, "/export:TraceEventInstance=advapi32.TraceEventInstance") // XP
#pragma comment(linker, "/export:TraceMessage=advapi32.TraceMessage") // XP
#pragma comment(linker, "/export:TraceMessageVa=advapi32.TraceMessageVa") // XP
#pragma comment(linker, "/export:TraceQueryInformation=advapi32.TraceQueryInformation")
#pragma comment(linker, "/export:TraceSetInformation=advapi32.TraceSetInformation")
#pragma comment(linker, "/export:TreeResetNamedSecurityInfoA=advapi32.TreeResetNamedSecurityInfoA") // XP
#pragma comment(linker, "/export:TreeResetNamedSecurityInfoW=advapi32.TreeResetNamedSecurityInfoW") // XP
#pragma comment(linker, "/export:TreeSetNamedSecurityInfoA=advapi32.TreeSetNamedSecurityInfoA")
#pragma comment(linker, "/export:TreeSetNamedSecurityInfoW=advapi32.TreeSetNamedSecurityInfoW")
#pragma comment(linker, "/export:TrusteeAccessToObjectA=advapi32.TrusteeAccessToObjectA") // XP
#pragma comment(linker, "/export:TrusteeAccessToObjectW=advapi32.TrusteeAccessToObjectW") // XP
#pragma comment(linker, "/export:UninstallApplication=advapi32.UninstallApplication") // XP
#pragma comment(linker, "/export:UnlockServiceDatabase=advapi32.UnlockServiceDatabase") // XP
#pragma comment(linker, "/export:UnregisterIdleTask=advapi32.UnregisterIdleTask") // XP
#pragma comment(linker, "/export:UnregisterTraceGuids=advapi32.UnregisterTraceGuids") // XP
#pragma comment(linker, "/export:UpdateTraceA=advapi32.UpdateTraceA") // XP
#pragma comment(linker, "/export:UpdateTraceW=advapi32.UpdateTraceW") // XP
#pragma comment(linker, "/export:UsePinForEncryptedFilesA=advapi32.UsePinForEncryptedFilesA")
#pragma comment(linker, "/export:UsePinForEncryptedFilesW=advapi32.UsePinForEncryptedFilesW")
#pragma comment(linker, "/export:WaitServiceState=advapi32.WaitServiceState")
#pragma comment(linker, "/export:WmiCloseBlock=advapi32.WmiCloseBlock") // XP
#pragma comment(linker, "/export:WmiDevInstToInstanceNameA=advapi32.WmiDevInstToInstanceNameA") // XP
#pragma comment(linker, "/export:WmiDevInstToInstanceNameW=advapi32.WmiDevInstToInstanceNameW") // XP
#pragma comment(linker, "/export:WmiEnumerateGuids=advapi32.WmiEnumerateGuids") // XP
#pragma comment(linker, "/export:WmiExecuteMethodA=advapi32.WmiExecuteMethodA") // XP
#pragma comment(linker, "/export:WmiExecuteMethodW=advapi32.WmiExecuteMethodW") // XP
#pragma comment(linker, "/export:WmiFileHandleToInstanceNameA=advapi32.WmiFileHandleToInstanceNameA") // XP
#pragma comment(linker, "/export:WmiFileHandleToInstanceNameW=advapi32.WmiFileHandleToInstanceNameW") // XP
#pragma comment(linker, "/export:WmiFreeBuffer=advapi32.WmiFreeBuffer") // XP
#pragma comment(linker, "/export:WmiMofEnumerateResourcesA=advapi32.WmiMofEnumerateResourcesA") // XP
#pragma comment(linker, "/export:WmiMofEnumerateResourcesW=advapi32.WmiMofEnumerateResourcesW") // XP
#pragma comment(linker, "/export:WmiNotificationRegistrationA=advapi32.WmiNotificationRegistrationA") // XP
#pragma comment(linker, "/export:WmiNotificationRegistrationW=advapi32.WmiNotificationRegistrationW") // XP
#pragma comment(linker, "/export:WmiOpenBlock=advapi32.WmiOpenBlock") // XP
#pragma comment(linker, "/export:WmiQueryAllDataA=advapi32.WmiQueryAllDataA") // XP
#pragma comment(linker, "/export:WmiQueryAllDataMultipleA=advapi32.WmiQueryAllDataMultipleA") // XP
#pragma comment(linker, "/export:WmiQueryAllDataMultipleW=advapi32.WmiQueryAllDataMultipleW") // XP
#pragma comment(linker, "/export:WmiQueryAllDataW=advapi32.WmiQueryAllDataW") // XP
#pragma comment(linker, "/export:WmiQueryGuidInformation=advapi32.WmiQueryGuidInformation") // XP
#pragma comment(linker, "/export:WmiQuerySingleInstanceA=advapi32.WmiQuerySingleInstanceA") // XP
#pragma comment(linker, "/export:WmiQuerySingleInstanceMultipleA=advapi32.WmiQuerySingleInstanceMultipleA") // XP
#pragma comment(linker, "/export:WmiQuerySingleInstanceMultipleW=advapi32.WmiQuerySingleInstanceMultipleW") // XP
#pragma comment(linker, "/export:WmiQuerySingleInstanceW=advapi32.WmiQuerySingleInstanceW") // XP
#pragma comment(linker, "/export:WmiReceiveNotificationsA=advapi32.WmiReceiveNotificationsA") // XP
#pragma comment(linker, "/export:WmiReceiveNotificationsW=advapi32.WmiReceiveNotificationsW") // XP
#pragma comment(linker, "/export:WmiSetSingleInstanceA=advapi32.WmiSetSingleInstanceA") // XP
#pragma comment(linker, "/export:WmiSetSingleInstanceW=advapi32.WmiSetSingleInstanceW") // XP
#pragma comment(linker, "/export:WmiSetSingleItemA=advapi32.WmiSetSingleItemA") // XP
#pragma comment(linker, "/export:WmiSetSingleItemW=advapi32.WmiSetSingleItemW") // XP
#pragma comment(linker, "/export:WriteEncryptedFileRaw=advapi32.WriteEncryptedFileRaw") // XP
