#include <WinDef.h>

#pragma comment(linker, "/export:AddIPAddress=iphlpapi.AddIPAddress") // XP
#pragma comment(linker, "/export:AllocateAndGetInterfaceInfoFromStack=iphlpapi.AllocateAndGetInterfaceInfoFromStack")
#pragma comment(linker, "/export:AllocateAndGetIpAddrTableFromStack=iphlpapi.AllocateAndGetIpAddrTableFromStack") // XP
#pragma comment(linker, "/export:CancelIPChangeNotify=iphlpapi.CancelIPChangeNotify") // XP
#pragma comment(linker, "/export:CancelMibChangeNotify2=iphlpapi.CancelMibChangeNotify2")
#pragma comment(linker, "/export:CloseCompartment=iphlpapi.CloseCompartment")
#pragma comment(linker, "/export:CloseGetIPPhysicalInterfaceForDestination=iphlpapi.CloseGetIPPhysicalInterfaceForDestination")
#pragma comment(linker, "/export:ConvertCompartmentGuidToId=iphlpapi.ConvertCompartmentGuidToId")
#pragma comment(linker, "/export:ConvertCompartmentIdToGuid=iphlpapi.ConvertCompartmentIdToGuid")
#pragma comment(linker, "/export:ConvertGuidToStringA=iphlpapi.ConvertGuidToStringA")
#pragma comment(linker, "/export:ConvertGuidToStringW=iphlpapi.ConvertGuidToStringW")
#pragma comment(linker, "/export:ConvertInterfaceAliasToLuid=iphlpapi.ConvertInterfaceAliasToLuid")
#pragma comment(linker, "/export:ConvertInterfaceGuidToLuid=iphlpapi.ConvertInterfaceGuidToLuid")
#pragma comment(linker, "/export:ConvertInterfaceIndexToLuid=iphlpapi.ConvertInterfaceIndexToLuid")
#pragma comment(linker, "/export:ConvertInterfaceLuidToAlias=iphlpapi.ConvertInterfaceLuidToAlias")
#pragma comment(linker, "/export:ConvertInterfaceLuidToGuid=iphlpapi.ConvertInterfaceLuidToGuid")
#pragma comment(linker, "/export:ConvertInterfaceLuidToIndex=iphlpapi.ConvertInterfaceLuidToIndex")
#pragma comment(linker, "/export:ConvertInterfaceLuidToNameA=iphlpapi.ConvertInterfaceLuidToNameA")
#pragma comment(linker, "/export:ConvertInterfaceLuidToNameW=iphlpapi.ConvertInterfaceLuidToNameW")
#pragma comment(linker, "/export:ConvertInterfaceNameToLuidA=iphlpapi.ConvertInterfaceNameToLuidA")
#pragma comment(linker, "/export:ConvertInterfaceNameToLuidW=iphlpapi.ConvertInterfaceNameToLuidW")
#pragma comment(linker, "/export:ConvertInterfacePhysicalAddressToLuid=iphlpapi.ConvertInterfacePhysicalAddressToLuid")
#pragma comment(linker, "/export:ConvertIpv4MaskToLength=iphlpapi.ConvertIpv4MaskToLength")
#pragma comment(linker, "/export:ConvertLengthToIpv4Mask=iphlpapi.ConvertLengthToIpv4Mask")
#pragma comment(linker, "/export:ConvertRemoteInterfaceAliasToLuid=iphlpapi.ConvertRemoteInterfaceAliasToLuid")
#pragma comment(linker, "/export:ConvertRemoteInterfaceGuidToLuid=iphlpapi.ConvertRemoteInterfaceGuidToLuid")
#pragma comment(linker, "/export:ConvertRemoteInterfaceIndexToLuid=iphlpapi.ConvertRemoteInterfaceIndexToLuid")
#pragma comment(linker, "/export:ConvertRemoteInterfaceLuidToAlias=iphlpapi.ConvertRemoteInterfaceLuidToAlias")
#pragma comment(linker, "/export:ConvertRemoteInterfaceLuidToGuid=iphlpapi.ConvertRemoteInterfaceLuidToGuid")
#pragma comment(linker, "/export:ConvertRemoteInterfaceLuidToIndex=iphlpapi.ConvertRemoteInterfaceLuidToIndex")
#pragma comment(linker, "/export:ConvertStringToGuidA=iphlpapi.ConvertStringToGuidA")
#pragma comment(linker, "/export:ConvertStringToGuidW=iphlpapi.ConvertStringToGuidW")
#pragma comment(linker, "/export:ConvertStringToInterfacePhysicalAddress=iphlpapi.ConvertStringToInterfacePhysicalAddress")
#pragma comment(linker, "/export:CreateAnycastIpAddressEntry=iphlpapi.CreateAnycastIpAddressEntry")
#pragma comment(linker, "/export:CreateCompartment=iphlpapi.CreateCompartment")
#pragma comment(linker, "/export:CreateIpForwardEntry=iphlpapi.CreateIpForwardEntry") // XP
#pragma comment(linker, "/export:CreateIpForwardEntry2=iphlpapi.CreateIpForwardEntry2")
#pragma comment(linker, "/export:CreateIpNetEntry=iphlpapi.CreateIpNetEntry") // XP
#pragma comment(linker, "/export:CreateIpNetEntry2=iphlpapi.CreateIpNetEntry2")
#pragma comment(linker, "/export:CreatePersistentTcpPortReservation=iphlpapi.CreatePersistentTcpPortReservation")
#pragma comment(linker, "/export:CreatePersistentUdpPortReservation=iphlpapi.CreatePersistentUdpPortReservation")
#pragma comment(linker, "/export:CreateProxyArpEntry=iphlpapi.CreateProxyArpEntry") // XP
#pragma comment(linker, "/export:CreateSortedAddressPairs=iphlpapi.CreateSortedAddressPairs")
#pragma comment(linker, "/export:CreateUnicastIpAddressEntry=iphlpapi.CreateUnicastIpAddressEntry")
#pragma comment(linker, "/export:DeleteAnycastIpAddressEntry=iphlpapi.DeleteAnycastIpAddressEntry")
#pragma comment(linker, "/export:DeleteCompartment=iphlpapi.DeleteCompartment")
#pragma comment(linker, "/export:DeleteIPAddress=iphlpapi.DeleteIPAddress") // XP
#pragma comment(linker, "/export:DeleteIpForwardEntry=iphlpapi.DeleteIpForwardEntry") // XP
#pragma comment(linker, "/export:DeleteIpForwardEntry2=iphlpapi.DeleteIpForwardEntry2")
#pragma comment(linker, "/export:DeleteIpNetEntry=iphlpapi.DeleteIpNetEntry") // XP
#pragma comment(linker, "/export:DeleteIpNetEntry2=iphlpapi.DeleteIpNetEntry2")
#pragma comment(linker, "/export:DeletePersistentTcpPortReservation=iphlpapi.DeletePersistentTcpPortReservation")
#pragma comment(linker, "/export:DeletePersistentUdpPortReservation=iphlpapi.DeletePersistentUdpPortReservation")
#pragma comment(linker, "/export:DeleteProxyArpEntry=iphlpapi.DeleteProxyArpEntry") // XP
#pragma comment(linker, "/export:DeleteUnicastIpAddressEntry=iphlpapi.DeleteUnicastIpAddressEntry")
#pragma comment(linker, "/export:DisableMediaSense=iphlpapi.DisableMediaSense") // XP
#pragma comment(linker, "/export:EnableRouter=iphlpapi.EnableRouter") // XP
#pragma comment(linker, "/export:FlushIpNetTable=iphlpapi.FlushIpNetTable") // XP
#pragma comment(linker, "/export:FlushIpNetTable2=iphlpapi.FlushIpNetTable2")
#pragma comment(linker, "/export:FlushIpPathTable=iphlpapi.FlushIpPathTable")
#pragma comment(linker, "/export:FreeMibTable=iphlpapi.FreeMibTable")
#pragma comment(linker, "/export:GetAdapterIndex=iphlpapi.GetAdapterIndex") // XP
#pragma comment(linker, "/export:GetAdapterOrderMap=iphlpapi.GetAdapterOrderMap") // XP
#pragma comment(linker, "/export:GetAdaptersAddresses=iphlpapi.GetAdaptersAddresses") // XP
#pragma comment(linker, "/export:GetAdaptersInfo=iphlpapi.GetAdaptersInfo") // XP
#pragma comment(linker, "/export:GetAnycastIpAddressEntry=iphlpapi.GetAnycastIpAddressEntry")
#pragma comment(linker, "/export:GetAnycastIpAddressTable=iphlpapi.GetAnycastIpAddressTable")
#pragma comment(linker, "/export:GetBestInterface=iphlpapi.GetBestInterface") // XP
#pragma comment(linker, "/export:GetBestInterfaceEx=iphlpapi.GetBestInterfaceEx") // XP
#pragma comment(linker, "/export:GetBestRoute=iphlpapi.GetBestRoute") // XP
#pragma comment(linker, "/export:GetBestRoute2=iphlpapi.GetBestRoute2")
#pragma comment(linker, "/export:GetCurrentThreadCompartmentId=iphlpapi.GetCurrentThreadCompartmentId")
#pragma comment(linker, "/export:GetCurrentThreadCompartmentScope=iphlpapi.GetCurrentThreadCompartmentScope")
#pragma comment(linker, "/export:GetDefaultCompartmentId=iphlpapi.GetDefaultCompartmentId")
#pragma comment(linker, "/export:GetExtendedTcpTable=iphlpapi.GetExtendedTcpTable") // XP
#pragma comment(linker, "/export:GetExtendedUdpTable=iphlpapi.GetExtendedUdpTable") // XP
#pragma comment(linker, "/export:GetFriendlyIfIndex=iphlpapi.GetFriendlyIfIndex") // XP
#pragma comment(linker, "/export:GetIcmpStatistics=iphlpapi.GetIcmpStatistics") // XP
#pragma comment(linker, "/export:GetIcmpStatisticsEx=iphlpapi.GetIcmpStatisticsEx") // XP
#pragma comment(linker, "/export:GetIfEntry=iphlpapi.GetIfEntry") // XP
#pragma comment(linker, "/export:GetIfEntry2=iphlpapi.GetIfEntry2")
#pragma comment(linker, "/export:GetIfStackTable=iphlpapi.GetIfStackTable")
#pragma comment(linker, "/export:GetIfTable=iphlpapi.GetIfTable") // XP
#pragma comment(linker, "/export:GetIfTable2=iphlpapi.GetIfTable2")
#pragma comment(linker, "/export:GetIfTable2Ex=iphlpapi.GetIfTable2Ex")
#pragma comment(linker, "/export:GetInterfaceInfo=iphlpapi.GetInterfaceInfo") // XP
#pragma comment(linker, "/export:GetInvertedIfStackTable=iphlpapi.GetInvertedIfStackTable")
#pragma comment(linker, "/export:GetIpAddrTable=iphlpapi.GetIpAddrTable") // XP
#pragma comment(linker, "/export:GetIpErrorString=iphlpapi.GetIpErrorString") // XP
#pragma comment(linker, "/export:GetIpForwardEntry2=iphlpapi.GetIpForwardEntry2")
#pragma comment(linker, "/export:GetIpForwardTable=iphlpapi.GetIpForwardTable") // XP
#pragma comment(linker, "/export:GetIpForwardTable2=iphlpapi.GetIpForwardTable2")
#pragma comment(linker, "/export:GetIpInterfaceEntry=iphlpapi.GetIpInterfaceEntry")
#pragma comment(linker, "/export:GetIpInterfaceTable=iphlpapi.GetIpInterfaceTable")
#pragma comment(linker, "/export:GetIpNetEntry2=iphlpapi.GetIpNetEntry2")
#pragma comment(linker, "/export:GetIpNetTable=iphlpapi.GetIpNetTable") // XP
#pragma comment(linker, "/export:GetIpNetTable2=iphlpapi.GetIpNetTable2")
#pragma comment(linker, "/export:GetIpNetworkConnectionBandwidthEstimates=iphlpapi.GetIpNetworkConnectionBandwidthEstimates")
#pragma comment(linker, "/export:GetIpPathEntry=iphlpapi.GetIpPathEntry")
#pragma comment(linker, "/export:GetIpPathTable=iphlpapi.GetIpPathTable")
#pragma comment(linker, "/export:GetIpStatistics=iphlpapi.GetIpStatistics") // XP
#pragma comment(linker, "/export:GetIpStatisticsEx=iphlpapi.GetIpStatisticsEx") // XP
#pragma comment(linker, "/export:GetJobCompartmentId=iphlpapi.GetJobCompartmentId")
#pragma comment(linker, "/export:GetMulticastIpAddressEntry=iphlpapi.GetMulticastIpAddressEntry")
#pragma comment(linker, "/export:GetMulticastIpAddressTable=iphlpapi.GetMulticastIpAddressTable")
#pragma comment(linker, "/export:GetNetworkInformation=iphlpapi.GetNetworkInformation")
#pragma comment(linker, "/export:GetNetworkParams=iphlpapi.GetNetworkParams") // XP
#pragma comment(linker, "/export:GetNumberOfInterfaces=iphlpapi.GetNumberOfInterfaces") // XP
#pragma comment(linker, "/export:GetOwnerModuleFromPidAndInfo=iphlpapi.GetOwnerModuleFromPidAndInfo")
#pragma comment(linker, "/export:GetOwnerModuleFromTcp6Entry=iphlpapi.GetOwnerModuleFromTcp6Entry") // XP
#pragma comment(linker, "/export:GetOwnerModuleFromTcpEntry=iphlpapi.GetOwnerModuleFromTcpEntry") // XP
#pragma comment(linker, "/export:GetOwnerModuleFromUdp6Entry=iphlpapi.GetOwnerModuleFromUdp6Entry") // XP
#pragma comment(linker, "/export:GetOwnerModuleFromUdpEntry=iphlpapi.GetOwnerModuleFromUdpEntry") // XP
#pragma comment(linker, "/export:GetPerAdapterInfo=iphlpapi.GetPerAdapterInfo") // XP
#pragma comment(linker, "/export:GetPerTcp6ConnectionEStats=iphlpapi.GetPerTcp6ConnectionEStats")
#pragma comment(linker, "/export:GetPerTcp6ConnectionStats=iphlpapi.GetPerTcp6ConnectionStats")
#pragma comment(linker, "/export:GetPerTcpConnectionEStats=iphlpapi.GetPerTcpConnectionEStats")
#pragma comment(linker, "/export:GetPerTcpConnectionStats=iphlpapi.GetPerTcpConnectionStats")
#pragma comment(linker, "/export:GetRTTAndHopCount=iphlpapi.GetRTTAndHopCount") // XP
#pragma comment(linker, "/export:GetSessionCompartmentId=iphlpapi.GetSessionCompartmentId")
#pragma comment(linker, "/export:GetTcp6Table=iphlpapi.GetTcp6Table")
#pragma comment(linker, "/export:GetTcp6Table2=iphlpapi.GetTcp6Table2")
#pragma comment(linker, "/export:GetTcpStatistics=iphlpapi.GetTcpStatistics") // XP
#pragma comment(linker, "/export:GetTcpStatisticsEx=iphlpapi.GetTcpStatisticsEx") // XP
#pragma comment(linker, "/export:GetTcpTable=iphlpapi.GetTcpTable") // XP
#pragma comment(linker, "/export:GetTcpTable2=iphlpapi.GetTcpTable2")
#pragma comment(linker, "/export:GetTeredoPort=iphlpapi.GetTeredoPort")
#pragma comment(linker, "/export:GetUdp6Table=iphlpapi.GetUdp6Table")
#pragma comment(linker, "/export:GetUdpStatistics=iphlpapi.GetUdpStatistics") // XP
#pragma comment(linker, "/export:GetUdpStatisticsEx=iphlpapi.GetUdpStatisticsEx") // XP
#pragma comment(linker, "/export:GetUdpTable=iphlpapi.GetUdpTable") // XP
#pragma comment(linker, "/export:GetUniDirectionalAdapterInfo=iphlpapi.GetUniDirectionalAdapterInfo") // XP
#pragma comment(linker, "/export:GetUnicastIpAddressEntry=iphlpapi.GetUnicastIpAddressEntry")
#pragma comment(linker, "/export:GetUnicastIpAddressTable=iphlpapi.GetUnicastIpAddressTable")
#pragma comment(linker, "/export:GetWPAOACSupportLevel=iphlpapi.GetWPAOACSupportLevel")
#pragma comment(linker, "/export:Icmp6CreateFile=iphlpapi.Icmp6CreateFile") // XP
#pragma comment(linker, "/export:Icmp6ParseReplies=iphlpapi.Icmp6ParseReplies") // XP
#pragma comment(linker, "/export:Icmp6SendEcho2=iphlpapi.Icmp6SendEcho2") // XP
#pragma comment(linker, "/export:IcmpCloseHandle=iphlpapi.IcmpCloseHandle") // XP
#pragma comment(linker, "/export:IcmpCreateFile=iphlpapi.IcmpCreateFile") // XP
#pragma comment(linker, "/export:IcmpParseReplies=iphlpapi.IcmpParseReplies") // XP
#pragma comment(linker, "/export:IcmpSendEcho=iphlpapi.IcmpSendEcho") // XP
#pragma comment(linker, "/export:IcmpSendEcho2=iphlpapi.IcmpSendEcho2") // XP
#pragma comment(linker, "/export:IcmpSendEcho2Ex=iphlpapi.IcmpSendEcho2Ex")
#pragma comment(linker, "/export:InitializeCompartmentEntry=iphlpapi.InitializeCompartmentEntry")
#pragma comment(linker, "/export:InitializeIpForwardEntry=iphlpapi.InitializeIpForwardEntry")
#pragma comment(linker, "/export:InitializeIpInterfaceEntry=iphlpapi.InitializeIpInterfaceEntry")
#pragma comment(linker, "/export:InitializeUnicastIpAddressEntry=iphlpapi.InitializeUnicastIpAddressEntry")
#pragma comment(linker, "/export:InternalCleanupPersistentStore=iphlpapi.InternalCleanupPersistentStore")
#pragma comment(linker, "/export:InternalCreateAnycastIpAddressEntry=iphlpapi.InternalCreateAnycastIpAddressEntry")
#pragma comment(linker, "/export:InternalCreateIpForwardEntry=iphlpapi.InternalCreateIpForwardEntry") // XP
#pragma comment(linker, "/export:InternalCreateIpForwardEntry2=iphlpapi.InternalCreateIpForwardEntry2")
#pragma comment(linker, "/export:InternalCreateIpNetEntry=iphlpapi.InternalCreateIpNetEntry") // XP
#pragma comment(linker, "/export:InternalCreateIpNetEntry2=iphlpapi.InternalCreateIpNetEntry2")
#pragma comment(linker, "/export:InternalCreateUnicastIpAddressEntry=iphlpapi.InternalCreateUnicastIpAddressEntry")
#pragma comment(linker, "/export:InternalDeleteAnycastIpAddressEntry=iphlpapi.InternalDeleteAnycastIpAddressEntry")
#pragma comment(linker, "/export:InternalDeleteIpForwardEntry=iphlpapi.InternalDeleteIpForwardEntry") // XP
#pragma comment(linker, "/export:InternalDeleteIpForwardEntry2=iphlpapi.InternalDeleteIpForwardEntry2")
#pragma comment(linker, "/export:InternalDeleteIpNetEntry=iphlpapi.InternalDeleteIpNetEntry") // XP
#pragma comment(linker, "/export:InternalDeleteIpNetEntry2=iphlpapi.InternalDeleteIpNetEntry2")
#pragma comment(linker, "/export:InternalDeleteUnicastIpAddressEntry=iphlpapi.InternalDeleteUnicastIpAddressEntry")
#pragma comment(linker, "/export:InternalFindInterfaceByAddress=iphlpapi.InternalFindInterfaceByAddress")
#pragma comment(linker, "/export:InternalGetAnycastIpAddressEntry=iphlpapi.InternalGetAnycastIpAddressEntry")
#pragma comment(linker, "/export:InternalGetAnycastIpAddressTable=iphlpapi.InternalGetAnycastIpAddressTable")
#pragma comment(linker, "/export:InternalGetBoundTcp6EndpointTable=iphlpapi.InternalGetBoundTcp6EndpointTable")
#pragma comment(linker, "/export:InternalGetBoundTcpEndpointTable=iphlpapi.InternalGetBoundTcpEndpointTable")
#pragma comment(linker, "/export:InternalGetForwardIpTable2=iphlpapi.InternalGetForwardIpTable2")
#pragma comment(linker, "/export:InternalGetIPPhysicalInterfaceForDestination=iphlpapi.InternalGetIPPhysicalInterfaceForDestination")
#pragma comment(linker, "/export:InternalGetIfEntry2=iphlpapi.InternalGetIfEntry2")
#pragma comment(linker, "/export:InternalGetIfTable=iphlpapi.InternalGetIfTable") // XP
#pragma comment(linker, "/export:InternalGetIfTable2=iphlpapi.InternalGetIfTable2")
#pragma comment(linker, "/export:InternalGetIpAddrTable=iphlpapi.InternalGetIpAddrTable") // XP
#pragma comment(linker, "/export:InternalGetIpForwardEntry2=iphlpapi.InternalGetIpForwardEntry2")
#pragma comment(linker, "/export:InternalGetIpForwardTable=iphlpapi.InternalGetIpForwardTable") // XP
#pragma comment(linker, "/export:InternalGetIpInterfaceEntry=iphlpapi.InternalGetIpInterfaceEntry")
#pragma comment(linker, "/export:InternalGetIpInterfaceTable=iphlpapi.InternalGetIpInterfaceTable")
#pragma comment(linker, "/export:InternalGetIpNetEntry2=iphlpapi.InternalGetIpNetEntry2")
#pragma comment(linker, "/export:InternalGetIpNetTable=iphlpapi.InternalGetIpNetTable") // XP
#pragma comment(linker, "/export:InternalGetIpNetTable2=iphlpapi.InternalGetIpNetTable2")
#pragma comment(linker, "/export:InternalGetMulticastIpAddressEntry=iphlpapi.InternalGetMulticastIpAddressEntry")
#pragma comment(linker, "/export:InternalGetMulticastIpAddressTable=iphlpapi.InternalGetMulticastIpAddressTable")
#pragma comment(linker, "/export:InternalGetRtcSlotInformation=iphlpapi.InternalGetRtcSlotInformation")
#pragma comment(linker, "/export:InternalGetTcp6Table2=iphlpapi.InternalGetTcp6Table2")
#pragma comment(linker, "/export:InternalGetTcp6TableWithOwnerModule=iphlpapi.InternalGetTcp6TableWithOwnerModule")
#pragma comment(linker, "/export:InternalGetTcp6TableWithOwnerPid=iphlpapi.InternalGetTcp6TableWithOwnerPid")
#pragma comment(linker, "/export:InternalGetTcpTable=iphlpapi.InternalGetTcpTable") // XP
#pragma comment(linker, "/export:InternalGetTcpTable2=iphlpapi.InternalGetTcpTable2")
#pragma comment(linker, "/export:InternalGetTcpTableEx=iphlpapi.InternalGetTcpTableEx")
#pragma comment(linker, "/export:InternalGetTcpTableWithOwnerModule=iphlpapi.InternalGetTcpTableWithOwnerModule")
#pragma comment(linker, "/export:InternalGetTcpTableWithOwnerPid=iphlpapi.InternalGetTcpTableWithOwnerPid")
#pragma comment(linker, "/export:InternalGetTunnelPhysicalAdapter=iphlpapi.InternalGetTunnelPhysicalAdapter")
#pragma comment(linker, "/export:InternalGetUdp6TableWithOwnerModule=iphlpapi.InternalGetUdp6TableWithOwnerModule")
#pragma comment(linker, "/export:InternalGetUdp6TableWithOwnerPid=iphlpapi.InternalGetUdp6TableWithOwnerPid")
#pragma comment(linker, "/export:InternalGetUdpTable=iphlpapi.InternalGetUdpTable") // XP
#pragma comment(linker, "/export:InternalGetUdpTableEx=iphlpapi.InternalGetUdpTableEx")
#pragma comment(linker, "/export:InternalGetUdpTableWithOwnerModule=iphlpapi.InternalGetUdpTableWithOwnerModule")
#pragma comment(linker, "/export:InternalGetUdpTableWithOwnerPid=iphlpapi.InternalGetUdpTableWithOwnerPid")
#pragma comment(linker, "/export:InternalGetUnicastIpAddressEntry=iphlpapi.InternalGetUnicastIpAddressEntry")
#pragma comment(linker, "/export:InternalGetUnicastIpAddressTable=iphlpapi.InternalGetUnicastIpAddressTable")
#pragma comment(linker, "/export:InternalIcmpCreateFileEx=iphlpapi.InternalIcmpCreateFileEx")
#pragma comment(linker, "/export:InternalSetIfEntry=iphlpapi.InternalSetIfEntry") // XP
#pragma comment(linker, "/export:InternalSetIpForwardEntry=iphlpapi.InternalSetIpForwardEntry") // XP
#pragma comment(linker, "/export:InternalSetIpForwardEntry2=iphlpapi.InternalSetIpForwardEntry2")
#pragma comment(linker, "/export:InternalSetIpInterfaceEntry=iphlpapi.InternalSetIpInterfaceEntry")
#pragma comment(linker, "/export:InternalSetIpNetEntry=iphlpapi.InternalSetIpNetEntry") // XP
#pragma comment(linker, "/export:InternalSetIpNetEntry2=iphlpapi.InternalSetIpNetEntry2")
#pragma comment(linker, "/export:InternalSetIpStats=iphlpapi.InternalSetIpStats") // XP
#pragma comment(linker, "/export:InternalSetTcpEntry=iphlpapi.InternalSetTcpEntry") // XP
#pragma comment(linker, "/export:InternalSetTeredoPort=iphlpapi.InternalSetTeredoPort")
#pragma comment(linker, "/export:InternalSetUnicastIpAddressEntry=iphlpapi.InternalSetUnicastIpAddressEntry")
#pragma comment(linker, "/export:IpReleaseAddress=iphlpapi.IpReleaseAddress") // XP
#pragma comment(linker, "/export:IpRenewAddress=iphlpapi.IpRenewAddress") // XP
#pragma comment(linker, "/export:LookupPersistentTcpPortReservation=iphlpapi.LookupPersistentTcpPortReservation")
#pragma comment(linker, "/export:LookupPersistentUdpPortReservation=iphlpapi.LookupPersistentUdpPortReservation")
#pragma comment(linker, "/export:NTPTimeToNTFileTime=iphlpapi.NTPTimeToNTFileTime") // XP
#pragma comment(linker, "/export:NTTimeToNTPTime=iphlpapi.NTTimeToNTPTime") // XP
#pragma comment(linker, "/export:NhGetGuidFromInterfaceName=iphlpapi.NhGetGuidFromInterfaceName") // XP
#pragma comment(linker, "/export:NhGetInterfaceDescriptionFromGuid=iphlpapi.NhGetInterfaceDescriptionFromGuid")
#pragma comment(linker, "/export:NhGetInterfaceNameFromDeviceGuid=iphlpapi.NhGetInterfaceNameFromDeviceGuid") // XP
#pragma comment(linker, "/export:NhGetInterfaceNameFromGuid=iphlpapi.NhGetInterfaceNameFromGuid") // XP
#pragma comment(linker, "/export:NhpAllocateAndGetInterfaceInfoFromStack=iphlpapi.NhpAllocateAndGetInterfaceInfoFromStack") // XP
#pragma comment(linker, "/export:NotifyAddrChange=iphlpapi.NotifyAddrChange") // XP
#pragma comment(linker, "/export:NotifyCompartmentChange=iphlpapi.NotifyCompartmentChange")
#pragma comment(linker, "/export:NotifyIpInterfaceChange=iphlpapi.NotifyIpInterfaceChange")
#pragma comment(linker, "/export:NotifyRouteChange=iphlpapi.NotifyRouteChange") // XP
#pragma comment(linker, "/export:NotifyRouteChange2=iphlpapi.NotifyRouteChange2")
#pragma comment(linker, "/export:NotifyStableUnicastIpAddressTable=iphlpapi.NotifyStableUnicastIpAddressTable")
#pragma comment(linker, "/export:NotifyTeredoPortChange=iphlpapi.NotifyTeredoPortChange")
#pragma comment(linker, "/export:NotifyUnicastIpAddressChange=iphlpapi.NotifyUnicastIpAddressChange")
#pragma comment(linker, "/export:OpenCompartment=iphlpapi.OpenCompartment")
#pragma comment(linker, "/export:ParseNetworkString=iphlpapi.ParseNetworkString")
#pragma comment(linker, "/export:ResolveIpNetEntry2=iphlpapi.ResolveIpNetEntry2")
#pragma comment(linker, "/export:ResolveNeighbor=iphlpapi.ResolveNeighbor")
#pragma comment(linker, "/export:RestoreMediaSense=iphlpapi.RestoreMediaSense") // XP
#pragma comment(linker, "/export:SendARP=iphlpapi.SendARP") // XP
#pragma comment(linker, "/export:SetAdapterIpAddress=iphlpapi.SetAdapterIpAddress") // XP
#pragma comment(linker, "/export:SetCurrentThreadCompartmentId=iphlpapi.SetCurrentThreadCompartmentId")
#pragma comment(linker, "/export:SetCurrentThreadCompartmentScope=iphlpapi.SetCurrentThreadCompartmentScope")
#pragma comment(linker, "/export:SetIfEntry=iphlpapi.SetIfEntry") // XP
#pragma comment(linker, "/export:SetIpForwardEntry=iphlpapi.SetIpForwardEntry") // XP
#pragma comment(linker, "/export:SetIpForwardEntry2=iphlpapi.SetIpForwardEntry2")
#pragma comment(linker, "/export:SetIpInterfaceEntry=iphlpapi.SetIpInterfaceEntry")
#pragma comment(linker, "/export:SetIpNetEntry=iphlpapi.SetIpNetEntry") // XP
#pragma comment(linker, "/export:SetIpNetEntry2=iphlpapi.SetIpNetEntry2")
#pragma comment(linker, "/export:SetIpStatistics=iphlpapi.SetIpStatistics") // XP
#pragma comment(linker, "/export:SetIpStatisticsEx=iphlpapi.SetIpStatisticsEx")
#pragma comment(linker, "/export:SetIpTTL=iphlpapi.SetIpTTL") // XP
#pragma comment(linker, "/export:SetJobCompartmentId=iphlpapi.SetJobCompartmentId")
#pragma comment(linker, "/export:SetNetworkInformation=iphlpapi.SetNetworkInformation")
#pragma comment(linker, "/export:SetPerTcp6ConnectionEStats=iphlpapi.SetPerTcp6ConnectionEStats")
#pragma comment(linker, "/export:SetPerTcp6ConnectionStats=iphlpapi.SetPerTcp6ConnectionStats")
#pragma comment(linker, "/export:SetPerTcpConnectionEStats=iphlpapi.SetPerTcpConnectionEStats")
#pragma comment(linker, "/export:SetPerTcpConnectionStats=iphlpapi.SetPerTcpConnectionStats")
#pragma comment(linker, "/export:SetSessionCompartmentId=iphlpapi.SetSessionCompartmentId")
#pragma comment(linker, "/export:SetTcpEntry=iphlpapi.SetTcpEntry") // XP
#pragma comment(linker, "/export:SetUnicastIpAddressEntry=iphlpapi.SetUnicastIpAddressEntry")
#pragma comment(linker, "/export:UnenableRouter=iphlpapi.UnenableRouter") // XP
#pragma comment(linker, "/export:_PfAddFiltersToInterface@24=iphlpapi._PfAddFiltersToInterface@24") // XP
#pragma comment(linker, "/export:_PfAddGlobalFilterToInterface@8=iphlpapi._PfAddGlobalFilterToInterface@8") // XP
#pragma comment(linker, "/export:_PfBindInterfaceToIPAddress@12=iphlpapi._PfBindInterfaceToIPAddress@12") // XP
#pragma comment(linker, "/export:_PfBindInterfaceToIndex@16=iphlpapi._PfBindInterfaceToIndex@16") // XP
#pragma comment(linker, "/export:_PfCreateInterface@24=iphlpapi._PfCreateInterface@24") // XP
#pragma comment(linker, "/export:_PfDeleteInterface@4=iphlpapi._PfDeleteInterface@4") // XP
#pragma comment(linker, "/export:_PfDeleteLog@0=iphlpapi._PfDeleteLog@0") // XP
#pragma comment(linker, "/export:_PfGetInterfaceStatistics@16=iphlpapi._PfGetInterfaceStatistics@16") // XP
#pragma comment(linker, "/export:_PfMakeLog@4=iphlpapi._PfMakeLog@4") // XP
#pragma comment(linker, "/export:_PfRebindFilters@8=iphlpapi._PfRebindFilters@8") // XP
#pragma comment(linker, "/export:_PfRemoveFilterHandles@12=iphlpapi._PfRemoveFilterHandles@12") // XP
#pragma comment(linker, "/export:_PfRemoveFiltersFromInterface@20=iphlpapi._PfRemoveFiltersFromInterface@20") // XP
#pragma comment(linker, "/export:_PfRemoveGlobalFilterFromInterface@8=iphlpapi._PfRemoveGlobalFilterFromInterface@8") // XP
#pragma comment(linker, "/export:_PfSetLogBuffer@28=iphlpapi._PfSetLogBuffer@28") // XP
#pragma comment(linker, "/export:_PfTestPacket@20=iphlpapi._PfTestPacket@20") // XP
#pragma comment(linker, "/export:_PfUnBindInterface@4=iphlpapi._PfUnBindInterface@4") // XP
#pragma comment(linker, "/export:do_echo_rep=iphlpapi.do_echo_rep") // XP
#pragma comment(linker, "/export:do_echo_req=iphlpapi.do_echo_req") // XP
#pragma comment(linker, "/export:if_indextoname=iphlpapi.if_indextoname")
#pragma comment(linker, "/export:if_nametoindex=iphlpapi.if_nametoindex")
#pragma comment(linker, "/export:register_icmp=iphlpapi.register_icmp") // XP
