#include <WinDef.h>

#pragma comment(linker, "/export:BindMoniker=ole32.BindMoniker") // XP
#pragma comment(linker, "/export:CLIPFORMAT_UserFree=ole32.CLIPFORMAT_UserFree") // XP
#pragma comment(linker, "/export:CLIPFORMAT_UserFreeExt=ole32.CLIPFORMAT_UserFreeExt")
#pragma comment(linker, "/export:CLIPFORMAT_UserMarshal=ole32.CLIPFORMAT_UserMarshal") // XP
#pragma comment(linker, "/export:CLIPFORMAT_UserMarshalExt=ole32.CLIPFORMAT_UserMarshalExt")
#pragma comment(linker, "/export:CLIPFORMAT_UserSize=ole32.CLIPFORMAT_UserSize") // XP
#pragma comment(linker, "/export:CLIPFORMAT_UserSizeExt=ole32.CLIPFORMAT_UserSizeExt")
#pragma comment(linker, "/export:CLIPFORMAT_UserUnmarshal=ole32.CLIPFORMAT_UserUnmarshal") // XP
#pragma comment(linker, "/export:CLIPFORMAT_UserUnmarshalExt=ole32.CLIPFORMAT_UserUnmarshalExt")
#pragma comment(linker, "/export:CLSIDFromOle1Class=ole32.CLSIDFromOle1Class") // XP
#pragma comment(linker, "/export:CLSIDFromProgID=ole32.CLSIDFromProgID") // XP
#pragma comment(linker, "/export:CLSIDFromProgIDEx=ole32.CLSIDFromProgIDEx") // XP
#pragma comment(linker, "/export:CLSIDFromString=ole32.CLSIDFromString") // XP
#pragma comment(linker, "/export:CStdAsyncStubBuffer2_Connect=ole32.CStdAsyncStubBuffer2_Connect")
#pragma comment(linker, "/export:CStdAsyncStubBuffer2_Disconnect=ole32.CStdAsyncStubBuffer2_Disconnect")
#pragma comment(linker, "/export:CStdAsyncStubBuffer2_Release=ole32.CStdAsyncStubBuffer2_Release")
#pragma comment(linker, "/export:CStdAsyncStubBuffer_AddRef=ole32.CStdAsyncStubBuffer_AddRef")
#pragma comment(linker, "/export:CStdAsyncStubBuffer_Connect=ole32.CStdAsyncStubBuffer_Connect")
#pragma comment(linker, "/export:CStdAsyncStubBuffer_Disconnect=ole32.CStdAsyncStubBuffer_Disconnect")
#pragma comment(linker, "/export:CStdAsyncStubBuffer_Invoke=ole32.CStdAsyncStubBuffer_Invoke")
#pragma comment(linker, "/export:CStdAsyncStubBuffer_QueryInterface=ole32.CStdAsyncStubBuffer_QueryInterface")
#pragma comment(linker, "/export:CStdAsyncStubBuffer_Release=ole32.CStdAsyncStubBuffer_Release")
#pragma comment(linker, "/export:CStdStubBuffer2_Connect=ole32.CStdStubBuffer2_Connect")
#pragma comment(linker, "/export:CStdStubBuffer2_CountRefs=ole32.CStdStubBuffer2_CountRefs")
#pragma comment(linker, "/export:CStdStubBuffer2_Disconnect=ole32.CStdStubBuffer2_Disconnect")
#pragma comment(linker, "/export:CStdStubBuffer2_QueryInterface=ole32.CStdStubBuffer2_QueryInterface")
#pragma comment(linker, "/export:CheckInitDde=ole32.CheckInitDde")
#pragma comment(linker, "/export:CleanROTForApartment=ole32.CleanROTForApartment")
#pragma comment(linker, "/export:ClearQITableEntry=ole32.ClearQITableEntry")
#pragma comment(linker, "/export:ClipboardProcessUninitialize=ole32.ClipboardProcessUninitialize")
#pragma comment(linker, "/export:CoAddRefServerProcess=ole32.CoAddRefServerProcess") // XP
#pragma comment(linker, "/export:CoAicGetTokenForCOM=ole32.CoAicGetTokenForCOM")
#pragma comment(linker, "/export:CoAllowSetForegroundWindow=ole32.CoAllowSetForegroundWindow") // XP
#pragma comment(linker, "/export:CoAllowUnmarshalerCLSID=ole32.CoAllowUnmarshalerCLSID")
#pragma comment(linker, "/export:CoBuildVersion=ole32.CoBuildVersion") // XP
#pragma comment(linker, "/export:CoCancelCall=ole32.CoCancelCall") // XP
#pragma comment(linker, "/export:CoCheckElevationEnabled=ole32.CoCheckElevationEnabled")
#pragma comment(linker, "/export:CoCopyProxy=ole32.CoCopyProxy") // XP
#pragma comment(linker, "/export:CoCreateFreeThreadedMarshaler=ole32.CoCreateFreeThreadedMarshaler") // XP
#pragma comment(linker, "/export:CoCreateGuid=ole32.CoCreateGuid") // XP
#pragma comment(linker, "/export:CoCreateInstance=ole32.CoCreateInstance") // XP
#pragma comment(linker, "/export:CoCreateInstanceEx=ole32.CoCreateInstanceEx") // XP
#pragma comment(linker, "/export:CoCreateInstanceFromApp=ole32.CoCreateInstanceFromApp")
#pragma comment(linker, "/export:CoCreateObjectInContext=ole32.CoCreateObjectInContext") // XP
#pragma comment(linker, "/export:CoDeactivateObject=ole32.CoDeactivateObject") // XP
#pragma comment(linker, "/export:CoDecodeProxy=ole32.CoDecodeProxy")
#pragma comment(linker, "/export:CoDecrementMTAUsage=ole32.CoDecrementMTAUsage")
#pragma comment(linker, "/export:CoDisableCallCancellation=ole32.CoDisableCallCancellation") // XP
#pragma comment(linker, "/export:CoDisconnectContext=ole32.CoDisconnectContext")
#pragma comment(linker, "/export:CoDisconnectObject=ole32.CoDisconnectObject") // XP
#pragma comment(linker, "/export:CoDosDateTimeToFileTime=ole32.CoDosDateTimeToFileTime") // XP
#pragma comment(linker, "/export:CoEnableCallCancellation=ole32.CoEnableCallCancellation") // XP
#pragma comment(linker, "/export:CoFileTimeNow=ole32.CoFileTimeNow") // XP
#pragma comment(linker, "/export:CoFileTimeToDosDateTime=ole32.CoFileTimeToDosDateTime") // XP
#pragma comment(linker, "/export:CoFreeAllLibraries=ole32.CoFreeAllLibraries") // XP
#pragma comment(linker, "/export:CoFreeLibrary=ole32.CoFreeLibrary") // XP
#pragma comment(linker, "/export:CoFreeUnusedLibraries=ole32.CoFreeUnusedLibraries") // XP
#pragma comment(linker, "/export:CoFreeUnusedLibrariesEx=ole32.CoFreeUnusedLibrariesEx") // XP
#pragma comment(linker, "/export:CoGetActivationState=ole32.CoGetActivationState")
#pragma comment(linker, "/export:CoGetApartmentID=ole32.CoGetApartmentID") // XP
#pragma comment(linker, "/export:CoGetApartmentType=ole32.CoGetApartmentType")
#pragma comment(linker, "/export:CoGetCallContext=ole32.CoGetCallContext") // XP
#pragma comment(linker, "/export:CoGetCallState=ole32.CoGetCallState")
#pragma comment(linker, "/export:CoGetCallerTID=ole32.CoGetCallerTID") // XP
#pragma comment(linker, "/export:CoGetCancelObject=ole32.CoGetCancelObject") // XP
#pragma comment(linker, "/export:CoGetClassObject=ole32.CoGetClassObject") // XP
#pragma comment(linker, "/export:CoGetClassVersion=ole32.CoGetClassVersion") // XP
#pragma comment(linker, "/export:CoGetComCatalog=ole32.CoGetComCatalog") // XP
#pragma comment(linker, "/export:CoGetContextToken=ole32.CoGetContextToken") // XP
#pragma comment(linker, "/export:CoGetCurrentLogicalThreadId=ole32.CoGetCurrentLogicalThreadId") // XP
#pragma comment(linker, "/export:CoGetCurrentProcess=ole32.CoGetCurrentProcess") // XP
#pragma comment(linker, "/export:CoGetDefaultContext=ole32.CoGetDefaultContext") // XP
#pragma comment(linker, "/export:CoGetInstanceFromFile=ole32.CoGetInstanceFromFile") // XP
#pragma comment(linker, "/export:CoGetInstanceFromIStorage=ole32.CoGetInstanceFromIStorage") // XP
#pragma comment(linker, "/export:CoGetInterceptor=ole32.CoGetInterceptor") // XP
#pragma comment(linker, "/export:CoGetInterceptorForOle32=ole32.CoGetInterceptorForOle32")
#pragma comment(linker, "/export:CoGetInterceptorFromTypeInfo=ole32.CoGetInterceptorFromTypeInfo") // XP
#pragma comment(linker, "/export:CoGetInterfaceAndReleaseStream=ole32.CoGetInterfaceAndReleaseStream") // XP
#pragma comment(linker, "/export:CoGetMalloc=ole32.CoGetMalloc") // XP
#pragma comment(linker, "/export:CoGetMarshalSizeMax=ole32.CoGetMarshalSizeMax") // XP
#pragma comment(linker, "/export:CoGetModuleType=ole32.CoGetModuleType")
#pragma comment(linker, "/export:CoGetObject=ole32.CoGetObject") // XP
#pragma comment(linker, "/export:CoGetObjectContext=ole32.CoGetObjectContext") // XP
#pragma comment(linker, "/export:CoGetPSClsid=ole32.CoGetPSClsid") // XP
#pragma comment(linker, "/export:CoGetProcessIdentifier=ole32.CoGetProcessIdentifier") // XP
#pragma comment(linker, "/export:CoGetStandardMarshal=ole32.CoGetStandardMarshal") // XP
#pragma comment(linker, "/export:CoGetStdMarshalEx=ole32.CoGetStdMarshalEx") // XP
#pragma comment(linker, "/export:CoGetSystemSecurityPermissions=ole32.CoGetSystemSecurityPermissions") // XP
#pragma comment(linker, "/export:CoGetSystemWow64DirectoryW=ole32.CoGetSystemWow64DirectoryW")
#pragma comment(linker, "/export:CoGetTreatAsClass=ole32.CoGetTreatAsClass") // XP
#pragma comment(linker, "/export:CoHandlePriorityEventsFromMessagePump=ole32.CoHandlePriorityEventsFromMessagePump")
#pragma comment(linker, "/export:CoImpersonateClient=ole32.CoImpersonateClient") // XP
#pragma comment(linker, "/export:CoIncrementMTAUsage=ole32.CoIncrementMTAUsage")
#pragma comment(linker, "/export:CoInitialize=ole32.CoInitialize") // XP
#pragma comment(linker, "/export:CoInitializeEx=ole32.CoInitializeEx") // XP
#pragma comment(linker, "/export:CoInitializeSecurity=ole32.CoInitializeSecurity") // XP
#pragma comment(linker, "/export:CoInitializeWOW=ole32.CoInitializeWOW") // XP
#pragma comment(linker, "/export:CoInstall=ole32.CoInstall") // XP
#pragma comment(linker, "/export:CoInvalidateRemoteMachineBindings=ole32.CoInvalidateRemoteMachineBindings") // XP
#pragma comment(linker, "/export:CoIsHandlerConnected=ole32.CoIsHandlerConnected") // XP
#pragma comment(linker, "/export:CoIsOle1Class=ole32.CoIsOle1Class") // XP
#pragma comment(linker, "/export:CoLoadLibrary=ole32.CoLoadLibrary") // XP
#pragma comment(linker, "/export:CoLockObjectExternal=ole32.CoLockObjectExternal") // XP
#pragma comment(linker, "/export:CoMarshalHresult=ole32.CoMarshalHresult") // XP
#pragma comment(linker, "/export:CoMarshalInterThreadInterfaceInStream=ole32.CoMarshalInterThreadInterfaceInStream") // XP
#pragma comment(linker, "/export:CoMarshalInterface=ole32.CoMarshalInterface") // XP
#pragma comment(linker, "/export:CoPopServiceDomain=ole32.CoPopServiceDomain") // XP
#pragma comment(linker, "/export:CoPushServiceDomain=ole32.CoPushServiceDomain") // XP
#pragma comment(linker, "/export:CoQueryAuthenticationServices=ole32.CoQueryAuthenticationServices") // XP
#pragma comment(linker, "/export:CoQueryClientBlanket=ole32.CoQueryClientBlanket") // XP
#pragma comment(linker, "/export:CoQueryProxyBlanket=ole32.CoQueryProxyBlanket") // XP
#pragma comment(linker, "/export:CoQueryReleaseObject=ole32.CoQueryReleaseObject") // XP
#pragma comment(linker, "/export:CoReactivateObject=ole32.CoReactivateObject") // XP
#pragma comment(linker, "/export:CoRegisterActivationFilter=ole32.CoRegisterActivationFilter")
#pragma comment(linker, "/export:CoRegisterChannelHook=ole32.CoRegisterChannelHook") // XP
#pragma comment(linker, "/export:CoRegisterClassObject=ole32.CoRegisterClassObject") // XP
#pragma comment(linker, "/export:CoRegisterInitializeSpy=ole32.CoRegisterInitializeSpy") // XP
#pragma comment(linker, "/export:CoRegisterMallocSpy=ole32.CoRegisterMallocSpy") // XP
#pragma comment(linker, "/export:CoRegisterMessageFilter=ole32.CoRegisterMessageFilter") // XP
#pragma comment(linker, "/export:CoRegisterPSClsid=ole32.CoRegisterPSClsid") // XP
#pragma comment(linker, "/export:CoRegisterSurrogate=ole32.CoRegisterSurrogate") // XP
#pragma comment(linker, "/export:CoRegisterSurrogateEx=ole32.CoRegisterSurrogateEx") // XP
#pragma comment(linker, "/export:CoReleaseMarshalData=ole32.CoReleaseMarshalData") // XP
#pragma comment(linker, "/export:CoReleaseServerProcess=ole32.CoReleaseServerProcess") // XP
#pragma comment(linker, "/export:CoResumeClassObjects=ole32.CoResumeClassObjects") // XP
#pragma comment(linker, "/export:CoRetireServer=ole32.CoRetireServer") // XP
#pragma comment(linker, "/export:CoRevertToSelf=ole32.CoRevertToSelf") // XP
#pragma comment(linker, "/export:CoRevokeClassObject=ole32.CoRevokeClassObject") // XP
#pragma comment(linker, "/export:CoRevokeInitializeSpy=ole32.CoRevokeInitializeSpy") // XP
#pragma comment(linker, "/export:CoRevokeMallocSpy=ole32.CoRevokeMallocSpy") // XP
#pragma comment(linker, "/export:CoSetCancelObject=ole32.CoSetCancelObject") // XP
#pragma comment(linker, "/export:CoSetMessageDispatcher=ole32.CoSetMessageDispatcher")
#pragma comment(linker, "/export:CoSetProxyBlanket=ole32.CoSetProxyBlanket") // XP
#pragma comment(linker, "/export:CoSetState=ole32.CoSetState") // XP
#pragma comment(linker, "/export:CoSuspendClassObjects=ole32.CoSuspendClassObjects") // XP
#pragma comment(linker, "/export:CoSwitchCallContext=ole32.CoSwitchCallContext") // XP
#pragma comment(linker, "/export:CoTaskMemAlloc=ole32.CoTaskMemAlloc") // XP
#pragma comment(linker, "/export:CoTaskMemFree=ole32.CoTaskMemFree") // XP
#pragma comment(linker, "/export:CoTaskMemRealloc=ole32.CoTaskMemRealloc") // XP
#pragma comment(linker, "/export:CoTestCancel=ole32.CoTestCancel") // XP
#pragma comment(linker, "/export:CoTreatAsClass=ole32.CoTreatAsClass") // XP
#pragma comment(linker, "/export:CoUninitialize=ole32.CoUninitialize") // XP
#pragma comment(linker, "/export:CoUnloadingWOW=ole32.CoUnloadingWOW") // XP
#pragma comment(linker, "/export:CoUnmarshalHresult=ole32.CoUnmarshalHresult") // XP
#pragma comment(linker, "/export:CoUnmarshalInterface=ole32.CoUnmarshalInterface") // XP
#pragma comment(linker, "/export:CoVrfCheckThreadState=ole32.CoVrfCheckThreadState")
#pragma comment(linker, "/export:CoVrfGetThreadState=ole32.CoVrfGetThreadState")
#pragma comment(linker, "/export:CoVrfReleaseThreadState=ole32.CoVrfReleaseThreadState")
#pragma comment(linker, "/export:CoWaitForMultipleHandles=ole32.CoWaitForMultipleHandles") // XP
#pragma comment(linker, "/export:CoWaitForMultipleObjects=ole32.CoWaitForMultipleObjects")
#pragma comment(linker, "/export:ComPs_NdrDllCanUnloadNow=ole32.ComPs_NdrDllCanUnloadNow") // XP
#pragma comment(linker, "/export:ComPs_NdrDllGetClassObject=ole32.ComPs_NdrDllGetClassObject") // XP
#pragma comment(linker, "/export:ComPs_NdrDllRegisterProxy=ole32.ComPs_NdrDllRegisterProxy") // XP
#pragma comment(linker, "/export:ComPs_NdrDllUnregisterProxy=ole32.ComPs_NdrDllUnregisterProxy") // XP
#pragma comment(linker, "/export:CreateAntiMoniker=ole32.CreateAntiMoniker") // XP
#pragma comment(linker, "/export:CreateBindCtx=ole32.CreateBindCtx") // XP
#pragma comment(linker, "/export:CreateClassMoniker=ole32.CreateClassMoniker") // XP
#pragma comment(linker, "/export:CreateDataAdviseHolder=ole32.CreateDataAdviseHolder") // XP
#pragma comment(linker, "/export:CreateDataCache=ole32.CreateDataCache") // XP
#pragma comment(linker, "/export:CreateErrorInfo=ole32.CreateErrorInfo") // XP
#pragma comment(linker, "/export:CreateFileMoniker=ole32.CreateFileMoniker") // XP
#pragma comment(linker, "/export:CreateGenericComposite=ole32.CreateGenericComposite") // XP
#pragma comment(linker, "/export:CreateILockBytesOnHGlobal=ole32.CreateILockBytesOnHGlobal") // XP
#pragma comment(linker, "/export:CreateItemMoniker=ole32.CreateItemMoniker") // XP
#pragma comment(linker, "/export:CreateObjrefMoniker=ole32.CreateObjrefMoniker") // XP
#pragma comment(linker, "/export:CreateOleAdviseHolder=ole32.CreateOleAdviseHolder") // XP
#pragma comment(linker, "/export:CreatePointerMoniker=ole32.CreatePointerMoniker") // XP
#pragma comment(linker, "/export:CreateStdProgressIndicator=ole32.CreateStdProgressIndicator") // XP
#pragma comment(linker, "/export:CreateStreamOnHGlobal=ole32.CreateStreamOnHGlobal") // XP
#pragma comment(linker, "/export:DcomChannelSetHResult=ole32.DcomChannelSetHResult") // XP
#pragma comment(linker, "/export:DdeBindToObject=ole32.DdeBindToObject")
#pragma comment(linker, "/export:DeletePatternAndExtensionTables=ole32.DeletePatternAndExtensionTables")
#pragma comment(linker, "/export:DestroyRunningObjectTable=ole32.DestroyRunningObjectTable")
#pragma comment(linker, "/export:DllDebugObjectRPCHook=ole32.DllDebugObjectRPCHook") // XP
#pragma comment(linker, "/export:DllGetClassObject=ole32.DllGetClassObject") // XP
#pragma comment(linker, "/export:DllGetClassObjectWOW=ole32.DllGetClassObjectWOW") // XP
#pragma comment(linker, "/export:DllRegisterServer=ole32.DllRegisterServer") // XP
#pragma comment(linker, "/export:DoDragDrop=ole32.DoDragDrop") // XP
#pragma comment(linker, "/export:DragDropSetFDT=ole32.DragDropSetFDT")
#pragma comment(linker, "/export:EnableHookObject=ole32.EnableHookObject") // XP
#pragma comment(linker, "/export:FindExt=ole32.FindExt")
#pragma comment(linker, "/export:FmtIdToPropStgName=ole32.FmtIdToPropStgName") // XP
#pragma comment(linker, "/export:FreePropVariantArray=ole32.FreePropVariantArray") // XP
#pragma comment(linker, "/export:GetActiveObjectExt=ole32.GetActiveObjectExt")
#pragma comment(linker, "/export:GetClassFile=ole32.GetClassFile") // XP
#pragma comment(linker, "/export:GetConvertStg=ole32.GetConvertStg") // XP
#pragma comment(linker, "/export:GetDocumentBitStg=ole32.GetDocumentBitStg") // XP
#pragma comment(linker, "/export:GetErrorInfo=ole32.GetErrorInfo") // XP
#pragma comment(linker, "/export:GetHGlobalFromILockBytes=ole32.GetHGlobalFromILockBytes") // XP
#pragma comment(linker, "/export:GetHGlobalFromStream=ole32.GetHGlobalFromStream") // XP
#pragma comment(linker, "/export:GetHookInterface=ole32.GetHookInterface") // XP
#pragma comment(linker, "/export:GetObjectFromRotByPath=ole32.GetObjectFromRotByPath")
#pragma comment(linker, "/export:GetRunningObjectTable=ole32.GetRunningObjectTable") // XP
#pragma comment(linker, "/export:HACCEL_UserFree=ole32.HACCEL_UserFree") // XP
#pragma comment(linker, "/export:HACCEL_UserMarshal=ole32.HACCEL_UserMarshal") // XP
#pragma comment(linker, "/export:HACCEL_UserSize=ole32.HACCEL_UserSize") // XP
#pragma comment(linker, "/export:HACCEL_UserUnmarshal=ole32.HACCEL_UserUnmarshal") // XP
#pragma comment(linker, "/export:HBITMAP_UserFree=ole32.HBITMAP_UserFree") // XP
#pragma comment(linker, "/export:HBITMAP_UserMarshal=ole32.HBITMAP_UserMarshal") // XP
#pragma comment(linker, "/export:HBITMAP_UserSize=ole32.HBITMAP_UserSize") // XP
#pragma comment(linker, "/export:HBITMAP_UserUnmarshal=ole32.HBITMAP_UserUnmarshal") // XP
#pragma comment(linker, "/export:HBRUSH_UserFree=ole32.HBRUSH_UserFree") // XP
#pragma comment(linker, "/export:HBRUSH_UserMarshal=ole32.HBRUSH_UserMarshal") // XP
#pragma comment(linker, "/export:HBRUSH_UserSize=ole32.HBRUSH_UserSize") // XP
#pragma comment(linker, "/export:HBRUSH_UserUnmarshal=ole32.HBRUSH_UserUnmarshal") // XP
#pragma comment(linker, "/export:HDC_UserFree=ole32.HDC_UserFree") // XP
#pragma comment(linker, "/export:HDC_UserMarshal=ole32.HDC_UserMarshal") // XP
#pragma comment(linker, "/export:HDC_UserSize=ole32.HDC_UserSize") // XP
#pragma comment(linker, "/export:HDC_UserUnmarshal=ole32.HDC_UserUnmarshal") // XP
#pragma comment(linker, "/export:HENHMETAFILE_UserFree=ole32.HENHMETAFILE_UserFree") // XP
#pragma comment(linker, "/export:HENHMETAFILE_UserMarshal=ole32.HENHMETAFILE_UserMarshal") // XP
#pragma comment(linker, "/export:HENHMETAFILE_UserSize=ole32.HENHMETAFILE_UserSize") // XP
#pragma comment(linker, "/export:HENHMETAFILE_UserUnmarshal=ole32.HENHMETAFILE_UserUnmarshal") // XP
#pragma comment(linker, "/export:HGLOBAL_UserFree=ole32.HGLOBAL_UserFree") // XP
#pragma comment(linker, "/export:HGLOBAL_UserMarshal=ole32.HGLOBAL_UserMarshal") // XP
#pragma comment(linker, "/export:HGLOBAL_UserSize=ole32.HGLOBAL_UserSize") // XP
#pragma comment(linker, "/export:HGLOBAL_UserUnmarshal=ole32.HGLOBAL_UserUnmarshal") // XP
#pragma comment(linker, "/export:HICON_UserFree=ole32.HICON_UserFree") // XP
#pragma comment(linker, "/export:HICON_UserMarshal=ole32.HICON_UserMarshal") // XP
#pragma comment(linker, "/export:HICON_UserSize=ole32.HICON_UserSize") // XP
#pragma comment(linker, "/export:HICON_UserUnmarshal=ole32.HICON_UserUnmarshal") // XP
#pragma comment(linker, "/export:HMENU_UserFree=ole32.HMENU_UserFree") // XP
#pragma comment(linker, "/export:HMENU_UserMarshal=ole32.HMENU_UserMarshal") // XP
#pragma comment(linker, "/export:HMENU_UserSize=ole32.HMENU_UserSize") // XP
#pragma comment(linker, "/export:HMENU_UserUnmarshal=ole32.HMENU_UserUnmarshal") // XP
#pragma comment(linker, "/export:HMETAFILEPICT_UserFree=ole32.HMETAFILEPICT_UserFree") // XP
#pragma comment(linker, "/export:HMETAFILEPICT_UserMarshal=ole32.HMETAFILEPICT_UserMarshal") // XP
#pragma comment(linker, "/export:HMETAFILEPICT_UserSize=ole32.HMETAFILEPICT_UserSize") // XP
#pragma comment(linker, "/export:HMETAFILEPICT_UserUnmarshal=ole32.HMETAFILEPICT_UserUnmarshal") // XP
#pragma comment(linker, "/export:HMETAFILE_UserFree=ole32.HMETAFILE_UserFree") // XP
#pragma comment(linker, "/export:HMETAFILE_UserMarshal=ole32.HMETAFILE_UserMarshal") // XP
#pragma comment(linker, "/export:HMETAFILE_UserSize=ole32.HMETAFILE_UserSize") // XP
#pragma comment(linker, "/export:HMETAFILE_UserUnmarshal=ole32.HMETAFILE_UserUnmarshal") // XP
#pragma comment(linker, "/export:HMONITOR_UserFree=ole32.HMONITOR_UserFree")
#pragma comment(linker, "/export:HMONITOR_UserMarshal=ole32.HMONITOR_UserMarshal")
#pragma comment(linker, "/export:HMONITOR_UserSize=ole32.HMONITOR_UserSize")
#pragma comment(linker, "/export:HMONITOR_UserUnmarshal=ole32.HMONITOR_UserUnmarshal")
#pragma comment(linker, "/export:HPALETTE_UserFree=ole32.HPALETTE_UserFree") // XP
#pragma comment(linker, "/export:HPALETTE_UserFreeExt=ole32.HPALETTE_UserFreeExt")
#pragma comment(linker, "/export:HPALETTE_UserMarshal=ole32.HPALETTE_UserMarshal") // XP
#pragma comment(linker, "/export:HPALETTE_UserMarshalExt=ole32.HPALETTE_UserMarshalExt")
#pragma comment(linker, "/export:HPALETTE_UserSize=ole32.HPALETTE_UserSize") // XP
#pragma comment(linker, "/export:HPALETTE_UserSizeExt=ole32.HPALETTE_UserSizeExt")
#pragma comment(linker, "/export:HPALETTE_UserUnmarshal=ole32.HPALETTE_UserUnmarshal") // XP
#pragma comment(linker, "/export:HPALETTE_UserUnmarshalExt=ole32.HPALETTE_UserUnmarshalExt")
#pragma comment(linker, "/export:HRGN_UserFree=ole32.HRGN_UserFree")
#pragma comment(linker, "/export:HRGN_UserMarshal=ole32.HRGN_UserMarshal")
#pragma comment(linker, "/export:HRGN_UserSize=ole32.HRGN_UserSize")
#pragma comment(linker, "/export:HRGN_UserUnmarshal=ole32.HRGN_UserUnmarshal")
#pragma comment(linker, "/export:HWND_UserFree=ole32.HWND_UserFree") // XP
#pragma comment(linker, "/export:HWND_UserFreeExt=ole32.HWND_UserFreeExt")
#pragma comment(linker, "/export:HWND_UserMarshal=ole32.HWND_UserMarshal") // XP
#pragma comment(linker, "/export:HWND_UserMarshalExt=ole32.HWND_UserMarshalExt")
#pragma comment(linker, "/export:HWND_UserSize=ole32.HWND_UserSize") // XP
#pragma comment(linker, "/export:HWND_UserSizeExt=ole32.HWND_UserSizeExt")
#pragma comment(linker, "/export:HWND_UserUnmarshal=ole32.HWND_UserUnmarshal") // XP
#pragma comment(linker, "/export:HWND_UserUnmarshalExt=ole32.HWND_UserUnmarshalExt")
#pragma comment(linker, "/export:HkOleRegisterObject=ole32.HkOleRegisterObject") // XP
#pragma comment(linker, "/export:IIDFromString=ole32.IIDFromString") // XP
#pragma comment(linker, "/export:IsAccelerator=ole32.IsAccelerator") // XP
#pragma comment(linker, "/export:IsEqualGUID=ole32.IsEqualGUID") // XP
#pragma comment(linker, "/export:IsRoInitializeASTAAllowedInDesktop=ole32.IsRoInitializeASTAAllowedInDesktop")
#pragma comment(linker, "/export:IsValidIid=ole32.IsValidIid") // XP
#pragma comment(linker, "/export:IsValidInterface=ole32.IsValidInterface") // XP
#pragma comment(linker, "/export:IsValidPtrIn=ole32.IsValidPtrIn") // XP
#pragma comment(linker, "/export:IsValidPtrOut=ole32.IsValidPtrOut") // XP
#pragma comment(linker, "/export:MkParseDisplayName=ole32.MkParseDisplayName") // XP
#pragma comment(linker, "/export:MonikerCommonPrefixWith=ole32.MonikerCommonPrefixWith") // XP
#pragma comment(linker, "/export:MonikerLoadTypeLib=ole32.MonikerLoadTypeLib")
#pragma comment(linker, "/export:MonikerRelativePathTo=ole32.MonikerRelativePathTo") // XP
#pragma comment(linker, "/export:NdrOleInitializeExtension=ole32.NdrOleInitializeExtension")
#pragma comment(linker, "/export:NdrProxyForwardingFunction10=ole32.NdrProxyForwardingFunction10")
#pragma comment(linker, "/export:NdrProxyForwardingFunction11=ole32.NdrProxyForwardingFunction11")
#pragma comment(linker, "/export:NdrProxyForwardingFunction12=ole32.NdrProxyForwardingFunction12")
#pragma comment(linker, "/export:NdrProxyForwardingFunction13=ole32.NdrProxyForwardingFunction13")
#pragma comment(linker, "/export:NdrProxyForwardingFunction14=ole32.NdrProxyForwardingFunction14")
#pragma comment(linker, "/export:NdrProxyForwardingFunction15=ole32.NdrProxyForwardingFunction15")
#pragma comment(linker, "/export:NdrProxyForwardingFunction16=ole32.NdrProxyForwardingFunction16")
#pragma comment(linker, "/export:NdrProxyForwardingFunction17=ole32.NdrProxyForwardingFunction17")
#pragma comment(linker, "/export:NdrProxyForwardingFunction18=ole32.NdrProxyForwardingFunction18")
#pragma comment(linker, "/export:NdrProxyForwardingFunction19=ole32.NdrProxyForwardingFunction19")
#pragma comment(linker, "/export:NdrProxyForwardingFunction20=ole32.NdrProxyForwardingFunction20")
#pragma comment(linker, "/export:NdrProxyForwardingFunction21=ole32.NdrProxyForwardingFunction21")
#pragma comment(linker, "/export:NdrProxyForwardingFunction22=ole32.NdrProxyForwardingFunction22")
#pragma comment(linker, "/export:NdrProxyForwardingFunction23=ole32.NdrProxyForwardingFunction23")
#pragma comment(linker, "/export:NdrProxyForwardingFunction24=ole32.NdrProxyForwardingFunction24")
#pragma comment(linker, "/export:NdrProxyForwardingFunction25=ole32.NdrProxyForwardingFunction25")
#pragma comment(linker, "/export:NdrProxyForwardingFunction26=ole32.NdrProxyForwardingFunction26")
#pragma comment(linker, "/export:NdrProxyForwardingFunction27=ole32.NdrProxyForwardingFunction27")
#pragma comment(linker, "/export:NdrProxyForwardingFunction28=ole32.NdrProxyForwardingFunction28")
#pragma comment(linker, "/export:NdrProxyForwardingFunction29=ole32.NdrProxyForwardingFunction29")
#pragma comment(linker, "/export:NdrProxyForwardingFunction3=ole32.NdrProxyForwardingFunction3")
#pragma comment(linker, "/export:NdrProxyForwardingFunction30=ole32.NdrProxyForwardingFunction30")
#pragma comment(linker, "/export:NdrProxyForwardingFunction31=ole32.NdrProxyForwardingFunction31")
#pragma comment(linker, "/export:NdrProxyForwardingFunction32=ole32.NdrProxyForwardingFunction32")
#pragma comment(linker, "/export:NdrProxyForwardingFunction4=ole32.NdrProxyForwardingFunction4")
#pragma comment(linker, "/export:NdrProxyForwardingFunction5=ole32.NdrProxyForwardingFunction5")
#pragma comment(linker, "/export:NdrProxyForwardingFunction6=ole32.NdrProxyForwardingFunction6")
#pragma comment(linker, "/export:NdrProxyForwardingFunction7=ole32.NdrProxyForwardingFunction7")
#pragma comment(linker, "/export:NdrProxyForwardingFunction8=ole32.NdrProxyForwardingFunction8")
#pragma comment(linker, "/export:NdrProxyForwardingFunction9=ole32.NdrProxyForwardingFunction9")
#pragma comment(linker, "/export:ObjectStublessClient10=ole32.ObjectStublessClient10")
#pragma comment(linker, "/export:ObjectStublessClient11=ole32.ObjectStublessClient11")
#pragma comment(linker, "/export:ObjectStublessClient12=ole32.ObjectStublessClient12")
#pragma comment(linker, "/export:ObjectStublessClient13=ole32.ObjectStublessClient13")
#pragma comment(linker, "/export:ObjectStublessClient14=ole32.ObjectStublessClient14")
#pragma comment(linker, "/export:ObjectStublessClient15=ole32.ObjectStublessClient15")
#pragma comment(linker, "/export:ObjectStublessClient16=ole32.ObjectStublessClient16")
#pragma comment(linker, "/export:ObjectStublessClient17=ole32.ObjectStublessClient17")
#pragma comment(linker, "/export:ObjectStublessClient18=ole32.ObjectStublessClient18")
#pragma comment(linker, "/export:ObjectStublessClient19=ole32.ObjectStublessClient19")
#pragma comment(linker, "/export:ObjectStublessClient20=ole32.ObjectStublessClient20")
#pragma comment(linker, "/export:ObjectStublessClient21=ole32.ObjectStublessClient21")
#pragma comment(linker, "/export:ObjectStublessClient22=ole32.ObjectStublessClient22")
#pragma comment(linker, "/export:ObjectStublessClient23=ole32.ObjectStublessClient23")
#pragma comment(linker, "/export:ObjectStublessClient24=ole32.ObjectStublessClient24")
#pragma comment(linker, "/export:ObjectStublessClient25=ole32.ObjectStublessClient25")
#pragma comment(linker, "/export:ObjectStublessClient26=ole32.ObjectStublessClient26")
#pragma comment(linker, "/export:ObjectStublessClient27=ole32.ObjectStublessClient27")
#pragma comment(linker, "/export:ObjectStublessClient28=ole32.ObjectStublessClient28")
#pragma comment(linker, "/export:ObjectStublessClient29=ole32.ObjectStublessClient29")
#pragma comment(linker, "/export:ObjectStublessClient3=ole32.ObjectStublessClient3")
#pragma comment(linker, "/export:ObjectStublessClient30=ole32.ObjectStublessClient30")
#pragma comment(linker, "/export:ObjectStublessClient31=ole32.ObjectStublessClient31")
#pragma comment(linker, "/export:ObjectStublessClient32=ole32.ObjectStublessClient32")
#pragma comment(linker, "/export:ObjectStublessClient4=ole32.ObjectStublessClient4")
#pragma comment(linker, "/export:ObjectStublessClient5=ole32.ObjectStublessClient5")
#pragma comment(linker, "/export:ObjectStublessClient6=ole32.ObjectStublessClient6")
#pragma comment(linker, "/export:ObjectStublessClient7=ole32.ObjectStublessClient7")
#pragma comment(linker, "/export:ObjectStublessClient8=ole32.ObjectStublessClient8")
#pragma comment(linker, "/export:ObjectStublessClient9=ole32.ObjectStublessClient9")
#pragma comment(linker, "/export:Ole32DllGetClassObject=ole32.Ole32DllGetClassObject")
#pragma comment(linker, "/export:OleBuildVersion=ole32.OleBuildVersion") // XP
#pragma comment(linker, "/export:OleConvertIStorageToOLESTREAM=ole32.OleConvertIStorageToOLESTREAM") // XP
#pragma comment(linker, "/export:OleConvertIStorageToOLESTREAMEx=ole32.OleConvertIStorageToOLESTREAMEx") // XP
#pragma comment(linker, "/export:OleConvertOLESTREAMToIStorage=ole32.OleConvertOLESTREAMToIStorage") // XP
#pragma comment(linker, "/export:OleConvertOLESTREAMToIStorageEx=ole32.OleConvertOLESTREAMToIStorageEx") // XP
#pragma comment(linker, "/export:OleCreate=ole32.OleCreate") // XP
#pragma comment(linker, "/export:OleCreateDefaultHandler=ole32.OleCreateDefaultHandler") // XP
#pragma comment(linker, "/export:OleCreateEmbeddingHelper=ole32.OleCreateEmbeddingHelper") // XP
#pragma comment(linker, "/export:OleCreateEx=ole32.OleCreateEx") // XP
#pragma comment(linker, "/export:OleCreateFontIndirectExt=ole32.OleCreateFontIndirectExt")
#pragma comment(linker, "/export:OleCreateFromData=ole32.OleCreateFromData") // XP
#pragma comment(linker, "/export:OleCreateFromDataEx=ole32.OleCreateFromDataEx") // XP
#pragma comment(linker, "/export:OleCreateFromFile=ole32.OleCreateFromFile") // XP
#pragma comment(linker, "/export:OleCreateFromFileEx=ole32.OleCreateFromFileEx") // XP
#pragma comment(linker, "/export:OleCreateLink=ole32.OleCreateLink") // XP
#pragma comment(linker, "/export:OleCreateLinkEx=ole32.OleCreateLinkEx") // XP
#pragma comment(linker, "/export:OleCreateLinkFromData=ole32.OleCreateLinkFromData") // XP
#pragma comment(linker, "/export:OleCreateLinkFromDataEx=ole32.OleCreateLinkFromDataEx") // XP
#pragma comment(linker, "/export:OleCreateLinkToFile=ole32.OleCreateLinkToFile") // XP
#pragma comment(linker, "/export:OleCreateLinkToFileEx=ole32.OleCreateLinkToFileEx") // XP
#pragma comment(linker, "/export:OleCreateMenuDescriptor=ole32.OleCreateMenuDescriptor") // XP
#pragma comment(linker, "/export:OleCreatePictureIndirectExt=ole32.OleCreatePictureIndirectExt")
#pragma comment(linker, "/export:OleCreatePropertyFrameIndirectExt=ole32.OleCreatePropertyFrameIndirectExt")
#pragma comment(linker, "/export:OleCreateStaticFromData=ole32.OleCreateStaticFromData") // XP
#pragma comment(linker, "/export:OleDestroyMenuDescriptor=ole32.OleDestroyMenuDescriptor") // XP
#pragma comment(linker, "/export:OleDoAutoConvert=ole32.OleDoAutoConvert") // XP
#pragma comment(linker, "/export:OleDraw=ole32.OleDraw") // XP
#pragma comment(linker, "/export:OleDuplicateData=ole32.OleDuplicateData") // XP
#pragma comment(linker, "/export:OleFlushClipboard=ole32.OleFlushClipboard") // XP
#pragma comment(linker, "/export:OleGetAutoConvert=ole32.OleGetAutoConvert") // XP
#pragma comment(linker, "/export:OleGetClipboard=ole32.OleGetClipboard") // XP
#pragma comment(linker, "/export:OleGetClipboardWithEnterpriseInfo=ole32.OleGetClipboardWithEnterpriseInfo")
#pragma comment(linker, "/export:OleGetIconOfClass=ole32.OleGetIconOfClass") // XP
#pragma comment(linker, "/export:OleGetIconOfFile=ole32.OleGetIconOfFile") // XP
#pragma comment(linker, "/export:OleGetPackageClipboardOwner=ole32.OleGetPackageClipboardOwner")
#pragma comment(linker, "/export:OleIconToCursorExt=ole32.OleIconToCursorExt")
#pragma comment(linker, "/export:OleInitialize=ole32.OleInitialize") // XP
#pragma comment(linker, "/export:OleInitializeWOW=ole32.OleInitializeWOW") // XP
#pragma comment(linker, "/export:OleIsCurrentClipboard=ole32.OleIsCurrentClipboard") // XP
#pragma comment(linker, "/export:OleIsRunning=ole32.OleIsRunning") // XP
#pragma comment(linker, "/export:OleLoad=ole32.OleLoad") // XP
#pragma comment(linker, "/export:OleLoadFromStream=ole32.OleLoadFromStream") // XP
#pragma comment(linker, "/export:OleLoadPictureExt=ole32.OleLoadPictureExt")
#pragma comment(linker, "/export:OleLoadPictureFileExt=ole32.OleLoadPictureFileExt")
#pragma comment(linker, "/export:OleLoadPicturePathExt=ole32.OleLoadPicturePathExt")
#pragma comment(linker, "/export:OleLockRunning=ole32.OleLockRunning") // XP
#pragma comment(linker, "/export:OleMetafilePictFromIconAndLabel=ole32.OleMetafilePictFromIconAndLabel") // XP
#pragma comment(linker, "/export:OleNoteObjectVisible=ole32.OleNoteObjectVisible") // XP
#pragma comment(linker, "/export:OleQueryCreateFromData=ole32.OleQueryCreateFromData") // XP
#pragma comment(linker, "/export:OleQueryLinkFromData=ole32.OleQueryLinkFromData") // XP
#pragma comment(linker, "/export:OleRegEnumFormatEtc=ole32.OleRegEnumFormatEtc") // XP
#pragma comment(linker, "/export:OleRegEnumVerbs=ole32.OleRegEnumVerbs") // XP
#pragma comment(linker, "/export:OleRegGetMiscStatus=ole32.OleRegGetMiscStatus") // XP
#pragma comment(linker, "/export:OleRegGetUserType=ole32.OleRegGetUserType") // XP
#pragma comment(linker, "/export:OleReleaseEnumVerbCache=ole32.OleReleaseEnumVerbCache")
#pragma comment(linker, "/export:OleRun=ole32.OleRun") // XP
#pragma comment(linker, "/export:OleSave=ole32.OleSave") // XP
#pragma comment(linker, "/export:OleSavePictureFileExt=ole32.OleSavePictureFileExt")
#pragma comment(linker, "/export:OleSaveToStream=ole32.OleSaveToStream") // XP
#pragma comment(linker, "/export:OleSetAutoConvert=ole32.OleSetAutoConvert") // XP
#pragma comment(linker, "/export:OleSetClipboard=ole32.OleSetClipboard") // XP
#pragma comment(linker, "/export:OleSetContainedObject=ole32.OleSetContainedObject") // XP
#pragma comment(linker, "/export:OleSetMenuDescriptor=ole32.OleSetMenuDescriptor") // XP
#pragma comment(linker, "/export:OleTranslateAccelerator=ole32.OleTranslateAccelerator") // XP
#pragma comment(linker, "/export:OleTranslateColorExt=ole32.OleTranslateColorExt")
#pragma comment(linker, "/export:OleUninitialize=ole32.OleUninitialize") // XP
#pragma comment(linker, "/export:OpenOrCreateStream=ole32.OpenOrCreateStream") // XP
#pragma comment(linker, "/export:ProgIDFromCLSID=ole32.ProgIDFromCLSID") // XP
#pragma comment(linker, "/export:PropStgNameToFmtId=ole32.PropStgNameToFmtId") // XP
#pragma comment(linker, "/export:PropSysAllocString=ole32.PropSysAllocString") // XP
#pragma comment(linker, "/export:PropSysFreeString=ole32.PropSysFreeString") // XP
#pragma comment(linker, "/export:PropVariantChangeType=ole32.PropVariantChangeType") // XP
#pragma comment(linker, "/export:PropVariantClear=ole32.PropVariantClear") // XP
#pragma comment(linker, "/export:PropVariantCopy=ole32.PropVariantCopy") // XP
#pragma comment(linker, "/export:ReadClassStg=ole32.ReadClassStg") // XP
#pragma comment(linker, "/export:ReadClassStm=ole32.ReadClassStm") // XP
#pragma comment(linker, "/export:ReadFmtUserTypeStg=ole32.ReadFmtUserTypeStg") // XP
#pragma comment(linker, "/export:ReadOleStg=ole32.ReadOleStg") // XP
#pragma comment(linker, "/export:ReadStorageProperties=ole32.ReadStorageProperties")
#pragma comment(linker, "/export:ReadStringStream=ole32.ReadStringStream") // XP
#pragma comment(linker, "/export:RegisterActiveObjectExt=ole32.RegisterActiveObjectExt")
#pragma comment(linker, "/export:RegisterDragDrop=ole32.RegisterDragDrop") // XP
#pragma comment(linker, "/export:ReleaseStgMedium=ole32.ReleaseStgMedium") // XP
#pragma comment(linker, "/export:RevokeActiveObjectExt=ole32.RevokeActiveObjectExt")
#pragma comment(linker, "/export:RevokeDragDrop=ole32.RevokeDragDrop") // XP
#pragma comment(linker, "/export:RoGetAgileReference=ole32.RoGetAgileReference")
#pragma comment(linker, "/export:SNB_UserFree=ole32.SNB_UserFree") // XP
#pragma comment(linker, "/export:SNB_UserMarshal=ole32.SNB_UserMarshal") // XP
#pragma comment(linker, "/export:SNB_UserSize=ole32.SNB_UserSize") // XP
#pragma comment(linker, "/export:SNB_UserUnmarshal=ole32.SNB_UserUnmarshal") // XP
#pragma comment(linker, "/export:STGMEDIUM_UserFree=ole32.STGMEDIUM_UserFree") // XP
#pragma comment(linker, "/export:STGMEDIUM_UserFreeExt=ole32.STGMEDIUM_UserFreeExt")
#pragma comment(linker, "/export:STGMEDIUM_UserMarshal=ole32.STGMEDIUM_UserMarshal") // XP
#pragma comment(linker, "/export:STGMEDIUM_UserMarshalExt=ole32.STGMEDIUM_UserMarshalExt")
#pragma comment(linker, "/export:STGMEDIUM_UserSize=ole32.STGMEDIUM_UserSize") // XP
#pragma comment(linker, "/export:STGMEDIUM_UserSizeExt=ole32.STGMEDIUM_UserSizeExt")
#pragma comment(linker, "/export:STGMEDIUM_UserUnmarshal=ole32.STGMEDIUM_UserUnmarshal") // XP
#pragma comment(linker, "/export:STGMEDIUM_UserUnmarshalExt=ole32.STGMEDIUM_UserUnmarshalExt")
#pragma comment(linker, "/export:SetConvertStg=ole32.SetConvertStg") // XP
#pragma comment(linker, "/export:SetDocumentBitStg=ole32.SetDocumentBitStg") // XP
#pragma comment(linker, "/export:SetErrorInfo=ole32.SetErrorInfo") // XP
#pragma comment(linker, "/export:SetOleautModule=ole32.SetOleautModule")
#pragma comment(linker, "/export:SetWOWThunkGlobalPtr=ole32.SetWOWThunkGlobalPtr")
#pragma comment(linker, "/export:StdTypesGetClassObject=ole32.StdTypesGetClassObject")
#pragma comment(linker, "/export:StdTypesRegisterServer=ole32.StdTypesRegisterServer")
#pragma comment(linker, "/export:StgConvertPropertyToVariant=ole32.StgConvertPropertyToVariant") // XP
#pragma comment(linker, "/export:StgConvertVariantToProperty=ole32.StgConvertVariantToProperty") // XP
#pragma comment(linker, "/export:StgCreateDocfile=ole32.StgCreateDocfile") // XP
#pragma comment(linker, "/export:StgCreateDocfileOnILockBytes=ole32.StgCreateDocfileOnILockBytes") // XP
#pragma comment(linker, "/export:StgCreatePropSetStg=ole32.StgCreatePropSetStg") // XP
#pragma comment(linker, "/export:StgCreatePropStg=ole32.StgCreatePropStg") // XP
#pragma comment(linker, "/export:StgCreateStorageEx=ole32.StgCreateStorageEx") // XP
#pragma comment(linker, "/export:StgGetIFillLockBytesOnFile=ole32.StgGetIFillLockBytesOnFile") // XP
#pragma comment(linker, "/export:StgGetIFillLockBytesOnILockBytes=ole32.StgGetIFillLockBytesOnILockBytes") // XP
#pragma comment(linker, "/export:StgIsStorageFile=ole32.StgIsStorageFile") // XP
#pragma comment(linker, "/export:StgIsStorageILockBytes=ole32.StgIsStorageILockBytes") // XP
#pragma comment(linker, "/export:StgOpenAsyncDocfileOnIFillLockBytes=ole32.StgOpenAsyncDocfileOnIFillLockBytes") // XP
#pragma comment(linker, "/export:StgOpenPropStg=ole32.StgOpenPropStg") // XP
#pragma comment(linker, "/export:StgOpenStorage=ole32.StgOpenStorage") // XP
#pragma comment(linker, "/export:StgOpenStorageEx=ole32.StgOpenStorageEx") // XP
#pragma comment(linker, "/export:StgOpenStorageOnHandle=ole32.StgOpenStorageOnHandle") // XP
#pragma comment(linker, "/export:StgOpenStorageOnILockBytes=ole32.StgOpenStorageOnILockBytes") // XP
#pragma comment(linker, "/export:StgPropertyLengthAsVariant=ole32.StgPropertyLengthAsVariant") // XP
#pragma comment(linker, "/export:StgSetTimes=ole32.StgSetTimes") // XP
#pragma comment(linker, "/export:StoreQITableEntry=ole32.StoreQITableEntry")
#pragma comment(linker, "/export:StringFromCLSID=ole32.StringFromCLSID") // XP
#pragma comment(linker, "/export:StringFromGUID2=ole32.StringFromGUID2") // XP
#pragma comment(linker, "/export:StringFromIID=ole32.StringFromIID") // XP
#pragma comment(linker, "/export:UpdateDCOMSettings=ole32.UpdateDCOMSettings") // XP
#pragma comment(linker, "/export:UpdateProcessTracing=ole32.UpdateProcessTracing")
#pragma comment(linker, "/export:UtConvertDvtd16toDvtd32=ole32.UtConvertDvtd16toDvtd32") // XP
#pragma comment(linker, "/export:UtConvertDvtd32toDvtd16=ole32.UtConvertDvtd32toDvtd16") // XP
#pragma comment(linker, "/export:UtGetDvtd16Info=ole32.UtGetDvtd16Info") // XP
#pragma comment(linker, "/export:UtGetDvtd32Info=ole32.UtGetDvtd32Info") // XP
#pragma comment(linker, "/export:WdtpInterfacePointer_UserFree=ole32.WdtpInterfacePointer_UserFree") // XP
#pragma comment(linker, "/export:WdtpInterfacePointer_UserMarshal=ole32.WdtpInterfacePointer_UserMarshal") // XP
#pragma comment(linker, "/export:WdtpInterfacePointer_UserSize=ole32.WdtpInterfacePointer_UserSize") // XP
#pragma comment(linker, "/export:WdtpInterfacePointer_UserUnmarshal=ole32.WdtpInterfacePointer_UserUnmarshal") // XP
#pragma comment(linker, "/export:WriteClassStg=ole32.WriteClassStg") // XP
#pragma comment(linker, "/export:WriteClassStm=ole32.WriteClassStm") // XP
#pragma comment(linker, "/export:WriteFmtUserTypeStg=ole32.WriteFmtUserTypeStg") // XP
#pragma comment(linker, "/export:WriteOleStg=ole32.WriteOleStg") // XP
#pragma comment(linker, "/export:WriteStorageProperties=ole32.WriteStorageProperties")
#pragma comment(linker, "/export:WriteStringStream=ole32.WriteStringStream") // XP
