#include <WinDef.h>

#pragma comment(linker, "/export:AppCompat_RunDLLW=shell32.AppCompat_RunDLLW") // XP
#pragma comment(linker, "/export:AssocCreateForClasses=shell32.AssocCreateForClasses")
#pragma comment(linker, "/export:AssocGetDetailsOfPropKey=shell32.AssocGetDetailsOfPropKey")
#pragma comment(linker, "/export:CDefFolderMenu_Create2=shell32.CDefFolderMenu_Create2") // XP
#pragma comment(linker, "/export:CIDLData_CreateFromIDArray=shell32.CIDLData_CreateFromIDArray")
#pragma comment(linker, "/export:CStorageItem_GetValidatedStorageItemObject=shell32.CStorageItem_GetValidatedStorageItemObject")
#pragma comment(linker, "/export:CheckEscapesW=shell32.CheckEscapesW") // XP
#pragma comment(linker, "/export:CommandLineToArgvW=shell32.CommandLineToArgvW") // XP
#pragma comment(linker, "/export:Control_RunDLL=shell32.Control_RunDLL") // XP
#pragma comment(linker, "/export:Control_RunDLLA=shell32.Control_RunDLLA") // XP
#pragma comment(linker, "/export:Control_RunDLLAsUserW=shell32.Control_RunDLLAsUserW") // XP
#pragma comment(linker, "/export:Control_RunDLLW=shell32.Control_RunDLLW") // XP
#pragma comment(linker, "/export:CreateStorageItemFromPath_FullTrustCaller=shell32.CreateStorageItemFromPath_FullTrustCaller")
#pragma comment(linker, "/export:CreateStorageItemFromPath_FullTrustCaller_ForPackage=shell32.CreateStorageItemFromPath_FullTrustCaller_ForPackage")
#pragma comment(linker, "/export:CreateStorageItemFromPath_PartialTrustCaller=shell32.CreateStorageItemFromPath_PartialTrustCaller")
#pragma comment(linker, "/export:CreateStorageItemFromShellItem_FullTrustCaller=shell32.CreateStorageItemFromShellItem_FullTrustCaller")
#pragma comment(linker, "/export:CreateStorageItemFromShellItem_FullTrustCaller_ForPackage=shell32.CreateStorageItemFromShellItem_FullTrustCaller_ForPackage")
#pragma comment(linker, "/export:CreateStorageItemFromShellItem_FullTrustCaller_ForPackage_WithProcessHandle=shell32.CreateStorageItemFromShellItem_FullTrustCaller_ForPackage_WithProcessHandle")
#pragma comment(linker, "/export:CreateStorageItemFromShellItem_FullTrustCaller_UseImplicitFlagsAndPackage=shell32.CreateStorageItemFromShellItem_FullTrustCaller_UseImplicitFlagsAndPackage")
#pragma comment(linker, "/export:DAD_AutoScroll=shell32.DAD_AutoScroll") // XP
#pragma comment(linker, "/export:DAD_DragEnterEx=shell32.DAD_DragEnterEx") // XP
#pragma comment(linker, "/export:DAD_DragEnterEx2=shell32.DAD_DragEnterEx2") // XP
#pragma comment(linker, "/export:DAD_DragLeave=shell32.DAD_DragLeave") // XP
#pragma comment(linker, "/export:DAD_DragMove=shell32.DAD_DragMove") // XP
#pragma comment(linker, "/export:DAD_SetDragImage=shell32.DAD_SetDragImage") // XP
#pragma comment(linker, "/export:DAD_ShowDragImage=shell32.DAD_ShowDragImage") // XP
#pragma comment(linker, "/export:DllCanUnloadNow=shell32.DllCanUnloadNow") // XP
#pragma comment(linker, "/export:DllGetActivationFactory=shell32.DllGetActivationFactory")
#pragma comment(linker, "/export:DllGetClassObject=shell32.DllGetClassObject") // XP
#pragma comment(linker, "/export:DllGetVersion=shell32.DllGetVersion") // XP
#pragma comment(linker, "/export:DllInstall=shell32.DllInstall") // XP
#pragma comment(linker, "/export:DllRegisterServer=shell32.DllRegisterServer") // XP
#pragma comment(linker, "/export:DllUnregisterServer=shell32.DllUnregisterServer") // XP
#pragma comment(linker, "/export:DoEnvironmentSubstA=shell32.DoEnvironmentSubstA") // XP
#pragma comment(linker, "/export:DoEnvironmentSubstW=shell32.DoEnvironmentSubstW") // XP
#pragma comment(linker, "/export:DragAcceptFiles=shell32.DragAcceptFiles") // XP
#pragma comment(linker, "/export:DragFinish=shell32.DragFinish") // XP
#pragma comment(linker, "/export:DragQueryFile=shell32.DragQueryFile") // XP
#pragma comment(linker, "/export:DragQueryFileA=shell32.DragQueryFileA") // XP
#pragma comment(linker, "/export:DragQueryFileAorW=shell32.DragQueryFileAorW") // XP
#pragma comment(linker, "/export:DragQueryFileW=shell32.DragQueryFileW") // XP
#pragma comment(linker, "/export:DragQueryPoint=shell32.DragQueryPoint") // XP
#pragma comment(linker, "/export:DriveType=shell32.DriveType") // XP
#pragma comment(linker, "/export:DuplicateIcon=shell32.DuplicateIcon") // XP
#pragma comment(linker, "/export:ExtractAssociatedIconA=shell32.ExtractAssociatedIconA") // XP
#pragma comment(linker, "/export:ExtractAssociatedIconExA=shell32.ExtractAssociatedIconExA") // XP
#pragma comment(linker, "/export:ExtractAssociatedIconExW=shell32.ExtractAssociatedIconExW") // XP
#pragma comment(linker, "/export:ExtractAssociatedIconW=shell32.ExtractAssociatedIconW") // XP
#pragma comment(linker, "/export:ExtractIconA=shell32.ExtractIconA") // XP
#pragma comment(linker, "/export:ExtractIconEx=shell32.ExtractIconEx") // XP
#pragma comment(linker, "/export:ExtractIconExA=shell32.ExtractIconExA") // XP
#pragma comment(linker, "/export:ExtractIconExW=shell32.ExtractIconExW") // XP
#pragma comment(linker, "/export:ExtractIconW=shell32.ExtractIconW") // XP
#pragma comment(linker, "/export:FindExecutableA=shell32.FindExecutableA") // XP
#pragma comment(linker, "/export:FindExecutableW=shell32.FindExecutableW") // XP
#pragma comment(linker, "/export:FreeIconList=shell32.FreeIconList") // XP
#pragma comment(linker, "/export:GetCurrentProcessExplicitAppUserModelID=shell32.GetCurrentProcessExplicitAppUserModelID")
#pragma comment(linker, "/export:GetFileNameFromBrowse=shell32.GetFileNameFromBrowse") // XP
#pragma comment(linker, "/export:GetSystemPersistedStorageItemList=shell32.GetSystemPersistedStorageItemList")
#pragma comment(linker, "/export:ILAppendID=shell32.ILAppendID") // XP
#pragma comment(linker, "/export:ILClone=shell32.ILClone") // XP
#pragma comment(linker, "/export:ILCloneFirst=shell32.ILCloneFirst") // XP
#pragma comment(linker, "/export:ILCombine=shell32.ILCombine") // XP
#pragma comment(linker, "/export:ILCreateFromPath=shell32.ILCreateFromPath") // XP
#pragma comment(linker, "/export:ILCreateFromPathA=shell32.ILCreateFromPathA") // XP
#pragma comment(linker, "/export:ILCreateFromPathW=shell32.ILCreateFromPathW") // XP
#pragma comment(linker, "/export:ILFindChild=shell32.ILFindChild") // XP
#pragma comment(linker, "/export:ILFindLastID=shell32.ILFindLastID") // XP
#pragma comment(linker, "/export:ILFree=shell32.ILFree") // XP
#pragma comment(linker, "/export:ILGetNext=shell32.ILGetNext") // XP
#pragma comment(linker, "/export:ILGetSize=shell32.ILGetSize") // XP
#pragma comment(linker, "/export:ILIsEqual=shell32.ILIsEqual") // XP
#pragma comment(linker, "/export:ILIsParent=shell32.ILIsParent") // XP
#pragma comment(linker, "/export:ILLoadFromStreamEx=shell32.ILLoadFromStreamEx")
#pragma comment(linker, "/export:ILRemoveLastID=shell32.ILRemoveLastID") // XP
#pragma comment(linker, "/export:ILSaveToStream=shell32.ILSaveToStream") // XP
#pragma comment(linker, "/export:InitNetworkAddressControl=shell32.InitNetworkAddressControl")
#pragma comment(linker, "/export:InternalExtractIconListA=shell32.InternalExtractIconListA") // XP
#pragma comment(linker, "/export:InternalExtractIconListW=shell32.InternalExtractIconListW") // XP
#pragma comment(linker, "/export:IsDesktopExplorerProcess=shell32.IsDesktopExplorerProcess")
#pragma comment(linker, "/export:IsLFNDrive=shell32.IsLFNDrive") // XP
#pragma comment(linker, "/export:IsLFNDriveA=shell32.IsLFNDriveA") // XP
#pragma comment(linker, "/export:IsLFNDriveW=shell32.IsLFNDriveW") // XP
#pragma comment(linker, "/export:IsNetDrive=shell32.IsNetDrive") // XP
#pragma comment(linker, "/export:IsProcessAnExplorer=shell32.IsProcessAnExplorer")
#pragma comment(linker, "/export:IsUserAnAdmin=shell32.IsUserAnAdmin") // XP
#pragma comment(linker, "/export:LaunchMSHelp_RunDLLW=shell32.LaunchMSHelp_RunDLLW")
#pragma comment(linker, "/export:OpenAs_RunDLL=shell32.OpenAs_RunDLL") // XP
#pragma comment(linker, "/export:OpenAs_RunDLLA=shell32.OpenAs_RunDLLA") // XP
#pragma comment(linker, "/export:OpenAs_RunDLLW=shell32.OpenAs_RunDLLW") // XP
#pragma comment(linker, "/export:OpenRegStream=shell32.OpenRegStream") // XP
#pragma comment(linker, "/export:Options_RunDLL=shell32.Options_RunDLL") // XP
#pragma comment(linker, "/export:Options_RunDLLA=shell32.Options_RunDLLA") // XP
#pragma comment(linker, "/export:Options_RunDLLW=shell32.Options_RunDLLW") // XP
#pragma comment(linker, "/export:PathCleanupSpec=shell32.PathCleanupSpec") // XP
#pragma comment(linker, "/export:PathGetShortPath=shell32.PathGetShortPath") // XP
#pragma comment(linker, "/export:PathIsExe=shell32.PathIsExe") // XP
#pragma comment(linker, "/export:PathIsSlowA=shell32.PathIsSlowA") // XP
#pragma comment(linker, "/export:PathIsSlowW=shell32.PathIsSlowW") // XP
#pragma comment(linker, "/export:PathMakeUniqueName=shell32.PathMakeUniqueName") // XP
#pragma comment(linker, "/export:PathQualify=shell32.PathQualify") // XP
#pragma comment(linker, "/export:PathResolve=shell32.PathResolve") // XP
#pragma comment(linker, "/export:PathYetAnotherMakeUniqueName=shell32.PathYetAnotherMakeUniqueName") // XP
#pragma comment(linker, "/export:PickIconDlg=shell32.PickIconDlg") // XP
#pragma comment(linker, "/export:PifMgr_CloseProperties=shell32.PifMgr_CloseProperties") // XP
#pragma comment(linker, "/export:PifMgr_GetProperties=shell32.PifMgr_GetProperties") // XP
#pragma comment(linker, "/export:PifMgr_OpenProperties=shell32.PifMgr_OpenProperties") // XP
#pragma comment(linker, "/export:PifMgr_SetProperties=shell32.PifMgr_SetProperties") // XP
#pragma comment(linker, "/export:PrepareDiscForBurnRunDllW=shell32.PrepareDiscForBurnRunDllW")
#pragma comment(linker, "/export:PrintersGetCommand_RunDLL=shell32.PrintersGetCommand_RunDLL") // XP
#pragma comment(linker, "/export:PrintersGetCommand_RunDLLA=shell32.PrintersGetCommand_RunDLLA") // XP
#pragma comment(linker, "/export:PrintersGetCommand_RunDLLW=shell32.PrintersGetCommand_RunDLLW") // XP
#pragma comment(linker, "/export:ReadCabinetState=shell32.ReadCabinetState") // XP
#pragma comment(linker, "/export:RealDriveType=shell32.RealDriveType") // XP
#pragma comment(linker, "/export:RealShellExecuteA=shell32.RealShellExecuteA") // XP
#pragma comment(linker, "/export:RealShellExecuteExA=shell32.RealShellExecuteExA") // XP
#pragma comment(linker, "/export:RealShellExecuteExW=shell32.RealShellExecuteExW") // XP
#pragma comment(linker, "/export:RealShellExecuteW=shell32.RealShellExecuteW") // XP
#pragma comment(linker, "/export:RegenerateUserEnvironment=shell32.RegenerateUserEnvironment") // XP
#pragma comment(linker, "/export:RestartDialog=shell32.RestartDialog") // XP
#pragma comment(linker, "/export:RestartDialogEx=shell32.RestartDialogEx") // XP
#pragma comment(linker, "/export:RunAsNewUser_RunDLLW=shell32.RunAsNewUser_RunDLLW")
#pragma comment(linker, "/export:SHAddDefaultPropertiesByExt=shell32.SHAddDefaultPropertiesByExt")
#pragma comment(linker, "/export:SHAddFromPropSheetExtArray=shell32.SHAddFromPropSheetExtArray") // XP
#pragma comment(linker, "/export:SHAddToRecentDocs=shell32.SHAddToRecentDocs") // XP
#pragma comment(linker, "/export:SHAlloc=shell32.SHAlloc") // XP
#pragma comment(linker, "/export:SHAppBarMessage=shell32.SHAppBarMessage") // XP
#pragma comment(linker, "/export:SHAssocEnumHandlers=shell32.SHAssocEnumHandlers")
#pragma comment(linker, "/export:SHAssocEnumHandlersForProtocolByApplication=shell32.SHAssocEnumHandlersForProtocolByApplication")
#pragma comment(linker, "/export:SHBindToFolderIDListParent=shell32.SHBindToFolderIDListParent")
#pragma comment(linker, "/export:SHBindToFolderIDListParentEx=shell32.SHBindToFolderIDListParentEx")
#pragma comment(linker, "/export:SHBindToObject=shell32.SHBindToObject")
#pragma comment(linker, "/export:SHBindToParent=shell32.SHBindToParent") // XP
#pragma comment(linker, "/export:SHBrowseForFolder=shell32.SHBrowseForFolder") // XP
#pragma comment(linker, "/export:SHBrowseForFolderA=shell32.SHBrowseForFolderA") // XP
#pragma comment(linker, "/export:SHBrowseForFolderW=shell32.SHBrowseForFolderW") // XP
#pragma comment(linker, "/export:SHCLSIDFromString=shell32.SHCLSIDFromString") // XP
#pragma comment(linker, "/export:SHChangeNotification_Lock=shell32.SHChangeNotification_Lock") // XP
#pragma comment(linker, "/export:SHChangeNotification_Unlock=shell32.SHChangeNotification_Unlock") // XP
#pragma comment(linker, "/export:SHChangeNotify=shell32.SHChangeNotify") // XP
#pragma comment(linker, "/export:SHChangeNotifyDeregister=shell32.SHChangeNotifyDeregister") // XP
#pragma comment(linker, "/export:SHChangeNotifyRegister=shell32.SHChangeNotifyRegister") // XP
#pragma comment(linker, "/export:SHChangeNotifyRegisterThread=shell32.SHChangeNotifyRegisterThread")
#pragma comment(linker, "/export:SHChangeNotifySuspendResume=shell32.SHChangeNotifySuspendResume") // XP
#pragma comment(linker, "/export:SHCloneSpecialIDList=shell32.SHCloneSpecialIDList") // XP
#pragma comment(linker, "/export:SHCoCreateInstance=shell32.SHCoCreateInstance") // XP
#pragma comment(linker, "/export:SHCoCreateInstanceWorker=shell32.SHCoCreateInstanceWorker")
#pragma comment(linker, "/export:SHCreateAssociationRegistration=shell32.SHCreateAssociationRegistration")
#pragma comment(linker, "/export:SHCreateCategoryEnum=shell32.SHCreateCategoryEnum")
#pragma comment(linker, "/export:SHCreateDataObject=shell32.SHCreateDataObject")
#pragma comment(linker, "/export:SHCreateDefaultContextMenu=shell32.SHCreateDefaultContextMenu")
#pragma comment(linker, "/export:SHCreateDefaultExtractIcon=shell32.SHCreateDefaultExtractIcon")
#pragma comment(linker, "/export:SHCreateDefaultPropertiesOp=shell32.SHCreateDefaultPropertiesOp")
#pragma comment(linker, "/export:SHCreateDirectory=shell32.SHCreateDirectory") // XP
#pragma comment(linker, "/export:SHCreateDirectoryExA=shell32.SHCreateDirectoryExA") // XP
#pragma comment(linker, "/export:SHCreateDirectoryExW=shell32.SHCreateDirectoryExW") // XP
#pragma comment(linker, "/export:SHCreateDrvExtIcon=shell32.SHCreateDrvExtIcon")
#pragma comment(linker, "/export:SHCreateFileExtractIconW=shell32.SHCreateFileExtractIconW") // XP
#pragma comment(linker, "/export:SHCreateItemFromIDList=shell32.SHCreateItemFromIDList")
#pragma comment(linker, "/export:SHCreateItemFromParsingName=shell32.SHCreateItemFromParsingName")
#pragma comment(linker, "/export:SHCreateItemFromRelativeName=shell32.SHCreateItemFromRelativeName")
#pragma comment(linker, "/export:SHCreateItemInKnownFolder=shell32.SHCreateItemInKnownFolder")
#pragma comment(linker, "/export:SHCreateItemWithParent=shell32.SHCreateItemWithParent")
#pragma comment(linker, "/export:SHCreateLocalServerRunDll=shell32.SHCreateLocalServerRunDll") // XP
#pragma comment(linker, "/export:SHCreateProcessAsUserW=shell32.SHCreateProcessAsUserW") // XP
#pragma comment(linker, "/export:SHCreatePropSheetExtArray=shell32.SHCreatePropSheetExtArray") // XP
#pragma comment(linker, "/export:SHCreateQueryCancelAutoPlayMoniker=shell32.SHCreateQueryCancelAutoPlayMoniker") // XP
#pragma comment(linker, "/export:SHCreateShellFolderView=shell32.SHCreateShellFolderView") // XP
#pragma comment(linker, "/export:SHCreateShellFolderViewEx=shell32.SHCreateShellFolderViewEx") // XP
#pragma comment(linker, "/export:SHCreateShellItem=shell32.SHCreateShellItem") // XP
#pragma comment(linker, "/export:SHCreateShellItemArray=shell32.SHCreateShellItemArray")
#pragma comment(linker, "/export:SHCreateShellItemArrayFromDataObject=shell32.SHCreateShellItemArrayFromDataObject")
#pragma comment(linker, "/export:SHCreateShellItemArrayFromIDLists=shell32.SHCreateShellItemArrayFromIDLists")
#pragma comment(linker, "/export:SHCreateShellItemArrayFromShellItem=shell32.SHCreateShellItemArrayFromShellItem")
#pragma comment(linker, "/export:SHCreateStdEnumFmtEtc=shell32.SHCreateStdEnumFmtEtc") // XP
#pragma comment(linker, "/export:SHDefExtractIconA=shell32.SHDefExtractIconA") // XP
#pragma comment(linker, "/export:SHDefExtractIconW=shell32.SHDefExtractIconW") // XP
#pragma comment(linker, "/export:SHDestroyPropSheetExtArray=shell32.SHDestroyPropSheetExtArray") // XP
#pragma comment(linker, "/export:SHDoDragDrop=shell32.SHDoDragDrop") // XP
#pragma comment(linker, "/export:SHELL32_AddToBackIconTable=shell32.SHELL32_AddToBackIconTable")
#pragma comment(linker, "/export:SHELL32_AddToFrontIconTable=shell32.SHELL32_AddToFrontIconTable")
#pragma comment(linker, "/export:SHELL32_AreAllItemsAvailable=shell32.SHELL32_AreAllItemsAvailable")
#pragma comment(linker, "/export:SHELL32_BindToFilePlaceholderHandler=shell32.SHELL32_BindToFilePlaceholderHandler")
#pragma comment(linker, "/export:SHELL32_CCommonPlacesFolder_CreateInstance=shell32.SHELL32_CCommonPlacesFolder_CreateInstance")
#pragma comment(linker, "/export:SHELL32_CDBurn_CloseSession=shell32.SHELL32_CDBurn_CloseSession")
#pragma comment(linker, "/export:SHELL32_CDBurn_DriveSupportedForDataBurn=shell32.SHELL32_CDBurn_DriveSupportedForDataBurn")
#pragma comment(linker, "/export:SHELL32_CDBurn_Erase=shell32.SHELL32_CDBurn_Erase")
#pragma comment(linker, "/export:SHELL32_CDBurn_GetCDInfo=shell32.SHELL32_CDBurn_GetCDInfo")
#pragma comment(linker, "/export:SHELL32_CDBurn_GetLiveFSDiscInfo=shell32.SHELL32_CDBurn_GetLiveFSDiscInfo")
#pragma comment(linker, "/export:SHELL32_CDBurn_GetStagingPathOrNormalPath=shell32.SHELL32_CDBurn_GetStagingPathOrNormalPath")
#pragma comment(linker, "/export:SHELL32_CDBurn_GetTaskInfo=shell32.SHELL32_CDBurn_GetTaskInfo")
#pragma comment(linker, "/export:SHELL32_CDBurn_IsBlankDisc=shell32.SHELL32_CDBurn_IsBlankDisc")
#pragma comment(linker, "/export:SHELL32_CDBurn_IsBlankDisc2=shell32.SHELL32_CDBurn_IsBlankDisc2")
#pragma comment(linker, "/export:SHELL32_CDBurn_IsLiveFS=shell32.SHELL32_CDBurn_IsLiveFS")
#pragma comment(linker, "/export:SHELL32_CDBurn_OnDeviceChange=shell32.SHELL32_CDBurn_OnDeviceChange")
#pragma comment(linker, "/export:SHELL32_CDBurn_OnEject=shell32.SHELL32_CDBurn_OnEject")
#pragma comment(linker, "/export:SHELL32_CDBurn_OnMediaChange=shell32.SHELL32_CDBurn_OnMediaChange")
#pragma comment(linker, "/export:SHELL32_CDefFolderMenu_Create2=shell32.SHELL32_CDefFolderMenu_Create2")
#pragma comment(linker, "/export:SHELL32_CDefFolderMenu_Create2Ex=shell32.SHELL32_CDefFolderMenu_Create2Ex")
#pragma comment(linker, "/export:SHELL32_CDefFolderMenu_MergeMenu=shell32.SHELL32_CDefFolderMenu_MergeMenu")
#pragma comment(linker, "/export:SHELL32_CDrivesContextMenu_Create=shell32.SHELL32_CDrivesContextMenu_Create")
#pragma comment(linker, "/export:SHELL32_CDrivesDropTarget_Create=shell32.SHELL32_CDrivesDropTarget_Create")
#pragma comment(linker, "/export:SHELL32_CDrives_CreateSFVCB=shell32.SHELL32_CDrives_CreateSFVCB")
#pragma comment(linker, "/export:SHELL32_CFSDropTarget_CreateInstance=shell32.SHELL32_CFSDropTarget_CreateInstance")
#pragma comment(linker, "/export:SHELL32_CFSFolderCallback_Create=shell32.SHELL32_CFSFolderCallback_Create")
#pragma comment(linker, "/export:SHELL32_CFillPropertiesTask_CreateInstance=shell32.SHELL32_CFillPropertiesTask_CreateInstance")
#pragma comment(linker, "/export:SHELL32_CLibraryDropTarget_CreateInstance=shell32.SHELL32_CLibraryDropTarget_CreateInstance")
#pragma comment(linker, "/export:SHELL32_CLocationContextMenu_Create=shell32.SHELL32_CLocationContextMenu_Create")
#pragma comment(linker, "/export:SHELL32_CLocationFolderUI_CreateInstance=shell32.SHELL32_CLocationFolderUI_CreateInstance")
#pragma comment(linker, "/export:SHELL32_CMountPoint_DoAutorun=shell32.SHELL32_CMountPoint_DoAutorun")
#pragma comment(linker, "/export:SHELL32_CMountPoint_DoAutorunPrompt=shell32.SHELL32_CMountPoint_DoAutorunPrompt")
#pragma comment(linker, "/export:SHELL32_CMountPoint_IsAutoRunDriveAndEnabledByPolicy=shell32.SHELL32_CMountPoint_IsAutoRunDriveAndEnabledByPolicy")
#pragma comment(linker, "/export:SHELL32_CMountPoint_ProcessAutoRunFile=shell32.SHELL32_CMountPoint_ProcessAutoRunFile")
#pragma comment(linker, "/export:SHELL32_CMountPoint_WantAutorunUI=shell32.SHELL32_CMountPoint_WantAutorunUI")
#pragma comment(linker, "/export:SHELL32_CMountPoint_WantAutorunUIGetReady=shell32.SHELL32_CMountPoint_WantAutorunUIGetReady")
#pragma comment(linker, "/export:SHELL32_CPL_CategoryIdArrayFromVariant=shell32.SHELL32_CPL_CategoryIdArrayFromVariant")
#pragma comment(linker, "/export:SHELL32_CPL_IsLegacyCanonicalNameListedUnderKey=shell32.SHELL32_CPL_IsLegacyCanonicalNameListedUnderKey")
#pragma comment(linker, "/export:SHELL32_CPL_ModifyWowDisplayName=shell32.SHELL32_CPL_ModifyWowDisplayName")
#pragma comment(linker, "/export:SHELL32_CRecentDocsContextMenu_CreateInstance=shell32.SHELL32_CRecentDocsContextMenu_CreateInstance")
#pragma comment(linker, "/export:SHELL32_CSyncRootManager_CreateInstance=shell32.SHELL32_CSyncRootManager_CreateInstance")
#pragma comment(linker, "/export:SHELL32_CTransferConfirmation_CreateInstance=shell32.SHELL32_CTransferConfirmation_CreateInstance")
#pragma comment(linker, "/export:SHELL32_CallFileCopyHooks=shell32.SHELL32_CallFileCopyHooks")
#pragma comment(linker, "/export:SHELL32_CanDisplayWin8CopyDialog=shell32.SHELL32_CanDisplayWin8CopyDialog")
#pragma comment(linker, "/export:SHELL32_CloseAutoplayPrompt=shell32.SHELL32_CloseAutoplayPrompt")
#pragma comment(linker, "/export:SHELL32_CommandLineFromMsiDescriptor=shell32.SHELL32_CommandLineFromMsiDescriptor")
#pragma comment(linker, "/export:SHELL32_CopyExtrinsicPropertyStore=shell32.SHELL32_CopyExtrinsicPropertyStore")
#pragma comment(linker, "/export:SHELL32_CopyFilePlaceholderToNewFile=shell32.SHELL32_CopyFilePlaceholderToNewFile")
#pragma comment(linker, "/export:SHELL32_CopySecondaryTiles=shell32.SHELL32_CopySecondaryTiles")
#pragma comment(linker, "/export:SHELL32_CreateAlternateStreamFileName=shell32.SHELL32_CreateAlternateStreamFileName")
#pragma comment(linker, "/export:SHELL32_CreateConfirmationInterrupt=shell32.SHELL32_CreateConfirmationInterrupt")
#pragma comment(linker, "/export:SHELL32_CreateConflictInterrupt=shell32.SHELL32_CreateConflictInterrupt")
#pragma comment(linker, "/export:SHELL32_CreateDefaultOperationDataProvider=shell32.SHELL32_CreateDefaultOperationDataProvider")
#pragma comment(linker, "/export:SHELL32_CreateExtrinsicPropertyStore=shell32.SHELL32_CreateExtrinsicPropertyStore")
#pragma comment(linker, "/export:SHELL32_CreateFileFolderContextMenu=shell32.SHELL32_CreateFileFolderContextMenu")
#pragma comment(linker, "/export:SHELL32_CreateLinkInfoW=shell32.SHELL32_CreateLinkInfoW")
#pragma comment(linker, "/export:SHELL32_CreatePlaceholderFile=shell32.SHELL32_CreatePlaceholderFile")
#pragma comment(linker, "/export:SHELL32_CreateQosRecorder=shell32.SHELL32_CreateQosRecorder")
#pragma comment(linker, "/export:SHELL32_CreateSharePointView=shell32.SHELL32_CreateSharePointView")
#pragma comment(linker, "/export:SHELL32_Create_IEnumUICommand=shell32.SHELL32_Create_IEnumUICommand")
#pragma comment(linker, "/export:SHELL32_DestroyLinkInfo=shell32.SHELL32_DestroyLinkInfo")
#pragma comment(linker, "/export:SHELL32_EncryptDirectory=shell32.SHELL32_EncryptDirectory")
#pragma comment(linker, "/export:SHELL32_EncryptedFileKeyInfo=shell32.SHELL32_EncryptedFileKeyInfo")
#pragma comment(linker, "/export:SHELL32_EnumCommonTasks=shell32.SHELL32_EnumCommonTasks")
#pragma comment(linker, "/export:SHELL32_FilePlaceholder_BindToPrimaryStream=shell32.SHELL32_FilePlaceholder_BindToPrimaryStream")
#pragma comment(linker, "/export:SHELL32_FilePlaceholder_CreateInstance=shell32.SHELL32_FilePlaceholder_CreateInstance")
#pragma comment(linker, "/export:SHELL32_FreeEncryptedFileKeyInfo=shell32.SHELL32_FreeEncryptedFileKeyInfo")
#pragma comment(linker, "/export:SHELL32_GenerateAppID=shell32.SHELL32_GenerateAppID")
#pragma comment(linker, "/export:SHELL32_GetAppIDRoot=shell32.SHELL32_GetAppIDRoot")
#pragma comment(linker, "/export:SHELL32_GetCommandProviderForFolderType=shell32.SHELL32_GetCommandProviderForFolderType")
#pragma comment(linker, "/export:SHELL32_GetDPIAdjustedLogicalSize=shell32.SHELL32_GetDPIAdjustedLogicalSize")
#pragma comment(linker, "/export:SHELL32_GetDiskCleanupPath=shell32.SHELL32_GetDiskCleanupPath")
#pragma comment(linker, "/export:SHELL32_GetFileNameFromBrowse=shell32.SHELL32_GetFileNameFromBrowse")
#pragma comment(linker, "/export:SHELL32_GetIconOverlayManager=shell32.SHELL32_GetIconOverlayManager")
#pragma comment(linker, "/export:SHELL32_GetLinkInfoData=shell32.SHELL32_GetLinkInfoData")
#pragma comment(linker, "/export:SHELL32_GetPlaceholderStatesFromFileAttributesAndReparsePointTag=shell32.SHELL32_GetPlaceholderStatesFromFileAttributesAndReparsePointTag")
#pragma comment(linker, "/export:SHELL32_GetRatingBucket=shell32.SHELL32_GetRatingBucket")
#pragma comment(linker, "/export:SHELL32_GetSkyDriveNetworkStates=shell32.SHELL32_GetSkyDriveNetworkStates")
#pragma comment(linker, "/export:SHELL32_GetSqmableFileName=shell32.SHELL32_GetSqmableFileName")
#pragma comment(linker, "/export:SHELL32_GetThumbnailAdornerFromFactory=shell32.SHELL32_GetThumbnailAdornerFromFactory")
#pragma comment(linker, "/export:SHELL32_GetThumbnailAdornerFromFactory2=shell32.SHELL32_GetThumbnailAdornerFromFactory2")
#pragma comment(linker, "/export:SHELL32_HandleUnrecognizedFileSystem=shell32.SHELL32_HandleUnrecognizedFileSystem")
#pragma comment(linker, "/export:SHELL32_IconCacheCreate=shell32.SHELL32_IconCacheCreate")
#pragma comment(linker, "/export:SHELL32_IconCacheDestroy=shell32.SHELL32_IconCacheDestroy")
#pragma comment(linker, "/export:SHELL32_IconCacheHandleAssociationChanged=shell32.SHELL32_IconCacheHandleAssociationChanged")
#pragma comment(linker, "/export:SHELL32_IconCacheRestore=shell32.SHELL32_IconCacheRestore")
#pragma comment(linker, "/export:SHELL32_IconCache_AboutToExtractIcons=shell32.SHELL32_IconCache_AboutToExtractIcons")
#pragma comment(linker, "/export:SHELL32_IconCache_DoneExtractingIcons=shell32.SHELL32_IconCache_DoneExtractingIcons")
#pragma comment(linker, "/export:SHELL32_IconCache_ExpandEnvAndSearchPath=shell32.SHELL32_IconCache_ExpandEnvAndSearchPath")
#pragma comment(linker, "/export:SHELL32_IconCache_RememberRecentlyExtractedIconsW=shell32.SHELL32_IconCache_RememberRecentlyExtractedIconsW")
#pragma comment(linker, "/export:SHELL32_IconOverlayManagerInit=shell32.SHELL32_IconOverlayManagerInit")
#pragma comment(linker, "/export:SHELL32_IsGetKeyboardLayoutPresent=shell32.SHELL32_IsGetKeyboardLayoutPresent")
#pragma comment(linker, "/export:SHELL32_IsSystemUpgradeInProgress=shell32.SHELL32_IsSystemUpgradeInProgress")
#pragma comment(linker, "/export:SHELL32_IsValidLinkInfo=shell32.SHELL32_IsValidLinkInfo")
#pragma comment(linker, "/export:SHELL32_LegacyEnumSpecialTasksByType=shell32.SHELL32_LegacyEnumSpecialTasksByType")
#pragma comment(linker, "/export:SHELL32_LegacyEnumTasks=shell32.SHELL32_LegacyEnumTasks")
#pragma comment(linker, "/export:SHELL32_LookupBackIconIndex=shell32.SHELL32_LookupBackIconIndex")
#pragma comment(linker, "/export:SHELL32_LookupFrontIconIndex=shell32.SHELL32_LookupFrontIconIndex")
#pragma comment(linker, "/export:SHELL32_NormalizeRating=shell32.SHELL32_NormalizeRating")
#pragma comment(linker, "/export:SHELL32_NotifyLinkTrackingServiceOfMove=shell32.SHELL32_NotifyLinkTrackingServiceOfMove")
#pragma comment(linker, "/export:SHELL32_PifMgr_CloseProperties=shell32.SHELL32_PifMgr_CloseProperties")
#pragma comment(linker, "/export:SHELL32_PifMgr_GetProperties=shell32.SHELL32_PifMgr_GetProperties")
#pragma comment(linker, "/export:SHELL32_PifMgr_OpenProperties=shell32.SHELL32_PifMgr_OpenProperties")
#pragma comment(linker, "/export:SHELL32_PifMgr_SetProperties=shell32.SHELL32_PifMgr_SetProperties")
#pragma comment(linker, "/export:SHELL32_Printers_CreateBindInfo=shell32.SHELL32_Printers_CreateBindInfo")
#pragma comment(linker, "/export:SHELL32_Printjob_GetPidl=shell32.SHELL32_Printjob_GetPidl")
#pragma comment(linker, "/export:SHELL32_PurgeSystemIcon=shell32.SHELL32_PurgeSystemIcon")
#pragma comment(linker, "/export:SHELL32_RefreshOverlayImages=shell32.SHELL32_RefreshOverlayImages")
#pragma comment(linker, "/export:SHELL32_ResolveLinkInfoW=shell32.SHELL32_ResolveLinkInfoW")
#pragma comment(linker, "/export:SHELL32_SHAddSparseIcon=shell32.SHELL32_SHAddSparseIcon")
#pragma comment(linker, "/export:SHELL32_SHCreateByValueOperationInterrupt=shell32.SHELL32_SHCreateByValueOperationInterrupt")
#pragma comment(linker, "/export:SHELL32_SHCreateDefaultContextMenu=shell32.SHELL32_SHCreateDefaultContextMenu")
#pragma comment(linker, "/export:SHELL32_SHCreateLocalServer=shell32.SHELL32_SHCreateLocalServer")
#pragma comment(linker, "/export:SHELL32_SHCreateShellFolderView=shell32.SHELL32_SHCreateShellFolderView")
#pragma comment(linker, "/export:SHELL32_SHDuplicateEncryptionInfoFile=shell32.SHELL32_SHDuplicateEncryptionInfoFile")
#pragma comment(linker, "/export:SHELL32_SHEncryptFile=shell32.SHELL32_SHEncryptFile")
#pragma comment(linker, "/export:SHELL32_SHFormatDriveAsync=shell32.SHELL32_SHFormatDriveAsync")
#pragma comment(linker, "/export:SHELL32_SHGetThreadUndoManager=shell32.SHELL32_SHGetThreadUndoManager")
#pragma comment(linker, "/export:SHELL32_SHGetUserNameW=shell32.SHELL32_SHGetUserNameW")
#pragma comment(linker, "/export:SHELL32_SHIsVirtualDevice=shell32.SHELL32_SHIsVirtualDevice")
#pragma comment(linker, "/export:SHELL32_SHLaunchPropSheet=shell32.SHELL32_SHLaunchPropSheet")
#pragma comment(linker, "/export:SHELL32_SHLogILFromFSIL=shell32.SHELL32_SHLogILFromFSIL")
#pragma comment(linker, "/export:SHELL32_SHOpenWithDialog=shell32.SHELL32_SHOpenWithDialog")
#pragma comment(linker, "/export:SHELL32_SHStartNetConnectionDialogW=shell32.SHELL32_SHStartNetConnectionDialogW")
#pragma comment(linker, "/export:SHELL32_SHUICommandFromGUID=shell32.SHELL32_SHUICommandFromGUID")
#pragma comment(linker, "/export:SHELL32_SendToMenu_InvokeTargetedCommand=shell32.SHELL32_SendToMenu_InvokeTargetedCommand")
#pragma comment(linker, "/export:SHELL32_SendToMenu_VerifyTargetedCommand=shell32.SHELL32_SendToMenu_VerifyTargetedCommand")
#pragma comment(linker, "/export:SHELL32_SetPlaceholderReparsePointAttribute=shell32.SHELL32_SetPlaceholderReparsePointAttribute")
#pragma comment(linker, "/export:SHELL32_SetPlaceholderReparsePointAttribute2=shell32.SHELL32_SetPlaceholderReparsePointAttribute2")
#pragma comment(linker, "/export:SHELL32_ShowHideIconOnlyOnDesktop=shell32.SHELL32_ShowHideIconOnlyOnDesktop")
#pragma comment(linker, "/export:SHELL32_SimpleRatingToFilterCondition=shell32.SHELL32_SimpleRatingToFilterCondition")
#pragma comment(linker, "/export:SHELL32_StampIconForFile=shell32.SHELL32_StampIconForFile")
#pragma comment(linker, "/export:SHELL32_SuspendUndo=shell32.SHELL32_SuspendUndo")
#pragma comment(linker, "/export:SHELL32_TryVirtualDiscImageDriveEject=shell32.SHELL32_TryVirtualDiscImageDriveEject")
#pragma comment(linker, "/export:SHELL32_UpdateFilePlaceholderStates=shell32.SHELL32_UpdateFilePlaceholderStates")
#pragma comment(linker, "/export:SHELL32_VerifySaferTrust=shell32.SHELL32_VerifySaferTrust")
#pragma comment(linker, "/export:SHEmptyRecycleBinA=shell32.SHEmptyRecycleBinA") // XP
#pragma comment(linker, "/export:SHEmptyRecycleBinW=shell32.SHEmptyRecycleBinW") // XP
#pragma comment(linker, "/export:SHEnableServiceObject=shell32.SHEnableServiceObject") // XP
#pragma comment(linker, "/export:SHEnumerateUnreadMailAccountsW=shell32.SHEnumerateUnreadMailAccountsW") // XP
#pragma comment(linker, "/export:SHEvaluateSystemCommandTemplate=shell32.SHEvaluateSystemCommandTemplate")
#pragma comment(linker, "/export:SHExtractIconsW=shell32.SHExtractIconsW") // XP
#pragma comment(linker, "/export:SHFileOperation=shell32.SHFileOperation") // XP
#pragma comment(linker, "/export:SHFileOperationA=shell32.SHFileOperationA") // XP
#pragma comment(linker, "/export:SHFileOperationW=shell32.SHFileOperationW") // XP
#pragma comment(linker, "/export:SHFindFiles=shell32.SHFindFiles") // XP
#pragma comment(linker, "/export:SHFind_InitMenuPopup=shell32.SHFind_InitMenuPopup") // XP
#pragma comment(linker, "/export:SHFlushSFCache=shell32.SHFlushSFCache") // XP
#pragma comment(linker, "/export:SHFormatDrive=shell32.SHFormatDrive") // XP
#pragma comment(linker, "/export:SHFree=shell32.SHFree") // XP
#pragma comment(linker, "/export:SHFreeNameMappings=shell32.SHFreeNameMappings") // XP
#pragma comment(linker, "/export:SHGetAttributesFromDataObject=shell32.SHGetAttributesFromDataObject") // XP
#pragma comment(linker, "/export:SHGetDataFromIDListA=shell32.SHGetDataFromIDListA") // XP
#pragma comment(linker, "/export:SHGetDataFromIDListW=shell32.SHGetDataFromIDListW") // XP
#pragma comment(linker, "/export:SHGetDesktopFolder=shell32.SHGetDesktopFolder") // XP
#pragma comment(linker, "/export:SHGetDiskFreeSpaceA=shell32.SHGetDiskFreeSpaceA") // XP
#pragma comment(linker, "/export:SHGetDiskFreeSpaceExA=shell32.SHGetDiskFreeSpaceExA") // XP
#pragma comment(linker, "/export:SHGetDiskFreeSpaceExW=shell32.SHGetDiskFreeSpaceExW") // XP
#pragma comment(linker, "/export:SHGetDriveMedia=shell32.SHGetDriveMedia")
#pragma comment(linker, "/export:SHGetFileInfo=shell32.SHGetFileInfo") // XP
#pragma comment(linker, "/export:SHGetFileInfoA=shell32.SHGetFileInfoA") // XP
#pragma comment(linker, "/export:SHGetFileInfoW=shell32.SHGetFileInfoW") // XP
#pragma comment(linker, "/export:SHGetFolderLocation=shell32.SHGetFolderLocation") // XP
#pragma comment(linker, "/export:SHGetFolderPathA=shell32.SHGetFolderPathA") // XP
#pragma comment(linker, "/export:SHGetFolderPathAndSubDirA=shell32.SHGetFolderPathAndSubDirA") // XP
#pragma comment(linker, "/export:SHGetFolderPathAndSubDirW=shell32.SHGetFolderPathAndSubDirW") // XP
#pragma comment(linker, "/export:SHGetFolderPathEx=shell32.SHGetFolderPathEx")
#pragma comment(linker, "/export:SHGetFolderPathW=shell32.SHGetFolderPathW") // XP
#pragma comment(linker, "/export:SHGetIDListFromObject=shell32.SHGetIDListFromObject")
#pragma comment(linker, "/export:SHGetIconOverlayIndexA=shell32.SHGetIconOverlayIndexA") // XP
#pragma comment(linker, "/export:SHGetIconOverlayIndexW=shell32.SHGetIconOverlayIndexW") // XP
#pragma comment(linker, "/export:SHGetImageList=shell32.SHGetImageList") // XP
#pragma comment(linker, "/export:SHGetInstanceExplorer=shell32.SHGetInstanceExplorer") // XP
#pragma comment(linker, "/export:SHGetItemFromDataObject=shell32.SHGetItemFromDataObject")
#pragma comment(linker, "/export:SHGetItemFromObject=shell32.SHGetItemFromObject")
#pragma comment(linker, "/export:SHGetKnownFolderIDList=shell32.SHGetKnownFolderIDList")
#pragma comment(linker, "/export:SHGetKnownFolderItem=shell32.SHGetKnownFolderItem")
#pragma comment(linker, "/export:SHGetKnownFolderPath=shell32.SHGetKnownFolderPath")
#pragma comment(linker, "/export:SHGetLocalizedName=shell32.SHGetLocalizedName")
#pragma comment(linker, "/export:SHGetMalloc=shell32.SHGetMalloc") // XP
#pragma comment(linker, "/export:SHGetNameFromIDList=shell32.SHGetNameFromIDList")
#pragma comment(linker, "/export:SHGetNewLinkInfo=shell32.SHGetNewLinkInfo") // XP
#pragma comment(linker, "/export:SHGetNewLinkInfoA=shell32.SHGetNewLinkInfoA") // XP
#pragma comment(linker, "/export:SHGetNewLinkInfoW=shell32.SHGetNewLinkInfoW") // XP
#pragma comment(linker, "/export:SHGetPathFromIDList=shell32.SHGetPathFromIDList") // XP
#pragma comment(linker, "/export:SHGetPathFromIDListA=shell32.SHGetPathFromIDListA") // XP
#pragma comment(linker, "/export:SHGetPathFromIDListEx=shell32.SHGetPathFromIDListEx")
#pragma comment(linker, "/export:SHGetPathFromIDListW=shell32.SHGetPathFromIDListW") // XP
#pragma comment(linker, "/export:SHGetPropertyStoreForWindow=shell32.SHGetPropertyStoreForWindow")
#pragma comment(linker, "/export:SHGetPropertyStoreFromIDList=shell32.SHGetPropertyStoreFromIDList")
#pragma comment(linker, "/export:SHGetPropertyStoreFromParsingName=shell32.SHGetPropertyStoreFromParsingName")
#pragma comment(linker, "/export:SHGetRealIDL=shell32.SHGetRealIDL") // XP
#pragma comment(linker, "/export:SHGetSetFolderCustomSettings=shell32.SHGetSetFolderCustomSettings")
#pragma comment(linker, "/export:SHGetSetSettings=shell32.SHGetSetSettings") // XP
#pragma comment(linker, "/export:SHGetSettings=shell32.SHGetSettings") // XP
#pragma comment(linker, "/export:SHGetSpecialFolderLocation=shell32.SHGetSpecialFolderLocation") // XP
#pragma comment(linker, "/export:SHGetSpecialFolderPathA=shell32.SHGetSpecialFolderPathA") // XP
#pragma comment(linker, "/export:SHGetSpecialFolderPathW=shell32.SHGetSpecialFolderPathW") // XP
#pragma comment(linker, "/export:SHGetStockIconInfo=shell32.SHGetStockIconInfo")
#pragma comment(linker, "/export:SHGetTemporaryPropertyForItem=shell32.SHGetTemporaryPropertyForItem")
#pragma comment(linker, "/export:SHGetUnreadMailCountW=shell32.SHGetUnreadMailCountW") // XP
#pragma comment(linker, "/export:SHHandleUpdateImage=shell32.SHHandleUpdateImage") // XP
#pragma comment(linker, "/export:SHHelpShortcuts_RunDLL=shell32.SHHelpShortcuts_RunDLL") // XP
#pragma comment(linker, "/export:SHHelpShortcuts_RunDLLA=shell32.SHHelpShortcuts_RunDLLA") // XP
#pragma comment(linker, "/export:SHHelpShortcuts_RunDLLW=shell32.SHHelpShortcuts_RunDLLW") // XP
#pragma comment(linker, "/export:SHILCreateFromPath=shell32.SHILCreateFromPath") // XP
#pragma comment(linker, "/export:SHInvokePrinterCommandA=shell32.SHInvokePrinterCommandA") // XP
#pragma comment(linker, "/export:SHInvokePrinterCommandW=shell32.SHInvokePrinterCommandW") // XP
#pragma comment(linker, "/export:SHIsFileAvailableOffline=shell32.SHIsFileAvailableOffline") // XP
#pragma comment(linker, "/export:SHLimitInputEdit=shell32.SHLimitInputEdit") // XP
#pragma comment(linker, "/export:SHLoadInProc=shell32.SHLoadInProc") // XP
#pragma comment(linker, "/export:SHLoadNonloadedIconOverlayIdentifiers=shell32.SHLoadNonloadedIconOverlayIdentifiers") // XP
#pragma comment(linker, "/export:SHMapPIDLToSystemImageListIndex=shell32.SHMapPIDLToSystemImageListIndex") // XP
#pragma comment(linker, "/export:SHMultiFileProperties=shell32.SHMultiFileProperties") // XP
#pragma comment(linker, "/export:SHObjectProperties=shell32.SHObjectProperties") // XP
#pragma comment(linker, "/export:SHOpenFolderAndSelectItems=shell32.SHOpenFolderAndSelectItems") // XP
#pragma comment(linker, "/export:SHOpenPropSheetW=shell32.SHOpenPropSheetW") // XP
#pragma comment(linker, "/export:SHOpenWithDialog=shell32.SHOpenWithDialog")
#pragma comment(linker, "/export:SHParseDisplayName=shell32.SHParseDisplayName") // XP
#pragma comment(linker, "/export:SHPathPrepareForWriteA=shell32.SHPathPrepareForWriteA") // XP
#pragma comment(linker, "/export:SHPathPrepareForWriteW=shell32.SHPathPrepareForWriteW") // XP
#pragma comment(linker, "/export:SHPropStgCreate=shell32.SHPropStgCreate") // XP
#pragma comment(linker, "/export:SHPropStgReadMultiple=shell32.SHPropStgReadMultiple") // XP
#pragma comment(linker, "/export:SHPropStgWriteMultiple=shell32.SHPropStgWriteMultiple") // XP
#pragma comment(linker, "/export:SHQueryRecycleBinA=shell32.SHQueryRecycleBinA") // XP
#pragma comment(linker, "/export:SHQueryRecycleBinW=shell32.SHQueryRecycleBinW") // XP
#pragma comment(linker, "/export:SHQueryUserNotificationState=shell32.SHQueryUserNotificationState")
#pragma comment(linker, "/export:SHRemoveLocalizedName=shell32.SHRemoveLocalizedName")
#pragma comment(linker, "/export:SHReplaceFromPropSheetExtArray=shell32.SHReplaceFromPropSheetExtArray") // XP
#pragma comment(linker, "/export:SHResolveLibrary=shell32.SHResolveLibrary")
#pragma comment(linker, "/export:SHRestricted=shell32.SHRestricted") // XP
#pragma comment(linker, "/export:SHSetDefaultProperties=shell32.SHSetDefaultProperties")
#pragma comment(linker, "/export:SHSetFolderPathA=shell32.SHSetFolderPathA")
#pragma comment(linker, "/export:SHSetFolderPathW=shell32.SHSetFolderPathW")
#pragma comment(linker, "/export:SHSetInstanceExplorer=shell32.SHSetInstanceExplorer") // XP
#pragma comment(linker, "/export:SHSetKnownFolderPath=shell32.SHSetKnownFolderPath")
#pragma comment(linker, "/export:SHSetLocalizedName=shell32.SHSetLocalizedName") // XP
#pragma comment(linker, "/export:SHSetTemporaryPropertyForItem=shell32.SHSetTemporaryPropertyForItem")
#pragma comment(linker, "/export:SHSetUnreadMailCountW=shell32.SHSetUnreadMailCountW") // XP
#pragma comment(linker, "/export:SHShellFolderView_Message=shell32.SHShellFolderView_Message") // XP
#pragma comment(linker, "/export:SHShowManageLibraryUI=shell32.SHShowManageLibraryUI")
#pragma comment(linker, "/export:SHSimpleIDListFromPath=shell32.SHSimpleIDListFromPath") // XP
#pragma comment(linker, "/export:SHStartNetConnectionDialogW=shell32.SHStartNetConnectionDialogW") // XP
#pragma comment(linker, "/export:SHTestTokenMembership=shell32.SHTestTokenMembership") // XP
#pragma comment(linker, "/export:SHUpdateImageA=shell32.SHUpdateImageA") // XP
#pragma comment(linker, "/export:SHUpdateImageW=shell32.SHUpdateImageW") // XP
#pragma comment(linker, "/export:SHUpdateRecycleBinIcon=shell32.SHUpdateRecycleBinIcon") // XP
#pragma comment(linker, "/export:SHValidateUNC=shell32.SHValidateUNC") // XP
#pragma comment(linker, "/export:SetCurrentProcessExplicitAppUserModelID=shell32.SetCurrentProcessExplicitAppUserModelID")
#pragma comment(linker, "/export:SheChangeDirA=shell32.SheChangeDirA") // XP
#pragma comment(linker, "/export:SheChangeDirExW=shell32.SheChangeDirExW") // XP
#pragma comment(linker, "/export:SheGetDirA=shell32.SheGetDirA") // XP
#pragma comment(linker, "/export:SheSetCurDrive=shell32.SheSetCurDrive") // XP
#pragma comment(linker, "/export:ShellAboutA=shell32.ShellAboutA") // XP
#pragma comment(linker, "/export:ShellAboutW=shell32.ShellAboutW") // XP
#pragma comment(linker, "/export:ShellExec_RunDLL=shell32.ShellExec_RunDLL") // XP
#pragma comment(linker, "/export:ShellExec_RunDLLA=shell32.ShellExec_RunDLLA") // XP
#pragma comment(linker, "/export:ShellExec_RunDLLW=shell32.ShellExec_RunDLLW") // XP
#pragma comment(linker, "/export:ShellExecuteA=shell32.ShellExecuteA") // XP
#pragma comment(linker, "/export:ShellExecuteEx=shell32.ShellExecuteEx") // XP
#pragma comment(linker, "/export:ShellExecuteExA=shell32.ShellExecuteExA") // XP
#pragma comment(linker, "/export:ShellExecuteExW=shell32.ShellExecuteExW") // XP
#pragma comment(linker, "/export:ShellExecuteW=shell32.ShellExecuteW") // XP
#pragma comment(linker, "/export:ShellHookProc=shell32.ShellHookProc") // XP
#pragma comment(linker, "/export:ShellMessageBoxA=shell32.ShellMessageBoxA") // XP
#pragma comment(linker, "/export:ShellMessageBoxW=shell32.ShellMessageBoxW") // XP
#pragma comment(linker, "/export:Shell_GetCachedImageIndex=shell32.Shell_GetCachedImageIndex") // XP
#pragma comment(linker, "/export:Shell_GetCachedImageIndexA=shell32.Shell_GetCachedImageIndexA")
#pragma comment(linker, "/export:Shell_GetCachedImageIndexW=shell32.Shell_GetCachedImageIndexW")
#pragma comment(linker, "/export:Shell_GetImageLists=shell32.Shell_GetImageLists") // XP
#pragma comment(linker, "/export:Shell_MergeMenus=shell32.Shell_MergeMenus") // XP
#pragma comment(linker, "/export:Shell_NotifyIcon=shell32.Shell_NotifyIcon") // XP
#pragma comment(linker, "/export:Shell_NotifyIconA=shell32.Shell_NotifyIconA") // XP
#pragma comment(linker, "/export:Shell_NotifyIconGetRect=shell32.Shell_NotifyIconGetRect")
#pragma comment(linker, "/export:Shell_NotifyIconW=shell32.Shell_NotifyIconW") // XP
#pragma comment(linker, "/export:SignalFileOpen=shell32.SignalFileOpen") // XP
#pragma comment(linker, "/export:StgMakeUniqueName=shell32.StgMakeUniqueName")
#pragma comment(linker, "/export:StrChrA=shell32.StrChrA") // XP
#pragma comment(linker, "/export:StrChrIA=shell32.StrChrIA") // XP
#pragma comment(linker, "/export:StrChrIW=shell32.StrChrIW") // XP
#pragma comment(linker, "/export:StrChrW=shell32.StrChrW") // XP
#pragma comment(linker, "/export:StrCmpNA=shell32.StrCmpNA") // XP
#pragma comment(linker, "/export:StrCmpNIA=shell32.StrCmpNIA") // XP
#pragma comment(linker, "/export:StrCmpNIW=shell32.StrCmpNIW") // XP
#pragma comment(linker, "/export:StrCmpNW=shell32.StrCmpNW") // XP
#pragma comment(linker, "/export:StrNCmpA=shell32.StrNCmpA") // XP
#pragma comment(linker, "/export:StrNCmpIA=shell32.StrNCmpIA") // XP
#pragma comment(linker, "/export:StrNCmpIW=shell32.StrNCmpIW") // XP
#pragma comment(linker, "/export:StrNCmpW=shell32.StrNCmpW") // XP
#pragma comment(linker, "/export:StrRChrA=shell32.StrRChrA") // XP
#pragma comment(linker, "/export:StrRChrIA=shell32.StrRChrIA") // XP
#pragma comment(linker, "/export:StrRChrIW=shell32.StrRChrIW") // XP
#pragma comment(linker, "/export:StrRChrW=shell32.StrRChrW") // XP
#pragma comment(linker, "/export:StrRStrA=shell32.StrRStrA") // XP
#pragma comment(linker, "/export:StrRStrIA=shell32.StrRStrIA") // XP
#pragma comment(linker, "/export:StrRStrIW=shell32.StrRStrIW") // XP
#pragma comment(linker, "/export:StrRStrW=shell32.StrRStrW") // XP
#pragma comment(linker, "/export:StrStrA=shell32.StrStrA") // XP
#pragma comment(linker, "/export:StrStrIA=shell32.StrStrIA") // XP
#pragma comment(linker, "/export:StrStrIW=shell32.StrStrIW") // XP
#pragma comment(linker, "/export:StrStrW=shell32.StrStrW") // XP
#pragma comment(linker, "/export:UsersLibrariesFolderUI_CreateInstance=shell32.UsersLibrariesFolderUI_CreateInstance")
#pragma comment(linker, "/export:WOWShellExecute=shell32.WOWShellExecute") // XP
#pragma comment(linker, "/export:WaitForExplorerRestartW=shell32.WaitForExplorerRestartW")
#pragma comment(linker, "/export:Win32DeleteFile=shell32.Win32DeleteFile") // XP
#pragma comment(linker, "/export:WriteCabinetState=shell32.WriteCabinetState") // XP
