#include <WinDef.h>

#pragma comment(linker, "/export:AssocCreate=shlwapi.AssocCreate") // XP
#pragma comment(linker, "/export:AssocGetPerceivedType=shlwapi.AssocGetPerceivedType") // XP
#pragma comment(linker, "/export:AssocIsDangerous=shlwapi.AssocIsDangerous") // XP
#pragma comment(linker, "/export:AssocQueryKeyA=shlwapi.AssocQueryKeyA") // XP
#pragma comment(linker, "/export:AssocQueryKeyW=shlwapi.AssocQueryKeyW") // XP
#pragma comment(linker, "/export:AssocQueryStringA=shlwapi.AssocQueryStringA") // XP
#pragma comment(linker, "/export:AssocQueryStringByKeyA=shlwapi.AssocQueryStringByKeyA") // XP
#pragma comment(linker, "/export:AssocQueryStringByKeyW=shlwapi.AssocQueryStringByKeyW") // XP
#pragma comment(linker, "/export:AssocQueryStringW=shlwapi.AssocQueryStringW") // XP
#pragma comment(linker, "/export:ChrCmpIA=shlwapi.ChrCmpIA") // XP
#pragma comment(linker, "/export:ChrCmpIW=shlwapi.ChrCmpIW") // XP
#pragma comment(linker, "/export:ColorAdjustLuma=shlwapi.ColorAdjustLuma") // XP
#pragma comment(linker, "/export:ColorHLSToRGB=shlwapi.ColorHLSToRGB") // XP
#pragma comment(linker, "/export:ColorRGBToHLS=shlwapi.ColorRGBToHLS") // XP
#pragma comment(linker, "/export:ConnectToConnectionPoint=shlwapi.ConnectToConnectionPoint")
#pragma comment(linker, "/export:DelayLoadFailureHook=shlwapi.DelayLoadFailureHook") // XP
#pragma comment(linker, "/export:DllGetClassObject=shlwapi.DllGetClassObject")
#pragma comment(linker, "/export:DllGetVersion=shlwapi.DllGetVersion") // XP
#pragma comment(linker, "/export:GUIDFromStringW=shlwapi.GUIDFromStringW")
#pragma comment(linker, "/export:GetAcceptLanguagesA=shlwapi.GetAcceptLanguagesA") // XP
#pragma comment(linker, "/export:GetAcceptLanguagesW=shlwapi.GetAcceptLanguagesW") // XP
#pragma comment(linker, "/export:GetMenuPosFromID=shlwapi.GetMenuPosFromID") // XP
#pragma comment(linker, "/export:HashData=shlwapi.HashData") // XP
#pragma comment(linker, "/export:IStream_Copy=shlwapi.IStream_Copy")
#pragma comment(linker, "/export:IStream_Read=shlwapi.IStream_Read")
#pragma comment(linker, "/export:IStream_ReadPidl=shlwapi.IStream_ReadPidl")
#pragma comment(linker, "/export:IStream_ReadStr=shlwapi.IStream_ReadStr")
#pragma comment(linker, "/export:IStream_Reset=shlwapi.IStream_Reset")
#pragma comment(linker, "/export:IStream_Size=shlwapi.IStream_Size")
#pragma comment(linker, "/export:IStream_Write=shlwapi.IStream_Write")
#pragma comment(linker, "/export:IStream_WritePidl=shlwapi.IStream_WritePidl")
#pragma comment(linker, "/export:IStream_WriteStr=shlwapi.IStream_WriteStr")
#pragma comment(linker, "/export:IUnknown_AtomicRelease=shlwapi.IUnknown_AtomicRelease")
#pragma comment(linker, "/export:IUnknown_Exec=shlwapi.IUnknown_Exec")
#pragma comment(linker, "/export:IUnknown_GetSite=shlwapi.IUnknown_GetSite")
#pragma comment(linker, "/export:IUnknown_GetWindow=shlwapi.IUnknown_GetWindow")
#pragma comment(linker, "/export:IUnknown_QueryService=shlwapi.IUnknown_QueryService")
#pragma comment(linker, "/export:IUnknown_QueryStatus=shlwapi.IUnknown_QueryStatus")
#pragma comment(linker, "/export:IUnknown_Set=shlwapi.IUnknown_Set")
#pragma comment(linker, "/export:IUnknown_SetSite=shlwapi.IUnknown_SetSite")
#pragma comment(linker, "/export:IntlStrEqWorkerA=shlwapi.IntlStrEqWorkerA") // XP
#pragma comment(linker, "/export:IntlStrEqWorkerW=shlwapi.IntlStrEqWorkerW") // XP
#pragma comment(linker, "/export:IsCharSpaceA=shlwapi.IsCharSpaceA") // XP
#pragma comment(linker, "/export:IsCharSpaceW=shlwapi.IsCharSpaceW") // XP
#pragma comment(linker, "/export:IsInternetESCEnabled=shlwapi.IsInternetESCEnabled")
#pragma comment(linker, "/export:IsOS=shlwapi.IsOS")
#pragma comment(linker, "/export:MLLoadLibraryA=shlwapi.MLLoadLibraryA")
#pragma comment(linker, "/export:MLLoadLibraryW=shlwapi.MLLoadLibraryW")
#pragma comment(linker, "/export:ParseURLA=shlwapi.ParseURLA")
#pragma comment(linker, "/export:ParseURLW=shlwapi.ParseURLW")
#pragma comment(linker, "/export:PathAddBackslashA=shlwapi.PathAddBackslashA") // XP
#pragma comment(linker, "/export:PathAddBackslashW=shlwapi.PathAddBackslashW") // XP
#pragma comment(linker, "/export:PathAddExtensionA=shlwapi.PathAddExtensionA") // XP
#pragma comment(linker, "/export:PathAddExtensionW=shlwapi.PathAddExtensionW") // XP
#pragma comment(linker, "/export:PathAppendA=shlwapi.PathAppendA") // XP
#pragma comment(linker, "/export:PathAppendW=shlwapi.PathAppendW") // XP
#pragma comment(linker, "/export:PathBuildRootA=shlwapi.PathBuildRootA") // XP
#pragma comment(linker, "/export:PathBuildRootW=shlwapi.PathBuildRootW") // XP
#pragma comment(linker, "/export:PathCanonicalizeA=shlwapi.PathCanonicalizeA") // XP
#pragma comment(linker, "/export:PathCanonicalizeW=shlwapi.PathCanonicalizeW") // XP
#pragma comment(linker, "/export:PathCombineA=shlwapi.PathCombineA") // XP
#pragma comment(linker, "/export:PathCombineW=shlwapi.PathCombineW") // XP
#pragma comment(linker, "/export:PathCommonPrefixA=shlwapi.PathCommonPrefixA") // XP
#pragma comment(linker, "/export:PathCommonPrefixW=shlwapi.PathCommonPrefixW") // XP
#pragma comment(linker, "/export:PathCompactPathA=shlwapi.PathCompactPathA") // XP
#pragma comment(linker, "/export:PathCompactPathExA=shlwapi.PathCompactPathExA") // XP
#pragma comment(linker, "/export:PathCompactPathExW=shlwapi.PathCompactPathExW") // XP
#pragma comment(linker, "/export:PathCompactPathW=shlwapi.PathCompactPathW") // XP
#pragma comment(linker, "/export:PathCreateFromUrlA=shlwapi.PathCreateFromUrlA") // XP
#pragma comment(linker, "/export:PathCreateFromUrlAlloc=shlwapi.PathCreateFromUrlAlloc")
#pragma comment(linker, "/export:PathCreateFromUrlW=shlwapi.PathCreateFromUrlW") // XP
#pragma comment(linker, "/export:PathFileExistsA=shlwapi.PathFileExistsA") // XP
#pragma comment(linker, "/export:PathFileExistsAndAttributesW=shlwapi.PathFileExistsAndAttributesW")
#pragma comment(linker, "/export:PathFileExistsW=shlwapi.PathFileExistsW") // XP
#pragma comment(linker, "/export:PathFindExtensionA=shlwapi.PathFindExtensionA") // XP
#pragma comment(linker, "/export:PathFindExtensionW=shlwapi.PathFindExtensionW") // XP
#pragma comment(linker, "/export:PathFindFileNameA=shlwapi.PathFindFileNameA") // XP
#pragma comment(linker, "/export:PathFindFileNameW=shlwapi.PathFindFileNameW") // XP
#pragma comment(linker, "/export:PathFindNextComponentA=shlwapi.PathFindNextComponentA") // XP
#pragma comment(linker, "/export:PathFindNextComponentW=shlwapi.PathFindNextComponentW") // XP
#pragma comment(linker, "/export:PathFindOnPathA=shlwapi.PathFindOnPathA") // XP
#pragma comment(linker, "/export:PathFindOnPathW=shlwapi.PathFindOnPathW") // XP
#pragma comment(linker, "/export:PathFindSuffixArrayA=shlwapi.PathFindSuffixArrayA") // XP
#pragma comment(linker, "/export:PathFindSuffixArrayW=shlwapi.PathFindSuffixArrayW") // XP
#pragma comment(linker, "/export:PathGetArgsA=shlwapi.PathGetArgsA") // XP
#pragma comment(linker, "/export:PathGetArgsW=shlwapi.PathGetArgsW") // XP
#pragma comment(linker, "/export:PathGetCharTypeA=shlwapi.PathGetCharTypeA") // XP
#pragma comment(linker, "/export:PathGetCharTypeW=shlwapi.PathGetCharTypeW") // XP
#pragma comment(linker, "/export:PathGetDriveNumberA=shlwapi.PathGetDriveNumberA") // XP
#pragma comment(linker, "/export:PathGetDriveNumberW=shlwapi.PathGetDriveNumberW") // XP
#pragma comment(linker, "/export:PathIsContentTypeA=shlwapi.PathIsContentTypeA") // XP
#pragma comment(linker, "/export:PathIsContentTypeW=shlwapi.PathIsContentTypeW") // XP
#pragma comment(linker, "/export:PathIsDirectoryA=shlwapi.PathIsDirectoryA") // XP
#pragma comment(linker, "/export:PathIsDirectoryEmptyA=shlwapi.PathIsDirectoryEmptyA") // XP
#pragma comment(linker, "/export:PathIsDirectoryEmptyW=shlwapi.PathIsDirectoryEmptyW") // XP
#pragma comment(linker, "/export:PathIsDirectoryW=shlwapi.PathIsDirectoryW") // XP
#pragma comment(linker, "/export:PathIsFileSpecA=shlwapi.PathIsFileSpecA") // XP
#pragma comment(linker, "/export:PathIsFileSpecW=shlwapi.PathIsFileSpecW") // XP
#pragma comment(linker, "/export:PathIsLFNFileSpecA=shlwapi.PathIsLFNFileSpecA") // XP
#pragma comment(linker, "/export:PathIsLFNFileSpecW=shlwapi.PathIsLFNFileSpecW") // XP
#pragma comment(linker, "/export:PathIsNetworkPathA=shlwapi.PathIsNetworkPathA") // XP
#pragma comment(linker, "/export:PathIsNetworkPathW=shlwapi.PathIsNetworkPathW") // XP
#pragma comment(linker, "/export:PathIsPrefixA=shlwapi.PathIsPrefixA") // XP
#pragma comment(linker, "/export:PathIsPrefixW=shlwapi.PathIsPrefixW") // XP
#pragma comment(linker, "/export:PathIsRelativeA=shlwapi.PathIsRelativeA") // XP
#pragma comment(linker, "/export:PathIsRelativeW=shlwapi.PathIsRelativeW") // XP
#pragma comment(linker, "/export:PathIsRootA=shlwapi.PathIsRootA") // XP
#pragma comment(linker, "/export:PathIsRootW=shlwapi.PathIsRootW") // XP
#pragma comment(linker, "/export:PathIsSameRootA=shlwapi.PathIsSameRootA") // XP
#pragma comment(linker, "/export:PathIsSameRootW=shlwapi.PathIsSameRootW") // XP
#pragma comment(linker, "/export:PathIsSystemFolderA=shlwapi.PathIsSystemFolderA") // XP
#pragma comment(linker, "/export:PathIsSystemFolderW=shlwapi.PathIsSystemFolderW") // XP
#pragma comment(linker, "/export:PathIsUNCA=shlwapi.PathIsUNCA") // XP
#pragma comment(linker, "/export:PathIsUNCServerA=shlwapi.PathIsUNCServerA") // XP
#pragma comment(linker, "/export:PathIsUNCServerShareA=shlwapi.PathIsUNCServerShareA") // XP
#pragma comment(linker, "/export:PathIsUNCServerShareW=shlwapi.PathIsUNCServerShareW") // XP
#pragma comment(linker, "/export:PathIsUNCServerW=shlwapi.PathIsUNCServerW") // XP
#pragma comment(linker, "/export:PathIsUNCW=shlwapi.PathIsUNCW") // XP
#pragma comment(linker, "/export:PathIsURLA=shlwapi.PathIsURLA") // XP
#pragma comment(linker, "/export:PathIsURLW=shlwapi.PathIsURLW") // XP
#pragma comment(linker, "/export:PathMakePrettyA=shlwapi.PathMakePrettyA") // XP
#pragma comment(linker, "/export:PathMakePrettyW=shlwapi.PathMakePrettyW") // XP
#pragma comment(linker, "/export:PathMakeSystemFolderA=shlwapi.PathMakeSystemFolderA") // XP
#pragma comment(linker, "/export:PathMakeSystemFolderW=shlwapi.PathMakeSystemFolderW") // XP
#pragma comment(linker, "/export:PathMatchSpecA=shlwapi.PathMatchSpecA") // XP
#pragma comment(linker, "/export:PathMatchSpecExA=shlwapi.PathMatchSpecExA")
#pragma comment(linker, "/export:PathMatchSpecExW=shlwapi.PathMatchSpecExW")
#pragma comment(linker, "/export:PathMatchSpecW=shlwapi.PathMatchSpecW") // XP
#pragma comment(linker, "/export:PathParseIconLocationA=shlwapi.PathParseIconLocationA") // XP
#pragma comment(linker, "/export:PathParseIconLocationW=shlwapi.PathParseIconLocationW") // XP
#pragma comment(linker, "/export:PathQuoteSpacesA=shlwapi.PathQuoteSpacesA") // XP
#pragma comment(linker, "/export:PathQuoteSpacesW=shlwapi.PathQuoteSpacesW") // XP
#pragma comment(linker, "/export:PathRelativePathToA=shlwapi.PathRelativePathToA") // XP
#pragma comment(linker, "/export:PathRelativePathToW=shlwapi.PathRelativePathToW") // XP
#pragma comment(linker, "/export:PathRemoveArgsA=shlwapi.PathRemoveArgsA") // XP
#pragma comment(linker, "/export:PathRemoveArgsW=shlwapi.PathRemoveArgsW") // XP
#pragma comment(linker, "/export:PathRemoveBackslashA=shlwapi.PathRemoveBackslashA") // XP
#pragma comment(linker, "/export:PathRemoveBackslashW=shlwapi.PathRemoveBackslashW") // XP
#pragma comment(linker, "/export:PathRemoveBlanksA=shlwapi.PathRemoveBlanksA") // XP
#pragma comment(linker, "/export:PathRemoveBlanksW=shlwapi.PathRemoveBlanksW") // XP
#pragma comment(linker, "/export:PathRemoveExtensionA=shlwapi.PathRemoveExtensionA") // XP
#pragma comment(linker, "/export:PathRemoveExtensionW=shlwapi.PathRemoveExtensionW") // XP
#pragma comment(linker, "/export:PathRemoveFileSpecA=shlwapi.PathRemoveFileSpecA") // XP
#pragma comment(linker, "/export:PathRemoveFileSpecW=shlwapi.PathRemoveFileSpecW") // XP
#pragma comment(linker, "/export:PathRenameExtensionA=shlwapi.PathRenameExtensionA") // XP
#pragma comment(linker, "/export:PathRenameExtensionW=shlwapi.PathRenameExtensionW") // XP
#pragma comment(linker, "/export:PathSearchAndQualifyA=shlwapi.PathSearchAndQualifyA") // XP
#pragma comment(linker, "/export:PathSearchAndQualifyW=shlwapi.PathSearchAndQualifyW") // XP
#pragma comment(linker, "/export:PathSetDlgItemPathA=shlwapi.PathSetDlgItemPathA") // XP
#pragma comment(linker, "/export:PathSetDlgItemPathW=shlwapi.PathSetDlgItemPathW") // XP
#pragma comment(linker, "/export:PathSkipRootA=shlwapi.PathSkipRootA") // XP
#pragma comment(linker, "/export:PathSkipRootW=shlwapi.PathSkipRootW") // XP
#pragma comment(linker, "/export:PathStripPathA=shlwapi.PathStripPathA") // XP
#pragma comment(linker, "/export:PathStripPathW=shlwapi.PathStripPathW") // XP
#pragma comment(linker, "/export:PathStripToRootA=shlwapi.PathStripToRootA") // XP
#pragma comment(linker, "/export:PathStripToRootW=shlwapi.PathStripToRootW") // XP
#pragma comment(linker, "/export:PathUnExpandEnvStringsA=shlwapi.PathUnExpandEnvStringsA") // XP
#pragma comment(linker, "/export:PathUnExpandEnvStringsW=shlwapi.PathUnExpandEnvStringsW") // XP
#pragma comment(linker, "/export:PathUndecorateA=shlwapi.PathUndecorateA") // XP
#pragma comment(linker, "/export:PathUndecorateW=shlwapi.PathUndecorateW") // XP
#pragma comment(linker, "/export:PathUnmakeSystemFolderA=shlwapi.PathUnmakeSystemFolderA") // XP
#pragma comment(linker, "/export:PathUnmakeSystemFolderW=shlwapi.PathUnmakeSystemFolderW") // XP
#pragma comment(linker, "/export:PathUnquoteSpacesA=shlwapi.PathUnquoteSpacesA") // XP
#pragma comment(linker, "/export:PathUnquoteSpacesW=shlwapi.PathUnquoteSpacesW") // XP
#pragma comment(linker, "/export:QISearch=shlwapi.QISearch")
#pragma comment(linker, "/export:SHAllocShared=shlwapi.SHAllocShared") // XP
#pragma comment(linker, "/export:SHAnsiToAnsi=shlwapi.SHAnsiToAnsi")
#pragma comment(linker, "/export:SHAnsiToUnicode=shlwapi.SHAnsiToUnicode")
#pragma comment(linker, "/export:SHAutoComplete=shlwapi.SHAutoComplete") // XP
#pragma comment(linker, "/export:SHCopyKeyA=shlwapi.SHCopyKeyA") // XP
#pragma comment(linker, "/export:SHCopyKeyW=shlwapi.SHCopyKeyW") // XP
#pragma comment(linker, "/export:SHCreateMemStream=shlwapi.SHCreateMemStream")
#pragma comment(linker, "/export:SHCreateShellPalette=shlwapi.SHCreateShellPalette") // XP
#pragma comment(linker, "/export:SHCreateStreamOnFileA=shlwapi.SHCreateStreamOnFileA") // XP
#pragma comment(linker, "/export:SHCreateStreamOnFileEx=shlwapi.SHCreateStreamOnFileEx") // XP
#pragma comment(linker, "/export:SHCreateStreamOnFileW=shlwapi.SHCreateStreamOnFileW") // XP
#pragma comment(linker, "/export:SHCreateStreamWrapper=shlwapi.SHCreateStreamWrapper") // XP
#pragma comment(linker, "/export:SHCreateThread=shlwapi.SHCreateThread") // XP
#pragma comment(linker, "/export:SHCreateThreadRef=shlwapi.SHCreateThreadRef") // XP
#pragma comment(linker, "/export:SHCreateThreadWithHandle=shlwapi.SHCreateThreadWithHandle")
#pragma comment(linker, "/export:SHCreateWorkerWindowW=shlwapi.SHCreateWorkerWindowW")
#pragma comment(linker, "/export:SHDeleteEmptyKeyA=shlwapi.SHDeleteEmptyKeyA") // XP
#pragma comment(linker, "/export:SHDeleteEmptyKeyW=shlwapi.SHDeleteEmptyKeyW") // XP
#pragma comment(linker, "/export:SHDeleteKeyA=shlwapi.SHDeleteKeyA") // XP
#pragma comment(linker, "/export:SHDeleteKeyW=shlwapi.SHDeleteKeyW") // XP
#pragma comment(linker, "/export:SHDeleteOrphanKeyA=shlwapi.SHDeleteOrphanKeyA") // XP
#pragma comment(linker, "/export:SHDeleteOrphanKeyW=shlwapi.SHDeleteOrphanKeyW") // XP
#pragma comment(linker, "/export:SHDeleteValueA=shlwapi.SHDeleteValueA") // XP
#pragma comment(linker, "/export:SHDeleteValueW=shlwapi.SHDeleteValueW") // XP
#pragma comment(linker, "/export:SHEnumKeyExA=shlwapi.SHEnumKeyExA") // XP
#pragma comment(linker, "/export:SHEnumKeyExW=shlwapi.SHEnumKeyExW") // XP
#pragma comment(linker, "/export:SHEnumValueA=shlwapi.SHEnumValueA") // XP
#pragma comment(linker, "/export:SHEnumValueW=shlwapi.SHEnumValueW") // XP
#pragma comment(linker, "/export:SHFormatDateTimeA=shlwapi.SHFormatDateTimeA")
#pragma comment(linker, "/export:SHFormatDateTimeW=shlwapi.SHFormatDateTimeW")
#pragma comment(linker, "/export:SHFreeShared=shlwapi.SHFreeShared") // XP
#pragma comment(linker, "/export:SHGetInverseCMAP=shlwapi.SHGetInverseCMAP") // XP
#pragma comment(linker, "/export:SHGetThreadRef=shlwapi.SHGetThreadRef") // XP
#pragma comment(linker, "/export:SHGetValueA=shlwapi.SHGetValueA") // XP
#pragma comment(linker, "/export:SHGetValueW=shlwapi.SHGetValueW") // XP
#pragma comment(linker, "/export:SHGetViewStatePropertyBag=shlwapi.SHGetViewStatePropertyBag") // XP
#pragma comment(linker, "/export:SHIsChildOrSelf=shlwapi.SHIsChildOrSelf")
#pragma comment(linker, "/export:SHIsLowMemoryMachine=shlwapi.SHIsLowMemoryMachine") // XP
#pragma comment(linker, "/export:SHLoadIndirectString=shlwapi.SHLoadIndirectString") // XP
#pragma comment(linker, "/export:SHLockShared=shlwapi.SHLockShared") // XP
#pragma comment(linker, "/export:SHMessageBoxCheckA=shlwapi.SHMessageBoxCheckA")
#pragma comment(linker, "/export:SHMessageBoxCheckW=shlwapi.SHMessageBoxCheckW")
#pragma comment(linker, "/export:SHOpenRegStream2A=shlwapi.SHOpenRegStream2A") // XP
#pragma comment(linker, "/export:SHOpenRegStream2W=shlwapi.SHOpenRegStream2W") // XP
#pragma comment(linker, "/export:SHOpenRegStreamA=shlwapi.SHOpenRegStreamA") // XP
#pragma comment(linker, "/export:SHOpenRegStreamW=shlwapi.SHOpenRegStreamW") // XP
#pragma comment(linker, "/export:SHPackDispParamsV=shlwapi.SHPackDispParamsV")
#pragma comment(linker, "/export:SHPinDllOfCLSID=shlwapi.SHPinDllOfCLSID")
#pragma comment(linker, "/export:SHPropertyBag_ReadStrAlloc=shlwapi.SHPropertyBag_ReadStrAlloc")
#pragma comment(linker, "/export:SHPropertyBag_WriteBSTR=shlwapi.SHPropertyBag_WriteBSTR")
#pragma comment(linker, "/export:SHQueryInfoKeyA=shlwapi.SHQueryInfoKeyA") // XP
#pragma comment(linker, "/export:SHQueryInfoKeyW=shlwapi.SHQueryInfoKeyW") // XP
#pragma comment(linker, "/export:SHQueryValueExA=shlwapi.SHQueryValueExA") // XP
#pragma comment(linker, "/export:SHQueryValueExW=shlwapi.SHQueryValueExW") // XP
#pragma comment(linker, "/export:SHRegCloseUSKey=shlwapi.SHRegCloseUSKey") // XP
#pragma comment(linker, "/export:SHRegCreateUSKeyA=shlwapi.SHRegCreateUSKeyA") // XP
#pragma comment(linker, "/export:SHRegCreateUSKeyW=shlwapi.SHRegCreateUSKeyW") // XP
#pragma comment(linker, "/export:SHRegDeleteEmptyUSKeyA=shlwapi.SHRegDeleteEmptyUSKeyA") // XP
#pragma comment(linker, "/export:SHRegDeleteEmptyUSKeyW=shlwapi.SHRegDeleteEmptyUSKeyW") // XP
#pragma comment(linker, "/export:SHRegDeleteUSValueA=shlwapi.SHRegDeleteUSValueA") // XP
#pragma comment(linker, "/export:SHRegDeleteUSValueW=shlwapi.SHRegDeleteUSValueW") // XP
#pragma comment(linker, "/export:SHRegDuplicateHKey=shlwapi.SHRegDuplicateHKey") // XP
#pragma comment(linker, "/export:SHRegEnumUSKeyA=shlwapi.SHRegEnumUSKeyA") // XP
#pragma comment(linker, "/export:SHRegEnumUSKeyW=shlwapi.SHRegEnumUSKeyW") // XP
#pragma comment(linker, "/export:SHRegEnumUSValueA=shlwapi.SHRegEnumUSValueA") // XP
#pragma comment(linker, "/export:SHRegEnumUSValueW=shlwapi.SHRegEnumUSValueW") // XP
#pragma comment(linker, "/export:SHRegGetBoolUSValueA=shlwapi.SHRegGetBoolUSValueA") // XP
#pragma comment(linker, "/export:SHRegGetBoolUSValueW=shlwapi.SHRegGetBoolUSValueW") // XP
#pragma comment(linker, "/export:SHRegGetBoolValueFromHKCUHKLM=shlwapi.SHRegGetBoolValueFromHKCUHKLM")
#pragma comment(linker, "/export:SHRegGetIntW=shlwapi.SHRegGetIntW")
#pragma comment(linker, "/export:SHRegGetPathA=shlwapi.SHRegGetPathA") // XP
#pragma comment(linker, "/export:SHRegGetPathW=shlwapi.SHRegGetPathW") // XP
#pragma comment(linker, "/export:SHRegGetUSValueA=shlwapi.SHRegGetUSValueA") // XP
#pragma comment(linker, "/export:SHRegGetUSValueW=shlwapi.SHRegGetUSValueW") // XP
#pragma comment(linker, "/export:SHRegGetValueA=shlwapi.SHRegGetValueA") // XP
#pragma comment(linker, "/export:SHRegGetValueFromHKCUHKLM=shlwapi.SHRegGetValueFromHKCUHKLM")
#pragma comment(linker, "/export:SHRegGetValueW=shlwapi.SHRegGetValueW") // XP
#pragma comment(linker, "/export:SHRegOpenUSKeyA=shlwapi.SHRegOpenUSKeyA") // XP
#pragma comment(linker, "/export:SHRegOpenUSKeyW=shlwapi.SHRegOpenUSKeyW") // XP
#pragma comment(linker, "/export:SHRegQueryInfoUSKeyA=shlwapi.SHRegQueryInfoUSKeyA") // XP
#pragma comment(linker, "/export:SHRegQueryInfoUSKeyW=shlwapi.SHRegQueryInfoUSKeyW") // XP
#pragma comment(linker, "/export:SHRegQueryUSValueA=shlwapi.SHRegQueryUSValueA") // XP
#pragma comment(linker, "/export:SHRegQueryUSValueW=shlwapi.SHRegQueryUSValueW") // XP
#pragma comment(linker, "/export:SHRegSetPathA=shlwapi.SHRegSetPathA") // XP
#pragma comment(linker, "/export:SHRegSetPathW=shlwapi.SHRegSetPathW") // XP
#pragma comment(linker, "/export:SHRegSetUSValueA=shlwapi.SHRegSetUSValueA") // XP
#pragma comment(linker, "/export:SHRegSetUSValueW=shlwapi.SHRegSetUSValueW") // XP
#pragma comment(linker, "/export:SHRegWriteUSValueA=shlwapi.SHRegWriteUSValueA") // XP
#pragma comment(linker, "/export:SHRegWriteUSValueW=shlwapi.SHRegWriteUSValueW") // XP
#pragma comment(linker, "/export:SHRegisterValidateTemplate=shlwapi.SHRegisterValidateTemplate") // XP
#pragma comment(linker, "/export:SHReleaseThreadRef=shlwapi.SHReleaseThreadRef") // XP
#pragma comment(linker, "/export:SHRunIndirectRegClientCommand=shlwapi.SHRunIndirectRegClientCommand")
#pragma comment(linker, "/export:SHSendMessageBroadcastA=shlwapi.SHSendMessageBroadcastA")
#pragma comment(linker, "/export:SHSendMessageBroadcastW=shlwapi.SHSendMessageBroadcastW")
#pragma comment(linker, "/export:SHSetThreadRef=shlwapi.SHSetThreadRef") // XP
#pragma comment(linker, "/export:SHSetValueA=shlwapi.SHSetValueA") // XP
#pragma comment(linker, "/export:SHSetValueW=shlwapi.SHSetValueW") // XP
#pragma comment(linker, "/export:SHSkipJunction=shlwapi.SHSkipJunction") // XP
#pragma comment(linker, "/export:SHStrDupA=shlwapi.SHStrDupA") // XP
#pragma comment(linker, "/export:SHStrDupW=shlwapi.SHStrDupW") // XP
#pragma comment(linker, "/export:SHStripMneumonicA=shlwapi.SHStripMneumonicA")
#pragma comment(linker, "/export:SHStripMneumonicW=shlwapi.SHStripMneumonicW")
#pragma comment(linker, "/export:SHUnicodeToAnsi=shlwapi.SHUnicodeToAnsi")
#pragma comment(linker, "/export:SHUnicodeToAnsiCP=shlwapi.SHUnicodeToAnsiCP")
#pragma comment(linker, "/export:SHUnicodeToUnicode=shlwapi.SHUnicodeToUnicode")
#pragma comment(linker, "/export:SHUnlockShared=shlwapi.SHUnlockShared") // XP
#pragma comment(linker, "/export:ShellMessageBoxA=shlwapi.ShellMessageBoxA")
#pragma comment(linker, "/export:ShellMessageBoxW=shlwapi.ShellMessageBoxW")
#pragma comment(linker, "/export:StrCSpnA=shlwapi.StrCSpnA") // XP
#pragma comment(linker, "/export:StrCSpnIA=shlwapi.StrCSpnIA") // XP
#pragma comment(linker, "/export:StrCSpnIW=shlwapi.StrCSpnIW") // XP
#pragma comment(linker, "/export:StrCSpnW=shlwapi.StrCSpnW") // XP
#pragma comment(linker, "/export:StrCatBuffA=shlwapi.StrCatBuffA") // XP
#pragma comment(linker, "/export:StrCatBuffW=shlwapi.StrCatBuffW") // XP
#pragma comment(linker, "/export:StrCatChainW=shlwapi.StrCatChainW") // XP
#pragma comment(linker, "/export:StrCatW=shlwapi.StrCatW") // XP
#pragma comment(linker, "/export:StrChrA=shlwapi.StrChrA") // XP
#pragma comment(linker, "/export:StrChrIA=shlwapi.StrChrIA") // XP
#pragma comment(linker, "/export:StrChrIW=shlwapi.StrChrIW") // XP
#pragma comment(linker, "/export:StrChrNIW=shlwapi.StrChrNIW") // XP
#pragma comment(linker, "/export:StrChrNW=shlwapi.StrChrNW") // XP
#pragma comment(linker, "/export:StrChrW=shlwapi.StrChrW") // XP
#pragma comment(linker, "/export:StrCmpCA=shlwapi.StrCmpCA") // XP
#pragma comment(linker, "/export:StrCmpCW=shlwapi.StrCmpCW") // XP
#pragma comment(linker, "/export:StrCmpICA=shlwapi.StrCmpICA") // XP
#pragma comment(linker, "/export:StrCmpICW=shlwapi.StrCmpICW") // XP
#pragma comment(linker, "/export:StrCmpIW=shlwapi.StrCmpIW") // XP
#pragma comment(linker, "/export:StrCmpLogicalW=shlwapi.StrCmpLogicalW") // XP
#pragma comment(linker, "/export:StrCmpNA=shlwapi.StrCmpNA") // XP
#pragma comment(linker, "/export:StrCmpNCA=shlwapi.StrCmpNCA")
#pragma comment(linker, "/export:StrCmpNCW=shlwapi.StrCmpNCW")
#pragma comment(linker, "/export:StrCmpNIA=shlwapi.StrCmpNIA") // XP
#pragma comment(linker, "/export:StrCmpNICA=shlwapi.StrCmpNICA")
#pragma comment(linker, "/export:StrCmpNICW=shlwapi.StrCmpNICW")
#pragma comment(linker, "/export:StrCmpNIW=shlwapi.StrCmpNIW") // XP
#pragma comment(linker, "/export:StrCmpNW=shlwapi.StrCmpNW") // XP
#pragma comment(linker, "/export:StrCmpW=shlwapi.StrCmpW") // XP
#pragma comment(linker, "/export:StrCpyNW=shlwapi.StrCpyNW") // XP
#pragma comment(linker, "/export:StrCpyW=shlwapi.StrCpyW") // XP
#pragma comment(linker, "/export:StrDupA=shlwapi.StrDupA") // XP
#pragma comment(linker, "/export:StrDupW=shlwapi.StrDupW") // XP
#pragma comment(linker, "/export:StrFormatByteSize64A=shlwapi.StrFormatByteSize64A") // XP
#pragma comment(linker, "/export:StrFormatByteSizeA=shlwapi.StrFormatByteSizeA") // XP
#pragma comment(linker, "/export:StrFormatByteSizeEx=shlwapi.StrFormatByteSizeEx")
#pragma comment(linker, "/export:StrFormatByteSizeW=shlwapi.StrFormatByteSizeW") // XP
#pragma comment(linker, "/export:StrFormatKBSizeA=shlwapi.StrFormatKBSizeA") // XP
#pragma comment(linker, "/export:StrFormatKBSizeW=shlwapi.StrFormatKBSizeW") // XP
#pragma comment(linker, "/export:StrFromTimeIntervalA=shlwapi.StrFromTimeIntervalA") // XP
#pragma comment(linker, "/export:StrFromTimeIntervalW=shlwapi.StrFromTimeIntervalW") // XP
#pragma comment(linker, "/export:StrIsIntlEqualA=shlwapi.StrIsIntlEqualA") // XP
#pragma comment(linker, "/export:StrIsIntlEqualW=shlwapi.StrIsIntlEqualW") // XP
#pragma comment(linker, "/export:StrNCatA=shlwapi.StrNCatA") // XP
#pragma comment(linker, "/export:StrNCatW=shlwapi.StrNCatW") // XP
#pragma comment(linker, "/export:StrPBrkA=shlwapi.StrPBrkA") // XP
#pragma comment(linker, "/export:StrPBrkW=shlwapi.StrPBrkW") // XP
#pragma comment(linker, "/export:StrRChrA=shlwapi.StrRChrA") // XP
#pragma comment(linker, "/export:StrRChrIA=shlwapi.StrRChrIA") // XP
#pragma comment(linker, "/export:StrRChrIW=shlwapi.StrRChrIW") // XP
#pragma comment(linker, "/export:StrRChrW=shlwapi.StrRChrW") // XP
#pragma comment(linker, "/export:StrRStrIA=shlwapi.StrRStrIA") // XP
#pragma comment(linker, "/export:StrRStrIW=shlwapi.StrRStrIW") // XP
#pragma comment(linker, "/export:StrRetToBSTR=shlwapi.StrRetToBSTR") // XP
#pragma comment(linker, "/export:StrRetToBufA=shlwapi.StrRetToBufA") // XP
#pragma comment(linker, "/export:StrRetToBufW=shlwapi.StrRetToBufW") // XP
#pragma comment(linker, "/export:StrRetToStrA=shlwapi.StrRetToStrA") // XP
#pragma comment(linker, "/export:StrRetToStrW=shlwapi.StrRetToStrW") // XP
#pragma comment(linker, "/export:StrSpnA=shlwapi.StrSpnA") // XP
#pragma comment(linker, "/export:StrSpnW=shlwapi.StrSpnW") // XP
#pragma comment(linker, "/export:StrStrA=shlwapi.StrStrA") // XP
#pragma comment(linker, "/export:StrStrIA=shlwapi.StrStrIA") // XP
#pragma comment(linker, "/export:StrStrIW=shlwapi.StrStrIW") // XP
#pragma comment(linker, "/export:StrStrNIW=shlwapi.StrStrNIW") // XP
#pragma comment(linker, "/export:StrStrNW=shlwapi.StrStrNW") // XP
#pragma comment(linker, "/export:StrStrW=shlwapi.StrStrW") // XP
#pragma comment(linker, "/export:StrToInt64ExA=shlwapi.StrToInt64ExA") // XP
#pragma comment(linker, "/export:StrToInt64ExW=shlwapi.StrToInt64ExW") // XP
#pragma comment(linker, "/export:StrToIntA=shlwapi.StrToIntA") // XP
#pragma comment(linker, "/export:StrToIntExA=shlwapi.StrToIntExA") // XP
#pragma comment(linker, "/export:StrToIntExW=shlwapi.StrToIntExW") // XP
#pragma comment(linker, "/export:StrToIntW=shlwapi.StrToIntW") // XP
#pragma comment(linker, "/export:StrTrimA=shlwapi.StrTrimA") // XP
#pragma comment(linker, "/export:StrTrimW=shlwapi.StrTrimW") // XP
#pragma comment(linker, "/export:UrlApplySchemeA=shlwapi.UrlApplySchemeA") // XP
#pragma comment(linker, "/export:UrlApplySchemeW=shlwapi.UrlApplySchemeW") // XP
#pragma comment(linker, "/export:UrlCanonicalizeA=shlwapi.UrlCanonicalizeA") // XP
#pragma comment(linker, "/export:UrlCanonicalizeW=shlwapi.UrlCanonicalizeW") // XP
#pragma comment(linker, "/export:UrlCombineA=shlwapi.UrlCombineA") // XP
#pragma comment(linker, "/export:UrlCombineW=shlwapi.UrlCombineW") // XP
#pragma comment(linker, "/export:UrlCompareA=shlwapi.UrlCompareA") // XP
#pragma comment(linker, "/export:UrlCompareW=shlwapi.UrlCompareW") // XP
#pragma comment(linker, "/export:UrlCreateFromPathA=shlwapi.UrlCreateFromPathA") // XP
#pragma comment(linker, "/export:UrlCreateFromPathW=shlwapi.UrlCreateFromPathW") // XP
#pragma comment(linker, "/export:UrlEscapeA=shlwapi.UrlEscapeA") // XP
#pragma comment(linker, "/export:UrlEscapeW=shlwapi.UrlEscapeW") // XP
#pragma comment(linker, "/export:UrlFixupW=shlwapi.UrlFixupW")
#pragma comment(linker, "/export:UrlGetLocationA=shlwapi.UrlGetLocationA") // XP
#pragma comment(linker, "/export:UrlGetLocationW=shlwapi.UrlGetLocationW") // XP
#pragma comment(linker, "/export:UrlGetPartA=shlwapi.UrlGetPartA") // XP
#pragma comment(linker, "/export:UrlGetPartW=shlwapi.UrlGetPartW") // XP
#pragma comment(linker, "/export:UrlHashA=shlwapi.UrlHashA") // XP
#pragma comment(linker, "/export:UrlHashW=shlwapi.UrlHashW") // XP
#pragma comment(linker, "/export:UrlIsA=shlwapi.UrlIsA") // XP
#pragma comment(linker, "/export:UrlIsNoHistoryA=shlwapi.UrlIsNoHistoryA") // XP
#pragma comment(linker, "/export:UrlIsNoHistoryW=shlwapi.UrlIsNoHistoryW") // XP
#pragma comment(linker, "/export:UrlIsOpaqueA=shlwapi.UrlIsOpaqueA") // XP
#pragma comment(linker, "/export:UrlIsOpaqueW=shlwapi.UrlIsOpaqueW") // XP
#pragma comment(linker, "/export:UrlIsW=shlwapi.UrlIsW") // XP
#pragma comment(linker, "/export:UrlUnescapeA=shlwapi.UrlUnescapeA") // XP
#pragma comment(linker, "/export:UrlUnescapeW=shlwapi.UrlUnescapeW") // XP
#pragma comment(linker, "/export:WhichPlatform=shlwapi.WhichPlatform")
#pragma comment(linker, "/export:wnsprintfA=shlwapi.wnsprintfA") // XP
#pragma comment(linker, "/export:wnsprintfW=shlwapi.wnsprintfW") // XP
#pragma comment(linker, "/export:wvnsprintfA=shlwapi.wvnsprintfA") // XP
#pragma comment(linker, "/export:wvnsprintfW=shlwapi.wvnsprintfW") // XP
