#include <WinDef.h>

#pragma comment(linker, "/export:ActivateKeyboardLayout=user32.ActivateKeyboardLayout") // XP
#pragma comment(linker, "/export:AddClipboardFormatListener=user32.AddClipboardFormatListener")
#pragma comment(linker, "/export:AdjustWindowRect=user32.AdjustWindowRect") // XP
#pragma comment(linker, "/export:AdjustWindowRectEx=user32.AdjustWindowRectEx") // XP
#pragma comment(linker, "/export:AdjustWindowRectExForDpi=user32.AdjustWindowRectExForDpi")
#pragma comment(linker, "/export:AlignRects=user32.AlignRects") // XP
#pragma comment(linker, "/export:AllowForegroundActivation=user32.AllowForegroundActivation") // XP
#pragma comment(linker, "/export:AllowSetForegroundWindow=user32.AllowSetForegroundWindow") // XP
#pragma comment(linker, "/export:AnimateWindow=user32.AnimateWindow") // XP
#pragma comment(linker, "/export:AnyPopup=user32.AnyPopup") // XP
#pragma comment(linker, "/export:AppendMenuA=user32.AppendMenuA") // XP
#pragma comment(linker, "/export:AppendMenuW=user32.AppendMenuW") // XP
#pragma comment(linker, "/export:AreDpiAwarenessContextsEqual=user32.AreDpiAwarenessContextsEqual")
#pragma comment(linker, "/export:ArrangeIconicWindows=user32.ArrangeIconicWindows") // XP
#pragma comment(linker, "/export:AttachThreadInput=user32.AttachThreadInput") // XP
#pragma comment(linker, "/export:BeginDeferWindowPos=user32.BeginDeferWindowPos") // XP
#pragma comment(linker, "/export:BeginPaint=user32.BeginPaint") // XP
#pragma comment(linker, "/export:BlockInput=user32.BlockInput") // XP
#pragma comment(linker, "/export:BringWindowToTop=user32.BringWindowToTop") // XP
#pragma comment(linker, "/export:BroadcastSystemMessage=user32.BroadcastSystemMessage") // XP
#pragma comment(linker, "/export:BroadcastSystemMessageA=user32.BroadcastSystemMessageA") // XP
#pragma comment(linker, "/export:BroadcastSystemMessageExA=user32.BroadcastSystemMessageExA") // XP
#pragma comment(linker, "/export:BroadcastSystemMessageExW=user32.BroadcastSystemMessageExW") // XP
#pragma comment(linker, "/export:BroadcastSystemMessageW=user32.BroadcastSystemMessageW") // XP
#pragma comment(linker, "/export:BuildReasonArray=user32.BuildReasonArray") // XP
#pragma comment(linker, "/export:CalcMenuBar=user32.CalcMenuBar") // XP
#pragma comment(linker, "/export:CalculatePopupWindowPosition=user32.CalculatePopupWindowPosition")
#pragma comment(linker, "/export:CallMsgFilter=user32.CallMsgFilter") // XP
#pragma comment(linker, "/export:CallMsgFilterA=user32.CallMsgFilterA") // XP
#pragma comment(linker, "/export:CallMsgFilterW=user32.CallMsgFilterW") // XP
#pragma comment(linker, "/export:CallNextHookEx=user32.CallNextHookEx") // XP
#pragma comment(linker, "/export:CallWindowProcA=user32.CallWindowProcA") // XP
#pragma comment(linker, "/export:CallWindowProcW=user32.CallWindowProcW") // XP
#pragma comment(linker, "/export:CancelShutdown=user32.CancelShutdown")
#pragma comment(linker, "/export:CascadeChildWindows=user32.CascadeChildWindows") // XP
#pragma comment(linker, "/export:CascadeWindows=user32.CascadeWindows") // XP
#pragma comment(linker, "/export:ChangeClipboardChain=user32.ChangeClipboardChain") // XP
#pragma comment(linker, "/export:ChangeDisplaySettingsA=user32.ChangeDisplaySettingsA") // XP
#pragma comment(linker, "/export:ChangeDisplaySettingsExA=user32.ChangeDisplaySettingsExA") // XP
#pragma comment(linker, "/export:ChangeDisplaySettingsExW=user32.ChangeDisplaySettingsExW") // XP
#pragma comment(linker, "/export:ChangeDisplaySettingsW=user32.ChangeDisplaySettingsW") // XP
#pragma comment(linker, "/export:ChangeMenuA=user32.ChangeMenuA") // XP
#pragma comment(linker, "/export:ChangeMenuW=user32.ChangeMenuW") // XP
#pragma comment(linker, "/export:ChangeWindowMessageFilter=user32.ChangeWindowMessageFilter")
#pragma comment(linker, "/export:ChangeWindowMessageFilterEx=user32.ChangeWindowMessageFilterEx")
#pragma comment(linker, "/export:CharLowerA=user32.CharLowerA") // XP
#pragma comment(linker, "/export:CharLowerBuffA=user32.CharLowerBuffA") // XP
#pragma comment(linker, "/export:CharLowerBuffW=user32.CharLowerBuffW") // XP
#pragma comment(linker, "/export:CharLowerW=user32.CharLowerW") // XP
#pragma comment(linker, "/export:CharNextA=user32.CharNextA") // XP
#pragma comment(linker, "/export:CharNextExA=user32.CharNextExA") // XP
#pragma comment(linker, "/export:CharNextW=user32.CharNextW") // XP
#pragma comment(linker, "/export:CharPrevA=user32.CharPrevA") // XP
#pragma comment(linker, "/export:CharPrevExA=user32.CharPrevExA") // XP
#pragma comment(linker, "/export:CharPrevW=user32.CharPrevW") // XP
#pragma comment(linker, "/export:CharToOemA=user32.CharToOemA") // XP
#pragma comment(linker, "/export:CharToOemBuffA=user32.CharToOemBuffA") // XP
#pragma comment(linker, "/export:CharToOemBuffW=user32.CharToOemBuffW") // XP
#pragma comment(linker, "/export:CharToOemW=user32.CharToOemW") // XP
#pragma comment(linker, "/export:CharUpperA=user32.CharUpperA") // XP
#pragma comment(linker, "/export:CharUpperBuffA=user32.CharUpperBuffA") // XP
#pragma comment(linker, "/export:CharUpperBuffW=user32.CharUpperBuffW") // XP
#pragma comment(linker, "/export:CharUpperW=user32.CharUpperW") // XP
#pragma comment(linker, "/export:CheckDBCSEnabledExt=user32.CheckDBCSEnabledExt")
#pragma comment(linker, "/export:CheckDlgButton=user32.CheckDlgButton") // XP
#pragma comment(linker, "/export:CheckMenuItem=user32.CheckMenuItem") // XP
#pragma comment(linker, "/export:CheckMenuRadioItem=user32.CheckMenuRadioItem") // XP
#pragma comment(linker, "/export:CheckProcessForClipboardAccess=user32.CheckProcessForClipboardAccess")
#pragma comment(linker, "/export:CheckProcessSession=user32.CheckProcessSession")
#pragma comment(linker, "/export:CheckRadioButton=user32.CheckRadioButton") // XP
#pragma comment(linker, "/export:CheckWindowThreadDesktop=user32.CheckWindowThreadDesktop")
#pragma comment(linker, "/export:ChildWindowFromPoint=user32.ChildWindowFromPoint") // XP
#pragma comment(linker, "/export:ChildWindowFromPointEx=user32.ChildWindowFromPointEx") // XP
#pragma comment(linker, "/export:CliImmSetHotKey=user32.CliImmSetHotKey") // XP
#pragma comment(linker, "/export:ClientThreadSetup=user32.ClientThreadSetup") // XP
#pragma comment(linker, "/export:ClientToScreen=user32.ClientToScreen") // XP
#pragma comment(linker, "/export:ClipCursor=user32.ClipCursor") // XP
#pragma comment(linker, "/export:CloseClipboard=user32.CloseClipboard") // XP
#pragma comment(linker, "/export:CloseDesktop=user32.CloseDesktop") // XP
#pragma comment(linker, "/export:CloseGestureInfoHandle=user32.CloseGestureInfoHandle")
#pragma comment(linker, "/export:CloseTouchInputHandle=user32.CloseTouchInputHandle")
#pragma comment(linker, "/export:CloseWindow=user32.CloseWindow") // XP
#pragma comment(linker, "/export:CloseWindowStation=user32.CloseWindowStation") // XP
#pragma comment(linker, "/export:ConsoleControl=user32.ConsoleControl")
#pragma comment(linker, "/export:ControlMagnification=user32.ControlMagnification")
#pragma comment(linker, "/export:CopyAcceleratorTableA=user32.CopyAcceleratorTableA") // XP
#pragma comment(linker, "/export:CopyAcceleratorTableW=user32.CopyAcceleratorTableW") // XP
#pragma comment(linker, "/export:CopyIcon=user32.CopyIcon") // XP
#pragma comment(linker, "/export:CopyImage=user32.CopyImage") // XP
#pragma comment(linker, "/export:CopyRect=user32.CopyRect") // XP
#pragma comment(linker, "/export:CountClipboardFormats=user32.CountClipboardFormats") // XP
#pragma comment(linker, "/export:CreateAcceleratorTableA=user32.CreateAcceleratorTableA") // XP
#pragma comment(linker, "/export:CreateAcceleratorTableW=user32.CreateAcceleratorTableW") // XP
#pragma comment(linker, "/export:CreateCaret=user32.CreateCaret") // XP
#pragma comment(linker, "/export:CreateCursor=user32.CreateCursor") // XP
#pragma comment(linker, "/export:CreateDCompositionHwndTarget=user32.CreateDCompositionHwndTarget")
#pragma comment(linker, "/export:CreateDesktopA=user32.CreateDesktopA") // XP
#pragma comment(linker, "/export:CreateDesktopExA=user32.CreateDesktopExA")
#pragma comment(linker, "/export:CreateDesktopExW=user32.CreateDesktopExW")
#pragma comment(linker, "/export:CreateDesktopW=user32.CreateDesktopW") // XP
#pragma comment(linker, "/export:CreateDialogIndirectParamA=user32.CreateDialogIndirectParamA") // XP
#pragma comment(linker, "/export:CreateDialogIndirectParamAorW=user32.CreateDialogIndirectParamAorW") // XP
#pragma comment(linker, "/export:CreateDialogIndirectParamW=user32.CreateDialogIndirectParamW") // XP
#pragma comment(linker, "/export:CreateDialogParamA=user32.CreateDialogParamA") // XP
#pragma comment(linker, "/export:CreateDialogParamW=user32.CreateDialogParamW") // XP
#pragma comment(linker, "/export:CreateIcon=user32.CreateIcon") // XP
#pragma comment(linker, "/export:CreateIconFromResource=user32.CreateIconFromResource") // XP
#pragma comment(linker, "/export:CreateIconFromResourceEx=user32.CreateIconFromResourceEx") // XP
#pragma comment(linker, "/export:CreateIconIndirect=user32.CreateIconIndirect") // XP
#pragma comment(linker, "/export:CreateMDIWindowA=user32.CreateMDIWindowA") // XP
#pragma comment(linker, "/export:CreateMDIWindowW=user32.CreateMDIWindowW") // XP
#pragma comment(linker, "/export:CreateMenu=user32.CreateMenu") // XP
#pragma comment(linker, "/export:CreatePopupMenu=user32.CreatePopupMenu") // XP
#pragma comment(linker, "/export:CreateSystemThreads=user32.CreateSystemThreads") // XP
#pragma comment(linker, "/export:CreateWindowExA=user32.CreateWindowExA") // XP
#pragma comment(linker, "/export:CreateWindowExW=user32.CreateWindowExW") // XP
#pragma comment(linker, "/export:CreateWindowInBand=user32.CreateWindowInBand")
#pragma comment(linker, "/export:CreateWindowInBandEx=user32.CreateWindowInBandEx")
#pragma comment(linker, "/export:CreateWindowIndirect=user32.CreateWindowIndirect")
#pragma comment(linker, "/export:CreateWindowStationA=user32.CreateWindowStationA") // XP
#pragma comment(linker, "/export:CreateWindowStationW=user32.CreateWindowStationW") // XP
#pragma comment(linker, "/export:CsrBroadcastSystemMessageExW=user32.CsrBroadcastSystemMessageExW") // XP
#pragma comment(linker, "/export:CtxInitUser32=user32.CtxInitUser32") // XP
#pragma comment(linker, "/export:DdeAbandonTransaction=user32.DdeAbandonTransaction") // XP
#pragma comment(linker, "/export:DdeAccessData=user32.DdeAccessData") // XP
#pragma comment(linker, "/export:DdeAddData=user32.DdeAddData") // XP
#pragma comment(linker, "/export:DdeClientTransaction=user32.DdeClientTransaction") // XP
#pragma comment(linker, "/export:DdeCmpStringHandles=user32.DdeCmpStringHandles") // XP
#pragma comment(linker, "/export:DdeConnect=user32.DdeConnect") // XP
#pragma comment(linker, "/export:DdeConnectList=user32.DdeConnectList") // XP
#pragma comment(linker, "/export:DdeCreateDataHandle=user32.DdeCreateDataHandle") // XP
#pragma comment(linker, "/export:DdeCreateStringHandleA=user32.DdeCreateStringHandleA") // XP
#pragma comment(linker, "/export:DdeCreateStringHandleW=user32.DdeCreateStringHandleW") // XP
#pragma comment(linker, "/export:DdeDisconnect=user32.DdeDisconnect") // XP
#pragma comment(linker, "/export:DdeDisconnectList=user32.DdeDisconnectList") // XP
#pragma comment(linker, "/export:DdeEnableCallback=user32.DdeEnableCallback") // XP
#pragma comment(linker, "/export:DdeFreeDataHandle=user32.DdeFreeDataHandle") // XP
#pragma comment(linker, "/export:DdeFreeStringHandle=user32.DdeFreeStringHandle") // XP
#pragma comment(linker, "/export:DdeGetData=user32.DdeGetData") // XP
#pragma comment(linker, "/export:DdeGetLastError=user32.DdeGetLastError") // XP
#pragma comment(linker, "/export:DdeGetQualityOfService=user32.DdeGetQualityOfService") // XP
#pragma comment(linker, "/export:DdeImpersonateClient=user32.DdeImpersonateClient") // XP
#pragma comment(linker, "/export:DdeInitializeA=user32.DdeInitializeA") // XP
#pragma comment(linker, "/export:DdeInitializeW=user32.DdeInitializeW") // XP
#pragma comment(linker, "/export:DdeKeepStringHandle=user32.DdeKeepStringHandle") // XP
#pragma comment(linker, "/export:DdeNameService=user32.DdeNameService") // XP
#pragma comment(linker, "/export:DdePostAdvise=user32.DdePostAdvise") // XP
#pragma comment(linker, "/export:DdeQueryConvInfo=user32.DdeQueryConvInfo") // XP
#pragma comment(linker, "/export:DdeQueryNextServer=user32.DdeQueryNextServer") // XP
#pragma comment(linker, "/export:DdeQueryStringA=user32.DdeQueryStringA") // XP
#pragma comment(linker, "/export:DdeQueryStringW=user32.DdeQueryStringW") // XP
#pragma comment(linker, "/export:DdeReconnect=user32.DdeReconnect") // XP
#pragma comment(linker, "/export:DdeSetQualityOfService=user32.DdeSetQualityOfService") // XP
#pragma comment(linker, "/export:DdeSetUserHandle=user32.DdeSetUserHandle") // XP
#pragma comment(linker, "/export:DdeUnaccessData=user32.DdeUnaccessData") // XP
#pragma comment(linker, "/export:DdeUninitialize=user32.DdeUninitialize") // XP
#pragma comment(linker, "/export:DefDlgProcA=user32.DefDlgProcA") // XP
#pragma comment(linker, "/export:DefDlgProcW=user32.DefDlgProcW") // XP
#pragma comment(linker, "/export:DefFrameProcA=user32.DefFrameProcA") // XP
#pragma comment(linker, "/export:DefFrameProcW=user32.DefFrameProcW") // XP
#pragma comment(linker, "/export:DefMDIChildProcA=user32.DefMDIChildProcA") // XP
#pragma comment(linker, "/export:DefMDIChildProcW=user32.DefMDIChildProcW") // XP
#pragma comment(linker, "/export:DefRawInputProc=user32.DefRawInputProc") // XP
#pragma comment(linker, "/export:DefWindowProcA=user32.DefWindowProcA") // XP
#pragma comment(linker, "/export:DefWindowProcW=user32.DefWindowProcW") // XP
#pragma comment(linker, "/export:DeferWindowPos=user32.DeferWindowPos") // XP
#pragma comment(linker, "/export:DeferWindowPosAndBand=user32.DeferWindowPosAndBand")
#pragma comment(linker, "/export:DeleteMenu=user32.DeleteMenu") // XP
#pragma comment(linker, "/export:DeregisterShellHookWindow=user32.DeregisterShellHookWindow") // XP
#pragma comment(linker, "/export:DestroyAcceleratorTable=user32.DestroyAcceleratorTable") // XP
#pragma comment(linker, "/export:DestroyCaret=user32.DestroyCaret") // XP
#pragma comment(linker, "/export:DestroyCursor=user32.DestroyCursor") // XP
#pragma comment(linker, "/export:DestroyDCompositionHwndTarget=user32.DestroyDCompositionHwndTarget")
#pragma comment(linker, "/export:DestroyIcon=user32.DestroyIcon") // XP
#pragma comment(linker, "/export:DestroyMenu=user32.DestroyMenu") // XP
#pragma comment(linker, "/export:DestroyReasons=user32.DestroyReasons") // XP
#pragma comment(linker, "/export:DestroyWindow=user32.DestroyWindow") // XP
#pragma comment(linker, "/export:DialogBoxIndirectParamA=user32.DialogBoxIndirectParamA") // XP
#pragma comment(linker, "/export:DialogBoxIndirectParamAorW=user32.DialogBoxIndirectParamAorW") // XP
#pragma comment(linker, "/export:DialogBoxIndirectParamW=user32.DialogBoxIndirectParamW") // XP
#pragma comment(linker, "/export:DialogBoxParamA=user32.DialogBoxParamA") // XP
#pragma comment(linker, "/export:DialogBoxParamW=user32.DialogBoxParamW") // XP
#pragma comment(linker, "/export:DisableProcessWindowsGhosting=user32.DisableProcessWindowsGhosting") // XP
#pragma comment(linker, "/export:DispatchMessageA=user32.DispatchMessageA") // XP
#pragma comment(linker, "/export:DispatchMessageW=user32.DispatchMessageW") // XP
#pragma comment(linker, "/export:DisplayConfigGetDeviceInfo=user32.DisplayConfigGetDeviceInfo")
#pragma comment(linker, "/export:DisplayConfigSetDeviceInfo=user32.DisplayConfigSetDeviceInfo")
#pragma comment(linker, "/export:DisplayExitWindowsWarnings=user32.DisplayExitWindowsWarnings") // XP
#pragma comment(linker, "/export:DlgDirListA=user32.DlgDirListA") // XP
#pragma comment(linker, "/export:DlgDirListComboBoxA=user32.DlgDirListComboBoxA") // XP
#pragma comment(linker, "/export:DlgDirListComboBoxW=user32.DlgDirListComboBoxW") // XP
#pragma comment(linker, "/export:DlgDirListW=user32.DlgDirListW") // XP
#pragma comment(linker, "/export:DlgDirSelectComboBoxExA=user32.DlgDirSelectComboBoxExA") // XP
#pragma comment(linker, "/export:DlgDirSelectComboBoxExW=user32.DlgDirSelectComboBoxExW") // XP
#pragma comment(linker, "/export:DlgDirSelectExA=user32.DlgDirSelectExA") // XP
#pragma comment(linker, "/export:DlgDirSelectExW=user32.DlgDirSelectExW") // XP
#pragma comment(linker, "/export:DoSoundConnect=user32.DoSoundConnect")
#pragma comment(linker, "/export:DoSoundDisconnect=user32.DoSoundDisconnect")
#pragma comment(linker, "/export:DragDetect=user32.DragDetect") // XP
#pragma comment(linker, "/export:DragObject=user32.DragObject") // XP
#pragma comment(linker, "/export:DrawAnimatedRects=user32.DrawAnimatedRects") // XP
#pragma comment(linker, "/export:DrawCaption=user32.DrawCaption") // XP
#pragma comment(linker, "/export:DrawCaptionTempA=user32.DrawCaptionTempA") // XP
#pragma comment(linker, "/export:DrawCaptionTempW=user32.DrawCaptionTempW") // XP
#pragma comment(linker, "/export:DrawEdge=user32.DrawEdge") // XP
#pragma comment(linker, "/export:DrawFocusRect=user32.DrawFocusRect") // XP
#pragma comment(linker, "/export:DrawFrame=user32.DrawFrame") // XP
#pragma comment(linker, "/export:DrawFrameControl=user32.DrawFrameControl") // XP
#pragma comment(linker, "/export:DrawIcon=user32.DrawIcon") // XP
#pragma comment(linker, "/export:DrawIconEx=user32.DrawIconEx") // XP
#pragma comment(linker, "/export:DrawMenuBar=user32.DrawMenuBar") // XP
#pragma comment(linker, "/export:DrawMenuBarTemp=user32.DrawMenuBarTemp") // XP
#pragma comment(linker, "/export:DrawStateA=user32.DrawStateA") // XP
#pragma comment(linker, "/export:DrawStateW=user32.DrawStateW") // XP
#pragma comment(linker, "/export:DrawTextA=user32.DrawTextA") // XP
#pragma comment(linker, "/export:DrawTextExA=user32.DrawTextExA") // XP
#pragma comment(linker, "/export:DrawTextExW=user32.DrawTextExW") // XP
#pragma comment(linker, "/export:DrawTextW=user32.DrawTextW") // XP
#pragma comment(linker, "/export:DwmGetDxSharedSurface=user32.DwmGetDxSharedSurface")
#pragma comment(linker, "/export:DwmGetRemoteSessionOcclusionEvent=user32.DwmGetRemoteSessionOcclusionEvent")
#pragma comment(linker, "/export:DwmGetRemoteSessionOcclusionState=user32.DwmGetRemoteSessionOcclusionState")
#pragma comment(linker, "/export:DwmKernelShutdown=user32.DwmKernelShutdown")
#pragma comment(linker, "/export:DwmKernelStartup=user32.DwmKernelStartup")
#pragma comment(linker, "/export:DwmLockScreenUpdates=user32.DwmLockScreenUpdates")
#pragma comment(linker, "/export:DwmValidateWindow=user32.DwmValidateWindow")
#pragma comment(linker, "/export:EditWndProc=user32.EditWndProc") // XP
#pragma comment(linker, "/export:EmptyClipboard=user32.EmptyClipboard") // XP
#pragma comment(linker, "/export:EnableMenuItem=user32.EnableMenuItem") // XP
#pragma comment(linker, "/export:EnableMouseInPointer=user32.EnableMouseInPointer")
#pragma comment(linker, "/export:EnableNonClientDpiScaling=user32.EnableNonClientDpiScaling")
#pragma comment(linker, "/export:EnableScrollBar=user32.EnableScrollBar") // XP
#pragma comment(linker, "/export:EnableSessionForMMCSS=user32.EnableSessionForMMCSS")
#pragma comment(linker, "/export:EnableWindow=user32.EnableWindow") // XP
#pragma comment(linker, "/export:EndDeferWindowPos=user32.EndDeferWindowPos") // XP
#pragma comment(linker, "/export:EndDeferWindowPosEx=user32.EndDeferWindowPosEx")
#pragma comment(linker, "/export:EndDialog=user32.EndDialog") // XP
#pragma comment(linker, "/export:EndMenu=user32.EndMenu") // XP
#pragma comment(linker, "/export:EndPaint=user32.EndPaint") // XP
#pragma comment(linker, "/export:EndTask=user32.EndTask") // XP
#pragma comment(linker, "/export:EnterReaderModeHelper=user32.EnterReaderModeHelper") // XP
#pragma comment(linker, "/export:EnumChildWindows=user32.EnumChildWindows") // XP
#pragma comment(linker, "/export:EnumClipboardFormats=user32.EnumClipboardFormats") // XP
#pragma comment(linker, "/export:EnumDesktopWindows=user32.EnumDesktopWindows") // XP
#pragma comment(linker, "/export:EnumDesktopsA=user32.EnumDesktopsA") // XP
#pragma comment(linker, "/export:EnumDesktopsW=user32.EnumDesktopsW") // XP
#pragma comment(linker, "/export:EnumDisplayDevicesA=user32.EnumDisplayDevicesA") // XP
#pragma comment(linker, "/export:EnumDisplayDevicesW=user32.EnumDisplayDevicesW") // XP
#pragma comment(linker, "/export:EnumDisplayMonitors=user32.EnumDisplayMonitors") // XP
#pragma comment(linker, "/export:EnumDisplaySettingsA=user32.EnumDisplaySettingsA") // XP
#pragma comment(linker, "/export:EnumDisplaySettingsExA=user32.EnumDisplaySettingsExA") // XP
#pragma comment(linker, "/export:EnumDisplaySettingsExW=user32.EnumDisplaySettingsExW") // XP
#pragma comment(linker, "/export:EnumDisplaySettingsW=user32.EnumDisplaySettingsW") // XP
#pragma comment(linker, "/export:EnumPropsA=user32.EnumPropsA") // XP
#pragma comment(linker, "/export:EnumPropsExA=user32.EnumPropsExA") // XP
#pragma comment(linker, "/export:EnumPropsExW=user32.EnumPropsExW") // XP
#pragma comment(linker, "/export:EnumPropsW=user32.EnumPropsW") // XP
#pragma comment(linker, "/export:EnumThreadWindows=user32.EnumThreadWindows") // XP
#pragma comment(linker, "/export:EnumWindowStationsA=user32.EnumWindowStationsA") // XP
#pragma comment(linker, "/export:EnumWindowStationsW=user32.EnumWindowStationsW") // XP
#pragma comment(linker, "/export:EnumWindows=user32.EnumWindows") // XP
#pragma comment(linker, "/export:EqualRect=user32.EqualRect") // XP
#pragma comment(linker, "/export:EvaluateProximityToPolygon=user32.EvaluateProximityToPolygon")
#pragma comment(linker, "/export:EvaluateProximityToRect=user32.EvaluateProximityToRect")
#pragma comment(linker, "/export:ExcludeUpdateRgn=user32.ExcludeUpdateRgn") // XP
#pragma comment(linker, "/export:ExitWindowsEx=user32.ExitWindowsEx") // XP
#pragma comment(linker, "/export:FillRect=user32.FillRect") // XP
#pragma comment(linker, "/export:FindWindowA=user32.FindWindowA") // XP
#pragma comment(linker, "/export:FindWindowExA=user32.FindWindowExA") // XP
#pragma comment(linker, "/export:FindWindowExW=user32.FindWindowExW") // XP
#pragma comment(linker, "/export:FindWindowW=user32.FindWindowW") // XP
#pragma comment(linker, "/export:FlashWindow=user32.FlashWindow") // XP
#pragma comment(linker, "/export:FlashWindowEx=user32.FlashWindowEx") // XP
#pragma comment(linker, "/export:FrameRect=user32.FrameRect") // XP
#pragma comment(linker, "/export:FreeDDElParam=user32.FreeDDElParam") // XP
#pragma comment(linker, "/export:FrostCrashedWindow=user32.FrostCrashedWindow")
#pragma comment(linker, "/export:GetActiveWindow=user32.GetActiveWindow") // XP
#pragma comment(linker, "/export:GetAltTabInfo=user32.GetAltTabInfo") // XP
#pragma comment(linker, "/export:GetAltTabInfoA=user32.GetAltTabInfoA") // XP
#pragma comment(linker, "/export:GetAltTabInfoW=user32.GetAltTabInfoW") // XP
#pragma comment(linker, "/export:GetAncestor=user32.GetAncestor") // XP
#pragma comment(linker, "/export:GetAppCompatFlags=user32.GetAppCompatFlags") // XP
#pragma comment(linker, "/export:GetAppCompatFlags2=user32.GetAppCompatFlags2") // XP
#pragma comment(linker, "/export:GetAsyncKeyState=user32.GetAsyncKeyState") // XP
#pragma comment(linker, "/export:GetAutoRotationState=user32.GetAutoRotationState")
#pragma comment(linker, "/export:GetAwarenessFromDpiAwarenessContext=user32.GetAwarenessFromDpiAwarenessContext")
#pragma comment(linker, "/export:GetCIMSSM=user32.GetCIMSSM")
#pragma comment(linker, "/export:GetCapture=user32.GetCapture") // XP
#pragma comment(linker, "/export:GetCaretBlinkTime=user32.GetCaretBlinkTime") // XP
#pragma comment(linker, "/export:GetCaretPos=user32.GetCaretPos") // XP
#pragma comment(linker, "/export:GetClassInfoA=user32.GetClassInfoA") // XP
#pragma comment(linker, "/export:GetClassInfoExA=user32.GetClassInfoExA") // XP
#pragma comment(linker, "/export:GetClassInfoExW=user32.GetClassInfoExW") // XP
#pragma comment(linker, "/export:GetClassInfoW=user32.GetClassInfoW") // XP
#pragma comment(linker, "/export:GetClassLongA=user32.GetClassLongA") // XP
#pragma comment(linker, "/export:GetClassLongW=user32.GetClassLongW") // XP
#pragma comment(linker, "/export:GetClassNameA=user32.GetClassNameA") // XP
#pragma comment(linker, "/export:GetClassNameW=user32.GetClassNameW") // XP
#pragma comment(linker, "/export:GetClassWord=user32.GetClassWord") // XP
#pragma comment(linker, "/export:GetClientRect=user32.GetClientRect") // XP
#pragma comment(linker, "/export:GetClipCursor=user32.GetClipCursor") // XP
#pragma comment(linker, "/export:GetClipboardAccessToken=user32.GetClipboardAccessToken")
#pragma comment(linker, "/export:GetClipboardData=user32.GetClipboardData") // XP
#pragma comment(linker, "/export:GetClipboardFormatNameA=user32.GetClipboardFormatNameA") // XP
#pragma comment(linker, "/export:GetClipboardFormatNameW=user32.GetClipboardFormatNameW") // XP
#pragma comment(linker, "/export:GetClipboardOwner=user32.GetClipboardOwner") // XP
#pragma comment(linker, "/export:GetClipboardSequenceNumber=user32.GetClipboardSequenceNumber") // XP
#pragma comment(linker, "/export:GetClipboardViewer=user32.GetClipboardViewer") // XP
#pragma comment(linker, "/export:GetComboBoxInfo=user32.GetComboBoxInfo") // XP
#pragma comment(linker, "/export:GetCurrentInputMessageSource=user32.GetCurrentInputMessageSource")
#pragma comment(linker, "/export:GetCursor=user32.GetCursor") // XP
#pragma comment(linker, "/export:GetCursorFrameInfo=user32.GetCursorFrameInfo") // XP
#pragma comment(linker, "/export:GetCursorInfo=user32.GetCursorInfo") // XP
#pragma comment(linker, "/export:GetCursorPos=user32.GetCursorPos") // XP
#pragma comment(linker, "/export:GetDC=user32.GetDC") // XP
#pragma comment(linker, "/export:GetDCEx=user32.GetDCEx") // XP
#pragma comment(linker, "/export:GetDesktopID=user32.GetDesktopID")
#pragma comment(linker, "/export:GetDesktopWindow=user32.GetDesktopWindow") // XP
#pragma comment(linker, "/export:GetDialogBaseUnits=user32.GetDialogBaseUnits") // XP
#pragma comment(linker, "/export:GetDisplayAutoRotationPreferences=user32.GetDisplayAutoRotationPreferences")
#pragma comment(linker, "/export:GetDisplayConfigBufferSizes=user32.GetDisplayConfigBufferSizes")
#pragma comment(linker, "/export:GetDlgCtrlID=user32.GetDlgCtrlID") // XP
#pragma comment(linker, "/export:GetDlgItem=user32.GetDlgItem") // XP
#pragma comment(linker, "/export:GetDlgItemInt=user32.GetDlgItemInt") // XP
#pragma comment(linker, "/export:GetDlgItemTextA=user32.GetDlgItemTextA") // XP
#pragma comment(linker, "/export:GetDlgItemTextW=user32.GetDlgItemTextW") // XP
#pragma comment(linker, "/export:GetDoubleClickTime=user32.GetDoubleClickTime") // XP
#pragma comment(linker, "/export:GetDpiForMonitorInternal=user32.GetDpiForMonitorInternal")
#pragma comment(linker, "/export:GetDpiForSystem=user32.GetDpiForSystem")
#pragma comment(linker, "/export:GetDpiForWindow=user32.GetDpiForWindow")
#pragma comment(linker, "/export:GetFocus=user32.GetFocus") // XP
#pragma comment(linker, "/export:GetForegroundWindow=user32.GetForegroundWindow") // XP
#pragma comment(linker, "/export:GetGUIThreadInfo=user32.GetGUIThreadInfo") // XP
#pragma comment(linker, "/export:GetGestureConfig=user32.GetGestureConfig")
#pragma comment(linker, "/export:GetGestureExtraArgs=user32.GetGestureExtraArgs")
#pragma comment(linker, "/export:GetGestureInfo=user32.GetGestureInfo")
#pragma comment(linker, "/export:GetGuiResources=user32.GetGuiResources") // XP
#pragma comment(linker, "/export:GetIconInfo=user32.GetIconInfo") // XP
#pragma comment(linker, "/export:GetIconInfoExA=user32.GetIconInfoExA")
#pragma comment(linker, "/export:GetIconInfoExW=user32.GetIconInfoExW")
#pragma comment(linker, "/export:GetInputDesktop=user32.GetInputDesktop") // XP
#pragma comment(linker, "/export:GetInputLocaleInfo=user32.GetInputLocaleInfo")
#pragma comment(linker, "/export:GetInputState=user32.GetInputState") // XP
#pragma comment(linker, "/export:GetInternalWindowPos=user32.GetInternalWindowPos") // XP
#pragma comment(linker, "/export:GetKBCodePage=user32.GetKBCodePage") // XP
#pragma comment(linker, "/export:GetKeyNameTextA=user32.GetKeyNameTextA") // XP
#pragma comment(linker, "/export:GetKeyNameTextW=user32.GetKeyNameTextW") // XP
#pragma comment(linker, "/export:GetKeyState=user32.GetKeyState") // XP
#pragma comment(linker, "/export:GetKeyboardLayout=user32.GetKeyboardLayout") // XP
#pragma comment(linker, "/export:GetKeyboardLayoutList=user32.GetKeyboardLayoutList") // XP
#pragma comment(linker, "/export:GetKeyboardLayoutNameA=user32.GetKeyboardLayoutNameA") // XP
#pragma comment(linker, "/export:GetKeyboardLayoutNameW=user32.GetKeyboardLayoutNameW") // XP
#pragma comment(linker, "/export:GetKeyboardState=user32.GetKeyboardState") // XP
#pragma comment(linker, "/export:GetKeyboardType=user32.GetKeyboardType") // XP
#pragma comment(linker, "/export:GetLastActivePopup=user32.GetLastActivePopup") // XP
#pragma comment(linker, "/export:GetLastInputInfo=user32.GetLastInputInfo") // XP
#pragma comment(linker, "/export:GetLayeredWindowAttributes=user32.GetLayeredWindowAttributes") // XP
#pragma comment(linker, "/export:GetListBoxInfo=user32.GetListBoxInfo") // XP
#pragma comment(linker, "/export:GetMagnificationDesktopColorEffect=user32.GetMagnificationDesktopColorEffect")
#pragma comment(linker, "/export:GetMagnificationDesktopMagnification=user32.GetMagnificationDesktopMagnification")
#pragma comment(linker, "/export:GetMagnificationLensCtxInformation=user32.GetMagnificationLensCtxInformation")
#pragma comment(linker, "/export:GetMenu=user32.GetMenu") // XP
#pragma comment(linker, "/export:GetMenuBarInfo=user32.GetMenuBarInfo") // XP
#pragma comment(linker, "/export:GetMenuCheckMarkDimensions=user32.GetMenuCheckMarkDimensions") // XP
#pragma comment(linker, "/export:GetMenuContextHelpId=user32.GetMenuContextHelpId") // XP
#pragma comment(linker, "/export:GetMenuDefaultItem=user32.GetMenuDefaultItem") // XP
#pragma comment(linker, "/export:GetMenuInfo=user32.GetMenuInfo") // XP
#pragma comment(linker, "/export:GetMenuItemCount=user32.GetMenuItemCount") // XP
#pragma comment(linker, "/export:GetMenuItemID=user32.GetMenuItemID") // XP
#pragma comment(linker, "/export:GetMenuItemInfoA=user32.GetMenuItemInfoA") // XP
#pragma comment(linker, "/export:GetMenuItemInfoW=user32.GetMenuItemInfoW") // XP
#pragma comment(linker, "/export:GetMenuItemRect=user32.GetMenuItemRect") // XP
#pragma comment(linker, "/export:GetMenuState=user32.GetMenuState") // XP
#pragma comment(linker, "/export:GetMenuStringA=user32.GetMenuStringA") // XP
#pragma comment(linker, "/export:GetMenuStringW=user32.GetMenuStringW") // XP
#pragma comment(linker, "/export:GetMessageA=user32.GetMessageA") // XP
#pragma comment(linker, "/export:GetMessageExtraInfo=user32.GetMessageExtraInfo") // XP
#pragma comment(linker, "/export:GetMessagePos=user32.GetMessagePos") // XP
#pragma comment(linker, "/export:GetMessageTime=user32.GetMessageTime") // XP
#pragma comment(linker, "/export:GetMessageW=user32.GetMessageW") // XP
#pragma comment(linker, "/export:GetMonitorInfoA=user32.GetMonitorInfoA") // XP
#pragma comment(linker, "/export:GetMonitorInfoW=user32.GetMonitorInfoW") // XP
#pragma comment(linker, "/export:GetMouseMovePointsEx=user32.GetMouseMovePointsEx") // XP
#pragma comment(linker, "/export:GetNextDlgGroupItem=user32.GetNextDlgGroupItem") // XP
#pragma comment(linker, "/export:GetNextDlgTabItem=user32.GetNextDlgTabItem") // XP
#pragma comment(linker, "/export:GetOpenClipboardWindow=user32.GetOpenClipboardWindow") // XP
#pragma comment(linker, "/export:GetParent=user32.GetParent") // XP
#pragma comment(linker, "/export:GetPhysicalCursorPos=user32.GetPhysicalCursorPos")
#pragma comment(linker, "/export:GetPointerCursorId=user32.GetPointerCursorId")
#pragma comment(linker, "/export:GetPointerDevice=user32.GetPointerDevice")
#pragma comment(linker, "/export:GetPointerDeviceCursors=user32.GetPointerDeviceCursors")
#pragma comment(linker, "/export:GetPointerDeviceProperties=user32.GetPointerDeviceProperties")
#pragma comment(linker, "/export:GetPointerDeviceRects=user32.GetPointerDeviceRects")
#pragma comment(linker, "/export:GetPointerDevices=user32.GetPointerDevices")
#pragma comment(linker, "/export:GetPointerFrameArrivalTimes=user32.GetPointerFrameArrivalTimes")
#pragma comment(linker, "/export:GetPointerFrameInfo=user32.GetPointerFrameInfo")
#pragma comment(linker, "/export:GetPointerFrameInfoHistory=user32.GetPointerFrameInfoHistory")
#pragma comment(linker, "/export:GetPointerFramePenInfo=user32.GetPointerFramePenInfo")
#pragma comment(linker, "/export:GetPointerFramePenInfoHistory=user32.GetPointerFramePenInfoHistory")
#pragma comment(linker, "/export:GetPointerFrameTouchInfo=user32.GetPointerFrameTouchInfo")
#pragma comment(linker, "/export:GetPointerFrameTouchInfoHistory=user32.GetPointerFrameTouchInfoHistory")
#pragma comment(linker, "/export:GetPointerInfo=user32.GetPointerInfo")
#pragma comment(linker, "/export:GetPointerInfoHistory=user32.GetPointerInfoHistory")
#pragma comment(linker, "/export:GetPointerInputTransform=user32.GetPointerInputTransform")
#pragma comment(linker, "/export:GetPointerPenInfo=user32.GetPointerPenInfo")
#pragma comment(linker, "/export:GetPointerPenInfoHistory=user32.GetPointerPenInfoHistory")
#pragma comment(linker, "/export:GetPointerTouchInfo=user32.GetPointerTouchInfo")
#pragma comment(linker, "/export:GetPointerTouchInfoHistory=user32.GetPointerTouchInfoHistory")
#pragma comment(linker, "/export:GetPointerType=user32.GetPointerType")
#pragma comment(linker, "/export:GetPriorityClipboardFormat=user32.GetPriorityClipboardFormat") // XP
#pragma comment(linker, "/export:GetProcessDefaultLayout=user32.GetProcessDefaultLayout") // XP
#pragma comment(linker, "/export:GetProcessDpiAwarenessInternal=user32.GetProcessDpiAwarenessInternal")
#pragma comment(linker, "/export:GetProcessWindowStation=user32.GetProcessWindowStation") // XP
#pragma comment(linker, "/export:GetProgmanWindow=user32.GetProgmanWindow") // XP
#pragma comment(linker, "/export:GetPropA=user32.GetPropA") // XP
#pragma comment(linker, "/export:GetPropW=user32.GetPropW") // XP
#pragma comment(linker, "/export:GetQueueStatus=user32.GetQueueStatus") // XP
#pragma comment(linker, "/export:GetRawInputBuffer=user32.GetRawInputBuffer") // XP
#pragma comment(linker, "/export:GetRawInputData=user32.GetRawInputData") // XP
#pragma comment(linker, "/export:GetRawInputDeviceInfoA=user32.GetRawInputDeviceInfoA") // XP
#pragma comment(linker, "/export:GetRawInputDeviceInfoW=user32.GetRawInputDeviceInfoW") // XP
#pragma comment(linker, "/export:GetRawInputDeviceList=user32.GetRawInputDeviceList") // XP
#pragma comment(linker, "/export:GetRawPointerDeviceData=user32.GetRawPointerDeviceData")
#pragma comment(linker, "/export:GetReasonTitleFromReasonCode=user32.GetReasonTitleFromReasonCode") // XP
#pragma comment(linker, "/export:GetRegisteredRawInputDevices=user32.GetRegisteredRawInputDevices") // XP
#pragma comment(linker, "/export:GetScrollBarInfo=user32.GetScrollBarInfo") // XP
#pragma comment(linker, "/export:GetScrollInfo=user32.GetScrollInfo") // XP
#pragma comment(linker, "/export:GetScrollPos=user32.GetScrollPos") // XP
#pragma comment(linker, "/export:GetScrollRange=user32.GetScrollRange") // XP
#pragma comment(linker, "/export:GetSendMessageReceiver=user32.GetSendMessageReceiver")
#pragma comment(linker, "/export:GetShellWindow=user32.GetShellWindow") // XP
#pragma comment(linker, "/export:GetSubMenu=user32.GetSubMenu") // XP
#pragma comment(linker, "/export:GetSysColor=user32.GetSysColor") // XP
#pragma comment(linker, "/export:GetSysColorBrush=user32.GetSysColorBrush") // XP
#pragma comment(linker, "/export:GetSystemMenu=user32.GetSystemMenu") // XP
#pragma comment(linker, "/export:GetSystemMetrics=user32.GetSystemMetrics") // XP
#pragma comment(linker, "/export:GetSystemMetricsForDpi=user32.GetSystemMetricsForDpi")
#pragma comment(linker, "/export:GetTabbedTextExtentA=user32.GetTabbedTextExtentA") // XP
#pragma comment(linker, "/export:GetTabbedTextExtentW=user32.GetTabbedTextExtentW") // XP
#pragma comment(linker, "/export:GetTaskmanWindow=user32.GetTaskmanWindow") // XP
#pragma comment(linker, "/export:GetThreadDesktop=user32.GetThreadDesktop") // XP
#pragma comment(linker, "/export:GetThreadDpiAwarenessContext=user32.GetThreadDpiAwarenessContext")
#pragma comment(linker, "/export:GetTitleBarInfo=user32.GetTitleBarInfo") // XP
#pragma comment(linker, "/export:GetTopLevelWindow=user32.GetTopLevelWindow")
#pragma comment(linker, "/export:GetTopWindow=user32.GetTopWindow") // XP
#pragma comment(linker, "/export:GetTouchInputInfo=user32.GetTouchInputInfo")
#pragma comment(linker, "/export:GetUnpredictedMessagePos=user32.GetUnpredictedMessagePos")
#pragma comment(linker, "/export:GetUpdateRect=user32.GetUpdateRect") // XP
#pragma comment(linker, "/export:GetUpdateRgn=user32.GetUpdateRgn") // XP
#pragma comment(linker, "/export:GetUpdatedClipboardFormats=user32.GetUpdatedClipboardFormats")
#pragma comment(linker, "/export:GetUserObjectInformationA=user32.GetUserObjectInformationA") // XP
#pragma comment(linker, "/export:GetUserObjectInformationW=user32.GetUserObjectInformationW") // XP
#pragma comment(linker, "/export:GetUserObjectSecurity=user32.GetUserObjectSecurity") // XP
#pragma comment(linker, "/export:GetWinStationInfo=user32.GetWinStationInfo") // XP
#pragma comment(linker, "/export:GetWindow=user32.GetWindow") // XP
#pragma comment(linker, "/export:GetWindowBand=user32.GetWindowBand")
#pragma comment(linker, "/export:GetWindowCompositionAttribute=user32.GetWindowCompositionAttribute")
#pragma comment(linker, "/export:GetWindowCompositionInfo=user32.GetWindowCompositionInfo")
#pragma comment(linker, "/export:GetWindowContextHelpId=user32.GetWindowContextHelpId") // XP
#pragma comment(linker, "/export:GetWindowDC=user32.GetWindowDC") // XP
#pragma comment(linker, "/export:GetWindowDisplayAffinity=user32.GetWindowDisplayAffinity")
#pragma comment(linker, "/export:GetWindowDpiAwarenessContext=user32.GetWindowDpiAwarenessContext")
#pragma comment(linker, "/export:GetWindowFeedbackSetting=user32.GetWindowFeedbackSetting")
#pragma comment(linker, "/export:GetWindowInfo=user32.GetWindowInfo") // XP
#pragma comment(linker, "/export:GetWindowLongA=user32.GetWindowLongA") // XP
#pragma comment(linker, "/export:GetWindowLongW=user32.GetWindowLongW") // XP
#pragma comment(linker, "/export:GetWindowMinimizeRect=user32.GetWindowMinimizeRect")
#pragma comment(linker, "/export:GetWindowModuleFileName=user32.GetWindowModuleFileName") // XP
#pragma comment(linker, "/export:GetWindowModuleFileNameA=user32.GetWindowModuleFileNameA") // XP
#pragma comment(linker, "/export:GetWindowModuleFileNameW=user32.GetWindowModuleFileNameW") // XP
#pragma comment(linker, "/export:GetWindowPlacement=user32.GetWindowPlacement") // XP
#pragma comment(linker, "/export:GetWindowRect=user32.GetWindowRect") // XP
#pragma comment(linker, "/export:GetWindowRgn=user32.GetWindowRgn") // XP
#pragma comment(linker, "/export:GetWindowRgnBox=user32.GetWindowRgnBox") // XP
#pragma comment(linker, "/export:GetWindowRgnEx=user32.GetWindowRgnEx")
#pragma comment(linker, "/export:GetWindowTextA=user32.GetWindowTextA") // XP
#pragma comment(linker, "/export:GetWindowTextLengthA=user32.GetWindowTextLengthA") // XP
#pragma comment(linker, "/export:GetWindowTextLengthW=user32.GetWindowTextLengthW") // XP
#pragma comment(linker, "/export:GetWindowTextW=user32.GetWindowTextW") // XP
#pragma comment(linker, "/export:GetWindowThreadProcessId=user32.GetWindowThreadProcessId") // XP
#pragma comment(linker, "/export:GetWindowWord=user32.GetWindowWord") // XP
#pragma comment(linker, "/export:GhostWindowFromHungWindow=user32.GhostWindowFromHungWindow")
#pragma comment(linker, "/export:GrayStringA=user32.GrayStringA") // XP
#pragma comment(linker, "/export:GrayStringW=user32.GrayStringW") // XP
#pragma comment(linker, "/export:HideCaret=user32.HideCaret") // XP
#pragma comment(linker, "/export:HiliteMenuItem=user32.HiliteMenuItem") // XP
#pragma comment(linker, "/export:HungWindowFromGhostWindow=user32.HungWindowFromGhostWindow")
#pragma comment(linker, "/export:IMPGetIMEA=user32.IMPGetIMEA") // XP
#pragma comment(linker, "/export:IMPGetIMEW=user32.IMPGetIMEW") // XP
#pragma comment(linker, "/export:IMPQueryIMEA=user32.IMPQueryIMEA") // XP
#pragma comment(linker, "/export:IMPQueryIMEW=user32.IMPQueryIMEW") // XP
#pragma comment(linker, "/export:IMPSetIMEA=user32.IMPSetIMEA") // XP
#pragma comment(linker, "/export:IMPSetIMEW=user32.IMPSetIMEW") // XP
#pragma comment(linker, "/export:ImpersonateDdeClientWindow=user32.ImpersonateDdeClientWindow") // XP
#pragma comment(linker, "/export:InSendMessage=user32.InSendMessage") // XP
#pragma comment(linker, "/export:InSendMessageEx=user32.InSendMessageEx") // XP
#pragma comment(linker, "/export:InflateRect=user32.InflateRect") // XP
#pragma comment(linker, "/export:InheritWindowMonitor=user32.InheritWindowMonitor")
#pragma comment(linker, "/export:InitDManipHook=user32.InitDManipHook")
#pragma comment(linker, "/export:InitializeInputDeviceInjection=user32.InitializeInputDeviceInjection")
#pragma comment(linker, "/export:InitializeLpkHooks=user32.InitializeLpkHooks") // XP
#pragma comment(linker, "/export:InitializePointerDeviceInjection=user32.InitializePointerDeviceInjection")
#pragma comment(linker, "/export:InitializeTouchInjection=user32.InitializeTouchInjection")
#pragma comment(linker, "/export:InjectDeviceInput=user32.InjectDeviceInput")
#pragma comment(linker, "/export:InjectKeyboardInput=user32.InjectKeyboardInput")
#pragma comment(linker, "/export:InjectMouseInput=user32.InjectMouseInput")
#pragma comment(linker, "/export:InjectPointerInput=user32.InjectPointerInput")
#pragma comment(linker, "/export:InjectTouchInput=user32.InjectTouchInput")
#pragma comment(linker, "/export:InsertMenuA=user32.InsertMenuA") // XP
#pragma comment(linker, "/export:InsertMenuItemA=user32.InsertMenuItemA") // XP
#pragma comment(linker, "/export:InsertMenuItemW=user32.InsertMenuItemW") // XP
#pragma comment(linker, "/export:InsertMenuW=user32.InsertMenuW") // XP
#pragma comment(linker, "/export:InternalGetWindowIcon=user32.InternalGetWindowIcon")
#pragma comment(linker, "/export:InternalGetWindowText=user32.InternalGetWindowText") // XP
#pragma comment(linker, "/export:IntersectRect=user32.IntersectRect") // XP
#pragma comment(linker, "/export:InvalidateRect=user32.InvalidateRect") // XP
#pragma comment(linker, "/export:InvalidateRgn=user32.InvalidateRgn") // XP
#pragma comment(linker, "/export:InvertRect=user32.InvertRect") // XP
#pragma comment(linker, "/export:IsCharAlphaA=user32.IsCharAlphaA") // XP
#pragma comment(linker, "/export:IsCharAlphaNumericA=user32.IsCharAlphaNumericA") // XP
#pragma comment(linker, "/export:IsCharAlphaNumericW=user32.IsCharAlphaNumericW") // XP
#pragma comment(linker, "/export:IsCharAlphaW=user32.IsCharAlphaW") // XP
#pragma comment(linker, "/export:IsCharLowerA=user32.IsCharLowerA") // XP
#pragma comment(linker, "/export:IsCharLowerW=user32.IsCharLowerW") // XP
#pragma comment(linker, "/export:IsCharUpperA=user32.IsCharUpperA") // XP
#pragma comment(linker, "/export:IsCharUpperW=user32.IsCharUpperW") // XP
#pragma comment(linker, "/export:IsChild=user32.IsChild") // XP
#pragma comment(linker, "/export:IsClipboardFormatAvailable=user32.IsClipboardFormatAvailable") // XP
#pragma comment(linker, "/export:IsDialogMessage=user32.IsDialogMessage") // XP
#pragma comment(linker, "/export:IsDialogMessageA=user32.IsDialogMessageA") // XP
#pragma comment(linker, "/export:IsDialogMessageW=user32.IsDialogMessageW") // XP
#pragma comment(linker, "/export:IsDlgButtonChecked=user32.IsDlgButtonChecked") // XP
#pragma comment(linker, "/export:IsGUIThread=user32.IsGUIThread") // XP
#pragma comment(linker, "/export:IsHungAppWindow=user32.IsHungAppWindow") // XP
#pragma comment(linker, "/export:IsIconic=user32.IsIconic") // XP
#pragma comment(linker, "/export:IsImmersiveProcess=user32.IsImmersiveProcess")
#pragma comment(linker, "/export:IsInDesktopWindowBand=user32.IsInDesktopWindowBand")
#pragma comment(linker, "/export:IsMenu=user32.IsMenu") // XP
#pragma comment(linker, "/export:IsMouseInPointerEnabled=user32.IsMouseInPointerEnabled")
#pragma comment(linker, "/export:IsProcessDPIAware=user32.IsProcessDPIAware")
#pragma comment(linker, "/export:IsQueueAttached=user32.IsQueueAttached")
#pragma comment(linker, "/export:IsRectEmpty=user32.IsRectEmpty") // XP
#pragma comment(linker, "/export:IsSETEnabled=user32.IsSETEnabled")
#pragma comment(linker, "/export:IsServerSideWindow=user32.IsServerSideWindow") // XP
#pragma comment(linker, "/export:IsThreadDesktopComposited=user32.IsThreadDesktopComposited")
#pragma comment(linker, "/export:IsThreadMessageQueueAttached=user32.IsThreadMessageQueueAttached")
#pragma comment(linker, "/export:IsTopLevelWindow=user32.IsTopLevelWindow")
#pragma comment(linker, "/export:IsTouchWindow=user32.IsTouchWindow")
#pragma comment(linker, "/export:IsValidDpiAwarenessContext=user32.IsValidDpiAwarenessContext")
#pragma comment(linker, "/export:IsWinEventHookInstalled=user32.IsWinEventHookInstalled") // XP
#pragma comment(linker, "/export:IsWindow=user32.IsWindow") // XP
#pragma comment(linker, "/export:IsWindowArranged=user32.IsWindowArranged")
#pragma comment(linker, "/export:IsWindowEnabled=user32.IsWindowEnabled") // XP
#pragma comment(linker, "/export:IsWindowInDestroy=user32.IsWindowInDestroy") // XP
#pragma comment(linker, "/export:IsWindowRedirectedForPrint=user32.IsWindowRedirectedForPrint")
#pragma comment(linker, "/export:IsWindowUnicode=user32.IsWindowUnicode") // XP
#pragma comment(linker, "/export:IsWindowVisible=user32.IsWindowVisible") // XP
#pragma comment(linker, "/export:IsWow64Message=user32.IsWow64Message")
#pragma comment(linker, "/export:IsZoomed=user32.IsZoomed") // XP
#pragma comment(linker, "/export:KillTimer=user32.KillTimer") // XP
#pragma comment(linker, "/export:LoadAcceleratorsA=user32.LoadAcceleratorsA") // XP
#pragma comment(linker, "/export:LoadAcceleratorsW=user32.LoadAcceleratorsW") // XP
#pragma comment(linker, "/export:LoadBitmapA=user32.LoadBitmapA") // XP
#pragma comment(linker, "/export:LoadBitmapW=user32.LoadBitmapW") // XP
#pragma comment(linker, "/export:LoadCursorA=user32.LoadCursorA") // XP
#pragma comment(linker, "/export:LoadCursorFromFileA=user32.LoadCursorFromFileA") // XP
#pragma comment(linker, "/export:LoadCursorFromFileW=user32.LoadCursorFromFileW") // XP
#pragma comment(linker, "/export:LoadCursorW=user32.LoadCursorW") // XP
#pragma comment(linker, "/export:LoadIconA=user32.LoadIconA") // XP
#pragma comment(linker, "/export:LoadIconW=user32.LoadIconW") // XP
#pragma comment(linker, "/export:LoadImageA=user32.LoadImageA") // XP
#pragma comment(linker, "/export:LoadImageW=user32.LoadImageW") // XP
#pragma comment(linker, "/export:LoadKeyboardLayoutA=user32.LoadKeyboardLayoutA") // XP
#pragma comment(linker, "/export:LoadKeyboardLayoutEx=user32.LoadKeyboardLayoutEx") // XP
#pragma comment(linker, "/export:LoadKeyboardLayoutW=user32.LoadKeyboardLayoutW") // XP
#pragma comment(linker, "/export:LoadLocalFonts=user32.LoadLocalFonts") // XP
#pragma comment(linker, "/export:LoadMenuA=user32.LoadMenuA") // XP
#pragma comment(linker, "/export:LoadMenuIndirectA=user32.LoadMenuIndirectA") // XP
#pragma comment(linker, "/export:LoadMenuIndirectW=user32.LoadMenuIndirectW") // XP
#pragma comment(linker, "/export:LoadMenuW=user32.LoadMenuW") // XP
#pragma comment(linker, "/export:LoadRemoteFonts=user32.LoadRemoteFonts") // XP
#pragma comment(linker, "/export:LoadStringA=user32.LoadStringA") // XP
#pragma comment(linker, "/export:LoadStringW=user32.LoadStringW") // XP
#pragma comment(linker, "/export:LockSetForegroundWindow=user32.LockSetForegroundWindow") // XP
#pragma comment(linker, "/export:LockWindowStation=user32.LockWindowStation") // XP
#pragma comment(linker, "/export:LockWindowUpdate=user32.LockWindowUpdate") // XP
#pragma comment(linker, "/export:LockWorkStation=user32.LockWorkStation") // XP
#pragma comment(linker, "/export:LogicalToPhysicalPoint=user32.LogicalToPhysicalPoint")
#pragma comment(linker, "/export:LogicalToPhysicalPointForPerMonitorDPI=user32.LogicalToPhysicalPointForPerMonitorDPI")
#pragma comment(linker, "/export:LookupIconIdFromDirectory=user32.LookupIconIdFromDirectory") // XP
#pragma comment(linker, "/export:LookupIconIdFromDirectoryEx=user32.LookupIconIdFromDirectoryEx") // XP
#pragma comment(linker, "/export:MBToWCSEx=user32.MBToWCSEx") // XP
#pragma comment(linker, "/export:MBToWCSExt=user32.MBToWCSExt")
#pragma comment(linker, "/export:MB_GetString=user32.MB_GetString") // XP
#pragma comment(linker, "/export:MapDialogRect=user32.MapDialogRect") // XP
#pragma comment(linker, "/export:MapVirtualKeyA=user32.MapVirtualKeyA") // XP
#pragma comment(linker, "/export:MapVirtualKeyExA=user32.MapVirtualKeyExA") // XP
#pragma comment(linker, "/export:MapVirtualKeyExW=user32.MapVirtualKeyExW") // XP
#pragma comment(linker, "/export:MapVirtualKeyW=user32.MapVirtualKeyW") // XP
#pragma comment(linker, "/export:MapWindowPoints=user32.MapWindowPoints") // XP
#pragma comment(linker, "/export:MenuItemFromPoint=user32.MenuItemFromPoint") // XP
#pragma comment(linker, "/export:MenuWindowProcA=user32.MenuWindowProcA") // XP
#pragma comment(linker, "/export:MenuWindowProcW=user32.MenuWindowProcW") // XP
#pragma comment(linker, "/export:MessageBeep=user32.MessageBeep") // XP
#pragma comment(linker, "/export:MessageBoxA=user32.MessageBoxA") // XP
#pragma comment(linker, "/export:MessageBoxExA=user32.MessageBoxExA") // XP
#pragma comment(linker, "/export:MessageBoxExW=user32.MessageBoxExW") // XP
#pragma comment(linker, "/export:MessageBoxIndirectA=user32.MessageBoxIndirectA") // XP
#pragma comment(linker, "/export:MessageBoxIndirectW=user32.MessageBoxIndirectW") // XP
#pragma comment(linker, "/export:MessageBoxTimeoutA=user32.MessageBoxTimeoutA") // XP
#pragma comment(linker, "/export:MessageBoxTimeoutW=user32.MessageBoxTimeoutW") // XP
#pragma comment(linker, "/export:MessageBoxW=user32.MessageBoxW") // XP
#pragma comment(linker, "/export:ModifyMenuA=user32.ModifyMenuA") // XP
#pragma comment(linker, "/export:ModifyMenuW=user32.ModifyMenuW") // XP
#pragma comment(linker, "/export:MonitorFromPoint=user32.MonitorFromPoint") // XP
#pragma comment(linker, "/export:MonitorFromRect=user32.MonitorFromRect") // XP
#pragma comment(linker, "/export:MonitorFromWindow=user32.MonitorFromWindow") // XP
#pragma comment(linker, "/export:MoveWindow=user32.MoveWindow") // XP
#pragma comment(linker, "/export:MsgWaitForMultipleObjects=user32.MsgWaitForMultipleObjects") // XP
#pragma comment(linker, "/export:MsgWaitForMultipleObjectsEx=user32.MsgWaitForMultipleObjectsEx") // XP
#pragma comment(linker, "/export:NotifyOverlayWindow=user32.NotifyOverlayWindow")
#pragma comment(linker, "/export:NotifyWinEvent=user32.NotifyWinEvent") // XP
#pragma comment(linker, "/export:OemKeyScan=user32.OemKeyScan") // XP
#pragma comment(linker, "/export:OemToCharA=user32.OemToCharA") // XP
#pragma comment(linker, "/export:OemToCharBuffA=user32.OemToCharBuffA") // XP
#pragma comment(linker, "/export:OemToCharBuffW=user32.OemToCharBuffW") // XP
#pragma comment(linker, "/export:OemToCharW=user32.OemToCharW") // XP
#pragma comment(linker, "/export:OffsetRect=user32.OffsetRect") // XP
#pragma comment(linker, "/export:OpenClipboard=user32.OpenClipboard") // XP
#pragma comment(linker, "/export:OpenDesktopA=user32.OpenDesktopA") // XP
#pragma comment(linker, "/export:OpenDesktopW=user32.OpenDesktopW") // XP
#pragma comment(linker, "/export:OpenIcon=user32.OpenIcon") // XP
#pragma comment(linker, "/export:OpenInputDesktop=user32.OpenInputDesktop") // XP
#pragma comment(linker, "/export:OpenThreadDesktop=user32.OpenThreadDesktop")
#pragma comment(linker, "/export:OpenWindowStationA=user32.OpenWindowStationA") // XP
#pragma comment(linker, "/export:OpenWindowStationW=user32.OpenWindowStationW") // XP
#pragma comment(linker, "/export:PackDDElParam=user32.PackDDElParam") // XP
#pragma comment(linker, "/export:PackTouchHitTestingProximityEvaluation=user32.PackTouchHitTestingProximityEvaluation")
#pragma comment(linker, "/export:PaintDesktop=user32.PaintDesktop") // XP
#pragma comment(linker, "/export:PaintMenuBar=user32.PaintMenuBar") // XP
#pragma comment(linker, "/export:PaintMonitor=user32.PaintMonitor")
#pragma comment(linker, "/export:PeekMessageA=user32.PeekMessageA") // XP
#pragma comment(linker, "/export:PeekMessageW=user32.PeekMessageW") // XP
#pragma comment(linker, "/export:PhysicalToLogicalPoint=user32.PhysicalToLogicalPoint")
#pragma comment(linker, "/export:PhysicalToLogicalPointForPerMonitorDPI=user32.PhysicalToLogicalPointForPerMonitorDPI")
#pragma comment(linker, "/export:PostMessageA=user32.PostMessageA") // XP
#pragma comment(linker, "/export:PostMessageW=user32.PostMessageW") // XP
#pragma comment(linker, "/export:PostQuitMessage=user32.PostQuitMessage") // XP
#pragma comment(linker, "/export:PostThreadMessageA=user32.PostThreadMessageA") // XP
#pragma comment(linker, "/export:PostThreadMessageW=user32.PostThreadMessageW") // XP
#pragma comment(linker, "/export:PrintWindow=user32.PrintWindow") // XP
#pragma comment(linker, "/export:PrivateExtractIconExA=user32.PrivateExtractIconExA") // XP
#pragma comment(linker, "/export:PrivateExtractIconExW=user32.PrivateExtractIconExW") // XP
#pragma comment(linker, "/export:PrivateExtractIconsA=user32.PrivateExtractIconsA") // XP
#pragma comment(linker, "/export:PrivateExtractIconsW=user32.PrivateExtractIconsW") // XP
#pragma comment(linker, "/export:PrivateRegisterICSProc=user32.PrivateRegisterICSProc")
#pragma comment(linker, "/export:PtInRect=user32.PtInRect") // XP
#pragma comment(linker, "/export:QueryBSDRWindow=user32.QueryBSDRWindow")
#pragma comment(linker, "/export:QueryDisplayConfig=user32.QueryDisplayConfig")
#pragma comment(linker, "/export:QuerySendMessage=user32.QuerySendMessage") // XP
#pragma comment(linker, "/export:RIMAddInputObserver=user32.RIMAddInputObserver")
#pragma comment(linker, "/export:RIMAreSiblingDevices=user32.RIMAreSiblingDevices")
#pragma comment(linker, "/export:RIMDeviceIoControl=user32.RIMDeviceIoControl")
#pragma comment(linker, "/export:RIMFreeInputBuffer=user32.RIMFreeInputBuffer")
#pragma comment(linker, "/export:RIMGetDevicePreparsedData=user32.RIMGetDevicePreparsedData")
#pragma comment(linker, "/export:RIMGetDevicePreparsedDataLockfree=user32.RIMGetDevicePreparsedDataLockfree")
#pragma comment(linker, "/export:RIMGetDeviceProperties=user32.RIMGetDeviceProperties")
#pragma comment(linker, "/export:RIMGetPhysicalDeviceRect=user32.RIMGetPhysicalDeviceRect")
#pragma comment(linker, "/export:RIMGetSourceProcessId=user32.RIMGetSourceProcessId")
#pragma comment(linker, "/export:RIMObserveNextInput=user32.RIMObserveNextInput")
#pragma comment(linker, "/export:RIMOnPnpNotification=user32.RIMOnPnpNotification")
#pragma comment(linker, "/export:RIMOnTimerNotification=user32.RIMOnTimerNotification")
#pragma comment(linker, "/export:RIMReadInput=user32.RIMReadInput")
#pragma comment(linker, "/export:RIMRegisterForInput=user32.RIMRegisterForInput")
#pragma comment(linker, "/export:RIMRemoveInputObserver=user32.RIMRemoveInputObserver")
#pragma comment(linker, "/export:RIMSetTestModeStatus=user32.RIMSetTestModeStatus")
#pragma comment(linker, "/export:RIMUnregisterForInput=user32.RIMUnregisterForInput")
#pragma comment(linker, "/export:RIMUpdateInputObserverRegistration=user32.RIMUpdateInputObserverRegistration")
#pragma comment(linker, "/export:RealChildWindowFromPoint=user32.RealChildWindowFromPoint") // XP
#pragma comment(linker, "/export:RealGetWindowClass=user32.RealGetWindowClass") // XP
#pragma comment(linker, "/export:RealGetWindowClassA=user32.RealGetWindowClassA") // XP
#pragma comment(linker, "/export:RealGetWindowClassW=user32.RealGetWindowClassW") // XP
#pragma comment(linker, "/export:ReasonCodeNeedsBugID=user32.ReasonCodeNeedsBugID") // XP
#pragma comment(linker, "/export:ReasonCodeNeedsComment=user32.ReasonCodeNeedsComment") // XP
#pragma comment(linker, "/export:RecordShutdownReason=user32.RecordShutdownReason") // XP
#pragma comment(linker, "/export:RedrawWindow=user32.RedrawWindow") // XP
#pragma comment(linker, "/export:RegisterBSDRWindow=user32.RegisterBSDRWindow")
#pragma comment(linker, "/export:RegisterClassA=user32.RegisterClassA") // XP
#pragma comment(linker, "/export:RegisterClassExA=user32.RegisterClassExA") // XP
#pragma comment(linker, "/export:RegisterClassExW=user32.RegisterClassExW") // XP
#pragma comment(linker, "/export:RegisterClassW=user32.RegisterClassW") // XP
#pragma comment(linker, "/export:RegisterClipboardFormatA=user32.RegisterClipboardFormatA") // XP
#pragma comment(linker, "/export:RegisterClipboardFormatW=user32.RegisterClipboardFormatW") // XP
#pragma comment(linker, "/export:RegisterDManipHook=user32.RegisterDManipHook")
#pragma comment(linker, "/export:RegisterDeviceNotificationA=user32.RegisterDeviceNotificationA") // XP
#pragma comment(linker, "/export:RegisterDeviceNotificationW=user32.RegisterDeviceNotificationW") // XP
#pragma comment(linker, "/export:RegisterErrorReportingDialog=user32.RegisterErrorReportingDialog")
#pragma comment(linker, "/export:RegisterFrostWindow=user32.RegisterFrostWindow")
#pragma comment(linker, "/export:RegisterGhostWindow=user32.RegisterGhostWindow")
#pragma comment(linker, "/export:RegisterHotKey=user32.RegisterHotKey") // XP
#pragma comment(linker, "/export:RegisterLogonProcess=user32.RegisterLogonProcess") // XP
#pragma comment(linker, "/export:RegisterManipulationThread=user32.RegisterManipulationThread")
#pragma comment(linker, "/export:RegisterMessagePumpHook=user32.RegisterMessagePumpHook") // XP
#pragma comment(linker, "/export:RegisterPointerDeviceNotifications=user32.RegisterPointerDeviceNotifications")
#pragma comment(linker, "/export:RegisterPointerInputTarget=user32.RegisterPointerInputTarget")
#pragma comment(linker, "/export:RegisterPointerInputTargetEx=user32.RegisterPointerInputTargetEx")
#pragma comment(linker, "/export:RegisterPowerSettingNotification=user32.RegisterPowerSettingNotification")
#pragma comment(linker, "/export:RegisterRawInputDevices=user32.RegisterRawInputDevices") // XP
#pragma comment(linker, "/export:RegisterServicesProcess=user32.RegisterServicesProcess") // XP
#pragma comment(linker, "/export:RegisterSessionPort=user32.RegisterSessionPort")
#pragma comment(linker, "/export:RegisterShellHookWindow=user32.RegisterShellHookWindow") // XP
#pragma comment(linker, "/export:RegisterSuspendResumeNotification=user32.RegisterSuspendResumeNotification")
#pragma comment(linker, "/export:RegisterSystemThread=user32.RegisterSystemThread") // XP
#pragma comment(linker, "/export:RegisterTasklist=user32.RegisterTasklist") // XP
#pragma comment(linker, "/export:RegisterTouchHitTestingWindow=user32.RegisterTouchHitTestingWindow")
#pragma comment(linker, "/export:RegisterTouchWindow=user32.RegisterTouchWindow")
#pragma comment(linker, "/export:RegisterUserApiHook=user32.RegisterUserApiHook") // XP
#pragma comment(linker, "/export:RegisterWindowMessageA=user32.RegisterWindowMessageA") // XP
#pragma comment(linker, "/export:RegisterWindowMessageW=user32.RegisterWindowMessageW") // XP
#pragma comment(linker, "/export:ReleaseCapture=user32.ReleaseCapture") // XP
#pragma comment(linker, "/export:ReleaseDC=user32.ReleaseDC") // XP
#pragma comment(linker, "/export:ReleaseDwmHitTestWaiters=user32.ReleaseDwmHitTestWaiters")
#pragma comment(linker, "/export:RemoveClipboardFormatListener=user32.RemoveClipboardFormatListener")
#pragma comment(linker, "/export:RemoveInjectionDevice=user32.RemoveInjectionDevice")
#pragma comment(linker, "/export:RemoveMenu=user32.RemoveMenu") // XP
#pragma comment(linker, "/export:RemovePropA=user32.RemovePropA") // XP
#pragma comment(linker, "/export:RemovePropW=user32.RemovePropW") // XP
#pragma comment(linker, "/export:ReplyMessage=user32.ReplyMessage") // XP
#pragma comment(linker, "/export:ResolveDesktopForWOW=user32.ResolveDesktopForWOW") // XP
#pragma comment(linker, "/export:ReuseDDElParam=user32.ReuseDDElParam") // XP
#pragma comment(linker, "/export:ScreenToClient=user32.ScreenToClient") // XP
#pragma comment(linker, "/export:ScrollChildren=user32.ScrollChildren") // XP
#pragma comment(linker, "/export:ScrollDC=user32.ScrollDC") // XP
#pragma comment(linker, "/export:ScrollWindow=user32.ScrollWindow") // XP
#pragma comment(linker, "/export:ScrollWindowEx=user32.ScrollWindowEx") // XP
#pragma comment(linker, "/export:SendDlgItemMessageA=user32.SendDlgItemMessageA") // XP
#pragma comment(linker, "/export:SendDlgItemMessageW=user32.SendDlgItemMessageW") // XP
#pragma comment(linker, "/export:SendIMEMessageExA=user32.SendIMEMessageExA") // XP
#pragma comment(linker, "/export:SendIMEMessageExW=user32.SendIMEMessageExW") // XP
#pragma comment(linker, "/export:SendInput=user32.SendInput") // XP
#pragma comment(linker, "/export:SendMessageA=user32.SendMessageA") // XP
#pragma comment(linker, "/export:SendMessageCallbackA=user32.SendMessageCallbackA") // XP
#pragma comment(linker, "/export:SendMessageCallbackW=user32.SendMessageCallbackW") // XP
#pragma comment(linker, "/export:SendMessageTimeoutA=user32.SendMessageTimeoutA") // XP
#pragma comment(linker, "/export:SendMessageTimeoutW=user32.SendMessageTimeoutW") // XP
#pragma comment(linker, "/export:SendMessageW=user32.SendMessageW") // XP
#pragma comment(linker, "/export:SendNotifyMessageA=user32.SendNotifyMessageA") // XP
#pragma comment(linker, "/export:SendNotifyMessageW=user32.SendNotifyMessageW") // XP
#pragma comment(linker, "/export:SetActiveWindow=user32.SetActiveWindow") // XP
#pragma comment(linker, "/export:SetCapture=user32.SetCapture") // XP
#pragma comment(linker, "/export:SetCaretBlinkTime=user32.SetCaretBlinkTime") // XP
#pragma comment(linker, "/export:SetCaretPos=user32.SetCaretPos") // XP
#pragma comment(linker, "/export:SetClassLongA=user32.SetClassLongA") // XP
#pragma comment(linker, "/export:SetClassLongW=user32.SetClassLongW") // XP
#pragma comment(linker, "/export:SetClassWord=user32.SetClassWord") // XP
#pragma comment(linker, "/export:SetClipboardData=user32.SetClipboardData") // XP
#pragma comment(linker, "/export:SetClipboardViewer=user32.SetClipboardViewer") // XP
#pragma comment(linker, "/export:SetCoalescableTimer=user32.SetCoalescableTimer")
#pragma comment(linker, "/export:SetCursor=user32.SetCursor") // XP
#pragma comment(linker, "/export:SetCursorContents=user32.SetCursorContents") // XP
#pragma comment(linker, "/export:SetCursorPos=user32.SetCursorPos") // XP
#pragma comment(linker, "/export:SetDebugErrorLevel=user32.SetDebugErrorLevel") // XP
#pragma comment(linker, "/export:SetDeskWallpaper=user32.SetDeskWallpaper") // XP
#pragma comment(linker, "/export:SetDisplayAutoRotationPreferences=user32.SetDisplayAutoRotationPreferences")
#pragma comment(linker, "/export:SetDisplayConfig=user32.SetDisplayConfig")
#pragma comment(linker, "/export:SetDlgItemInt=user32.SetDlgItemInt") // XP
#pragma comment(linker, "/export:SetDlgItemTextA=user32.SetDlgItemTextA") // XP
#pragma comment(linker, "/export:SetDlgItemTextW=user32.SetDlgItemTextW") // XP
#pragma comment(linker, "/export:SetDoubleClickTime=user32.SetDoubleClickTime") // XP
#pragma comment(linker, "/export:SetFeatureReportResponse=user32.SetFeatureReportResponse")
#pragma comment(linker, "/export:SetFocus=user32.SetFocus") // XP
#pragma comment(linker, "/export:SetForegroundWindow=user32.SetForegroundWindow") // XP
#pragma comment(linker, "/export:SetGestureConfig=user32.SetGestureConfig")
#pragma comment(linker, "/export:SetInternalWindowPos=user32.SetInternalWindowPos") // XP
#pragma comment(linker, "/export:SetKeyboardState=user32.SetKeyboardState") // XP
#pragma comment(linker, "/export:SetLastErrorEx=user32.SetLastErrorEx") // XP
#pragma comment(linker, "/export:SetLayeredWindowAttributes=user32.SetLayeredWindowAttributes") // XP
#pragma comment(linker, "/export:SetMagnificationDesktopColorEffect=user32.SetMagnificationDesktopColorEffect")
#pragma comment(linker, "/export:SetMagnificationDesktopMagnification=user32.SetMagnificationDesktopMagnification")
#pragma comment(linker, "/export:SetMagnificationLensCtxInformation=user32.SetMagnificationLensCtxInformation")
#pragma comment(linker, "/export:SetManipulationInputTarget=user32.SetManipulationInputTarget")
#pragma comment(linker, "/export:SetMenu=user32.SetMenu") // XP
#pragma comment(linker, "/export:SetMenuContextHelpId=user32.SetMenuContextHelpId") // XP
#pragma comment(linker, "/export:SetMenuDefaultItem=user32.SetMenuDefaultItem") // XP
#pragma comment(linker, "/export:SetMenuInfo=user32.SetMenuInfo") // XP
#pragma comment(linker, "/export:SetMenuItemBitmaps=user32.SetMenuItemBitmaps") // XP
#pragma comment(linker, "/export:SetMenuItemInfoA=user32.SetMenuItemInfoA") // XP
#pragma comment(linker, "/export:SetMenuItemInfoW=user32.SetMenuItemInfoW") // XP
#pragma comment(linker, "/export:SetMessageExtraInfo=user32.SetMessageExtraInfo") // XP
#pragma comment(linker, "/export:SetMessageQueue=user32.SetMessageQueue") // XP
#pragma comment(linker, "/export:SetMirrorRendering=user32.SetMirrorRendering")
#pragma comment(linker, "/export:SetParent=user32.SetParent") // XP
#pragma comment(linker, "/export:SetPhysicalCursorPos=user32.SetPhysicalCursorPos")
#pragma comment(linker, "/export:SetProcessDPIAware=user32.SetProcessDPIAware")
#pragma comment(linker, "/export:SetProcessDefaultLayout=user32.SetProcessDefaultLayout") // XP
#pragma comment(linker, "/export:SetProcessDpiAwarenessContext=user32.SetProcessDpiAwarenessContext")
#pragma comment(linker, "/export:SetProcessDpiAwarenessInternal=user32.SetProcessDpiAwarenessInternal")
#pragma comment(linker, "/export:SetProcessRestrictionExemption=user32.SetProcessRestrictionExemption")
#pragma comment(linker, "/export:SetProcessWindowStation=user32.SetProcessWindowStation") // XP
#pragma comment(linker, "/export:SetProgmanWindow=user32.SetProgmanWindow") // XP
#pragma comment(linker, "/export:SetPropA=user32.SetPropA") // XP
#pragma comment(linker, "/export:SetPropW=user32.SetPropW") // XP
#pragma comment(linker, "/export:SetRect=user32.SetRect") // XP
#pragma comment(linker, "/export:SetRectEmpty=user32.SetRectEmpty") // XP
#pragma comment(linker, "/export:SetScrollInfo=user32.SetScrollInfo") // XP
#pragma comment(linker, "/export:SetScrollPos=user32.SetScrollPos") // XP
#pragma comment(linker, "/export:SetScrollRange=user32.SetScrollRange") // XP
#pragma comment(linker, "/export:SetShellWindow=user32.SetShellWindow") // XP
#pragma comment(linker, "/export:SetShellWindowEx=user32.SetShellWindowEx") // XP
#pragma comment(linker, "/export:SetSysColors=user32.SetSysColors") // XP
#pragma comment(linker, "/export:SetSysColorsTemp=user32.SetSysColorsTemp") // XP
#pragma comment(linker, "/export:SetSystemCursor=user32.SetSystemCursor") // XP
#pragma comment(linker, "/export:SetSystemMenu=user32.SetSystemMenu") // XP
#pragma comment(linker, "/export:SetTaskmanWindow=user32.SetTaskmanWindow") // XP
#pragma comment(linker, "/export:SetThreadDesktop=user32.SetThreadDesktop") // XP
#pragma comment(linker, "/export:SetThreadDpiAwarenessContext=user32.SetThreadDpiAwarenessContext")
#pragma comment(linker, "/export:SetThreadInputBlocked=user32.SetThreadInputBlocked")
#pragma comment(linker, "/export:SetTimer=user32.SetTimer") // XP
#pragma comment(linker, "/export:SetUserObjectInformationA=user32.SetUserObjectInformationA") // XP
#pragma comment(linker, "/export:SetUserObjectInformationW=user32.SetUserObjectInformationW") // XP
#pragma comment(linker, "/export:SetUserObjectSecurity=user32.SetUserObjectSecurity") // XP
#pragma comment(linker, "/export:SetWinEventHook=user32.SetWinEventHook") // XP
#pragma comment(linker, "/export:SetWindowBand=user32.SetWindowBand")
#pragma comment(linker, "/export:SetWindowCompositionAttribute=user32.SetWindowCompositionAttribute")
#pragma comment(linker, "/export:SetWindowCompositionTransition=user32.SetWindowCompositionTransition")
#pragma comment(linker, "/export:SetWindowContextHelpId=user32.SetWindowContextHelpId") // XP
#pragma comment(linker, "/export:SetWindowDisplayAffinity=user32.SetWindowDisplayAffinity")
#pragma comment(linker, "/export:SetWindowFeedbackSetting=user32.SetWindowFeedbackSetting")
#pragma comment(linker, "/export:SetWindowLongA=user32.SetWindowLongA") // XP
#pragma comment(linker, "/export:SetWindowLongW=user32.SetWindowLongW") // XP
#pragma comment(linker, "/export:SetWindowPlacement=user32.SetWindowPlacement") // XP
#pragma comment(linker, "/export:SetWindowPos=user32.SetWindowPos") // XP
#pragma comment(linker, "/export:SetWindowRgn=user32.SetWindowRgn") // XP
#pragma comment(linker, "/export:SetWindowRgnEx=user32.SetWindowRgnEx")
#pragma comment(linker, "/export:SetWindowStationUser=user32.SetWindowStationUser") // XP
#pragma comment(linker, "/export:SetWindowTextA=user32.SetWindowTextA") // XP
#pragma comment(linker, "/export:SetWindowTextW=user32.SetWindowTextW") // XP
#pragma comment(linker, "/export:SetWindowWord=user32.SetWindowWord") // XP
#pragma comment(linker, "/export:SetWindowsHookA=user32.SetWindowsHookA") // XP
#pragma comment(linker, "/export:SetWindowsHookExA=user32.SetWindowsHookExA") // XP
#pragma comment(linker, "/export:SetWindowsHookExW=user32.SetWindowsHookExW") // XP
#pragma comment(linker, "/export:SetWindowsHookW=user32.SetWindowsHookW") // XP
#pragma comment(linker, "/export:ShowCaret=user32.ShowCaret") // XP
#pragma comment(linker, "/export:ShowCursor=user32.ShowCursor") // XP
#pragma comment(linker, "/export:ShowOwnedPopups=user32.ShowOwnedPopups") // XP
#pragma comment(linker, "/export:ShowScrollBar=user32.ShowScrollBar") // XP
#pragma comment(linker, "/export:ShowStartGlass=user32.ShowStartGlass") // XP
#pragma comment(linker, "/export:ShowSystemCursor=user32.ShowSystemCursor")
#pragma comment(linker, "/export:ShowWindow=user32.ShowWindow") // XP
#pragma comment(linker, "/export:ShowWindowAsync=user32.ShowWindowAsync") // XP
#pragma comment(linker, "/export:ShutdownBlockReasonCreate=user32.ShutdownBlockReasonCreate")
#pragma comment(linker, "/export:ShutdownBlockReasonDestroy=user32.ShutdownBlockReasonDestroy")
#pragma comment(linker, "/export:ShutdownBlockReasonQuery=user32.ShutdownBlockReasonQuery")
#pragma comment(linker, "/export:SignalRedirectionStartComplete=user32.SignalRedirectionStartComplete")
#pragma comment(linker, "/export:SkipPointerFrameMessages=user32.SkipPointerFrameMessages")
#pragma comment(linker, "/export:SoftModalMessageBox=user32.SoftModalMessageBox") // XP
#pragma comment(linker, "/export:SoundSentry=user32.SoundSentry")
#pragma comment(linker, "/export:SubtractRect=user32.SubtractRect") // XP
#pragma comment(linker, "/export:SwapMouseButton=user32.SwapMouseButton") // XP
#pragma comment(linker, "/export:SwitchDesktop=user32.SwitchDesktop") // XP
#pragma comment(linker, "/export:SwitchDesktopWithFade=user32.SwitchDesktopWithFade")
#pragma comment(linker, "/export:SwitchToThisWindow=user32.SwitchToThisWindow") // XP
#pragma comment(linker, "/export:SystemParametersInfoA=user32.SystemParametersInfoA") // XP
#pragma comment(linker, "/export:SystemParametersInfoForDpi=user32.SystemParametersInfoForDpi")
#pragma comment(linker, "/export:SystemParametersInfoW=user32.SystemParametersInfoW") // XP
#pragma comment(linker, "/export:TabbedTextOutA=user32.TabbedTextOutA") // XP
#pragma comment(linker, "/export:TabbedTextOutW=user32.TabbedTextOutW") // XP
#pragma comment(linker, "/export:TileChildWindows=user32.TileChildWindows") // XP
#pragma comment(linker, "/export:TileWindows=user32.TileWindows") // XP
#pragma comment(linker, "/export:ToAscii=user32.ToAscii") // XP
#pragma comment(linker, "/export:ToAsciiEx=user32.ToAsciiEx") // XP
#pragma comment(linker, "/export:ToUnicode=user32.ToUnicode") // XP
#pragma comment(linker, "/export:ToUnicodeEx=user32.ToUnicodeEx") // XP
#pragma comment(linker, "/export:TrackMouseEvent=user32.TrackMouseEvent") // XP
#pragma comment(linker, "/export:TrackPopupMenu=user32.TrackPopupMenu") // XP
#pragma comment(linker, "/export:TrackPopupMenuEx=user32.TrackPopupMenuEx") // XP
#pragma comment(linker, "/export:TranslateAccelerator=user32.TranslateAccelerator") // XP
#pragma comment(linker, "/export:TranslateAcceleratorA=user32.TranslateAcceleratorA") // XP
#pragma comment(linker, "/export:TranslateAcceleratorW=user32.TranslateAcceleratorW") // XP
#pragma comment(linker, "/export:TranslateMDISysAccel=user32.TranslateMDISysAccel") // XP
#pragma comment(linker, "/export:TranslateMessage=user32.TranslateMessage") // XP
#pragma comment(linker, "/export:TranslateMessageEx=user32.TranslateMessageEx") // XP
#pragma comment(linker, "/export:UnhookWinEvent=user32.UnhookWinEvent") // XP
#pragma comment(linker, "/export:UnhookWindowsHook=user32.UnhookWindowsHook") // XP
#pragma comment(linker, "/export:UnhookWindowsHookEx=user32.UnhookWindowsHookEx") // XP
#pragma comment(linker, "/export:UnionRect=user32.UnionRect") // XP
#pragma comment(linker, "/export:UnloadKeyboardLayout=user32.UnloadKeyboardLayout") // XP
#pragma comment(linker, "/export:UnlockWindowStation=user32.UnlockWindowStation") // XP
#pragma comment(linker, "/export:UnpackDDElParam=user32.UnpackDDElParam") // XP
#pragma comment(linker, "/export:UnregisterClassA=user32.UnregisterClassA") // XP
#pragma comment(linker, "/export:UnregisterClassW=user32.UnregisterClassW") // XP
#pragma comment(linker, "/export:UnregisterDeviceNotification=user32.UnregisterDeviceNotification") // XP
#pragma comment(linker, "/export:UnregisterHotKey=user32.UnregisterHotKey") // XP
#pragma comment(linker, "/export:UnregisterMessagePumpHook=user32.UnregisterMessagePumpHook") // XP
#pragma comment(linker, "/export:UnregisterPointerInputTarget=user32.UnregisterPointerInputTarget")
#pragma comment(linker, "/export:UnregisterPointerInputTargetEx=user32.UnregisterPointerInputTargetEx")
#pragma comment(linker, "/export:UnregisterPowerSettingNotification=user32.UnregisterPowerSettingNotification")
#pragma comment(linker, "/export:UnregisterSessionPort=user32.UnregisterSessionPort")
#pragma comment(linker, "/export:UnregisterSuspendResumeNotification=user32.UnregisterSuspendResumeNotification")
#pragma comment(linker, "/export:UnregisterTouchWindow=user32.UnregisterTouchWindow")
#pragma comment(linker, "/export:UnregisterUserApiHook=user32.UnregisterUserApiHook") // XP
#pragma comment(linker, "/export:UpdateDefaultDesktopThumbnail=user32.UpdateDefaultDesktopThumbnail")
#pragma comment(linker, "/export:UpdateLayeredWindow=user32.UpdateLayeredWindow") // XP
#pragma comment(linker, "/export:UpdateLayeredWindowIndirect=user32.UpdateLayeredWindowIndirect")
#pragma comment(linker, "/export:UpdatePerUserSystemParameters=user32.UpdatePerUserSystemParameters") // XP
#pragma comment(linker, "/export:UpdateWindow=user32.UpdateWindow") // XP
#pragma comment(linker, "/export:UpdateWindowInputSinkHints=user32.UpdateWindowInputSinkHints")
#pragma comment(linker, "/export:UpdateWindowTransform=user32.UpdateWindowTransform")
#pragma comment(linker, "/export:User32InitializeImmEntryTable=user32.User32InitializeImmEntryTable") // XP
#pragma comment(linker, "/export:UserClientDllInitialize=user32.UserClientDllInitialize") // XP
#pragma comment(linker, "/export:UserHandleGrantAccess=user32.UserHandleGrantAccess") // XP
#pragma comment(linker, "/export:UserLpkPSMTextOut=user32.UserLpkPSMTextOut") // XP
#pragma comment(linker, "/export:UserLpkTabbedTextOut=user32.UserLpkTabbedTextOut") // XP
#pragma comment(linker, "/export:UserRealizePalette=user32.UserRealizePalette") // XP
#pragma comment(linker, "/export:UserRegisterWowHandlers=user32.UserRegisterWowHandlers") // XP
#pragma comment(linker, "/export:VRipOutput=user32.VRipOutput") // XP
#pragma comment(linker, "/export:VTagOutput=user32.VTagOutput") // XP
#pragma comment(linker, "/export:ValidateRect=user32.ValidateRect") // XP
#pragma comment(linker, "/export:ValidateRgn=user32.ValidateRgn") // XP
#pragma comment(linker, "/export:VkKeyScanA=user32.VkKeyScanA") // XP
#pragma comment(linker, "/export:VkKeyScanExA=user32.VkKeyScanExA") // XP
#pragma comment(linker, "/export:VkKeyScanExW=user32.VkKeyScanExW") // XP
#pragma comment(linker, "/export:VkKeyScanW=user32.VkKeyScanW") // XP
#pragma comment(linker, "/export:WCSToMBEx=user32.WCSToMBEx") // XP
#pragma comment(linker, "/export:WINNLSEnableIME=user32.WINNLSEnableIME") // XP
#pragma comment(linker, "/export:WINNLSGetEnableStatus=user32.WINNLSGetEnableStatus") // XP
#pragma comment(linker, "/export:WINNLSGetIMEHotkey=user32.WINNLSGetIMEHotkey") // XP
#pragma comment(linker, "/export:WaitForInputIdle=user32.WaitForInputIdle") // XP
#pragma comment(linker, "/export:WaitForRedirectionStartComplete=user32.WaitForRedirectionStartComplete")
#pragma comment(linker, "/export:WaitMessage=user32.WaitMessage") // XP
#pragma comment(linker, "/export:WinHelpA=user32.WinHelpA") // XP
#pragma comment(linker, "/export:WinHelpW=user32.WinHelpW") // XP
#pragma comment(linker, "/export:WindowFromDC=user32.WindowFromDC") // XP
#pragma comment(linker, "/export:WindowFromPhysicalPoint=user32.WindowFromPhysicalPoint")
#pragma comment(linker, "/export:WindowFromPoint=user32.WindowFromPoint") // XP
#pragma comment(linker, "/export:Wow64Transition=user32.Wow64Transition")
#pragma comment(linker, "/export:_UserTestTokenForInteractive=user32._UserTestTokenForInteractive")
#pragma comment(linker, "/export:gSharedInfo=user32.gSharedInfo")
#pragma comment(linker, "/export:gapfnScSendMessage=user32.gapfnScSendMessage")
#pragma comment(linker, "/export:keybd_event=user32.keybd_event") // XP
#pragma comment(linker, "/export:mouse_event=user32.mouse_event") // XP
#pragma comment(linker, "/export:wsprintfA=user32.wsprintfA") // XP
#pragma comment(linker, "/export:wsprintfW=user32.wsprintfW") // XP
#pragma comment(linker, "/export:wvsprintfA=user32.wvsprintfA") // XP
#pragma comment(linker, "/export:wvsprintfW=user32.wvsprintfW") // XP
