#include <WinDef.h>

#pragma comment(linker, "/export:BeginBufferedAnimation=uxtheme.BeginBufferedAnimation")
#pragma comment(linker, "/export:BeginBufferedPaint=uxtheme.BeginBufferedPaint")
#pragma comment(linker, "/export:BeginPanningFeedback=uxtheme.BeginPanningFeedback")
#pragma comment(linker, "/export:BufferedPaintClear=uxtheme.BufferedPaintClear")
#pragma comment(linker, "/export:BufferedPaintInit=uxtheme.BufferedPaintInit")
#pragma comment(linker, "/export:BufferedPaintRenderAnimation=uxtheme.BufferedPaintRenderAnimation")
#pragma comment(linker, "/export:BufferedPaintSetAlpha=uxtheme.BufferedPaintSetAlpha")
#pragma comment(linker, "/export:BufferedPaintStopAllAnimations=uxtheme.BufferedPaintStopAllAnimations")
#pragma comment(linker, "/export:BufferedPaintUnInit=uxtheme.BufferedPaintUnInit")
#pragma comment(linker, "/export:CloseThemeData=uxtheme.CloseThemeData") // XP
#pragma comment(linker, "/export:DllCanUnloadNow=uxtheme.DllCanUnloadNow")
#pragma comment(linker, "/export:DllGetActivationFactory=uxtheme.DllGetActivationFactory")
#pragma comment(linker, "/export:DllGetClassObject=uxtheme.DllGetClassObject")
#pragma comment(linker, "/export:DrawThemeBackground=uxtheme.DrawThemeBackground") // XP
#pragma comment(linker, "/export:DrawThemeBackgroundEx=uxtheme.DrawThemeBackgroundEx") // XP
#pragma comment(linker, "/export:DrawThemeEdge=uxtheme.DrawThemeEdge") // XP
#pragma comment(linker, "/export:DrawThemeIcon=uxtheme.DrawThemeIcon") // XP
#pragma comment(linker, "/export:DrawThemeParentBackground=uxtheme.DrawThemeParentBackground") // XP
#pragma comment(linker, "/export:DrawThemeParentBackgroundEx=uxtheme.DrawThemeParentBackgroundEx")
#pragma comment(linker, "/export:DrawThemeText=uxtheme.DrawThemeText") // XP
#pragma comment(linker, "/export:DrawThemeTextEx=uxtheme.DrawThemeTextEx")
#pragma comment(linker, "/export:EnableThemeDialogTexture=uxtheme.EnableThemeDialogTexture") // XP
#pragma comment(linker, "/export:EnableTheming=uxtheme.EnableTheming") // XP
#pragma comment(linker, "/export:EndBufferedAnimation=uxtheme.EndBufferedAnimation")
#pragma comment(linker, "/export:EndBufferedPaint=uxtheme.EndBufferedPaint")
#pragma comment(linker, "/export:EndPanningFeedback=uxtheme.EndPanningFeedback")
#pragma comment(linker, "/export:GetBufferedPaintBits=uxtheme.GetBufferedPaintBits")
#pragma comment(linker, "/export:GetBufferedPaintDC=uxtheme.GetBufferedPaintDC")
#pragma comment(linker, "/export:GetBufferedPaintTargetDC=uxtheme.GetBufferedPaintTargetDC")
#pragma comment(linker, "/export:GetBufferedPaintTargetRect=uxtheme.GetBufferedPaintTargetRect")
#pragma comment(linker, "/export:GetColorFromPreference=uxtheme.GetColorFromPreference")
#pragma comment(linker, "/export:GetCurrentThemeName=uxtheme.GetCurrentThemeName") // XP
#pragma comment(linker, "/export:GetImmersiveColorFromColorSetEx=uxtheme.GetImmersiveColorFromColorSetEx")
#pragma comment(linker, "/export:GetImmersiveUserColorSetPreference=uxtheme.GetImmersiveUserColorSetPreference")
#pragma comment(linker, "/export:GetThemeAnimationProperty=uxtheme.GetThemeAnimationProperty")
#pragma comment(linker, "/export:GetThemeAnimationTransform=uxtheme.GetThemeAnimationTransform")
#pragma comment(linker, "/export:GetThemeAppProperties=uxtheme.GetThemeAppProperties") // XP
#pragma comment(linker, "/export:GetThemeBackgroundContentRect=uxtheme.GetThemeBackgroundContentRect") // XP
#pragma comment(linker, "/export:GetThemeBackgroundExtent=uxtheme.GetThemeBackgroundExtent") // XP
#pragma comment(linker, "/export:GetThemeBackgroundRegion=uxtheme.GetThemeBackgroundRegion") // XP
#pragma comment(linker, "/export:GetThemeBitmap=uxtheme.GetThemeBitmap")
#pragma comment(linker, "/export:GetThemeBool=uxtheme.GetThemeBool") // XP
#pragma comment(linker, "/export:GetThemeColor=uxtheme.GetThemeColor") // XP
#pragma comment(linker, "/export:GetThemeDocumentationProperty=uxtheme.GetThemeDocumentationProperty") // XP
#pragma comment(linker, "/export:GetThemeEnumValue=uxtheme.GetThemeEnumValue") // XP
#pragma comment(linker, "/export:GetThemeFilename=uxtheme.GetThemeFilename") // XP
#pragma comment(linker, "/export:GetThemeFont=uxtheme.GetThemeFont") // XP
#pragma comment(linker, "/export:GetThemeInt=uxtheme.GetThemeInt") // XP
#pragma comment(linker, "/export:GetThemeIntList=uxtheme.GetThemeIntList") // XP
#pragma comment(linker, "/export:GetThemeMargins=uxtheme.GetThemeMargins") // XP
#pragma comment(linker, "/export:GetThemeMetric=uxtheme.GetThemeMetric") // XP
#pragma comment(linker, "/export:GetThemePartSize=uxtheme.GetThemePartSize") // XP
#pragma comment(linker, "/export:GetThemePosition=uxtheme.GetThemePosition") // XP
#pragma comment(linker, "/export:GetThemePropertyOrigin=uxtheme.GetThemePropertyOrigin") // XP
#pragma comment(linker, "/export:GetThemeRect=uxtheme.GetThemeRect") // XP
#pragma comment(linker, "/export:GetThemeStream=uxtheme.GetThemeStream")
#pragma comment(linker, "/export:GetThemeString=uxtheme.GetThemeString") // XP
#pragma comment(linker, "/export:GetThemeSysBool=uxtheme.GetThemeSysBool") // XP
#pragma comment(linker, "/export:GetThemeSysColor=uxtheme.GetThemeSysColor") // XP
#pragma comment(linker, "/export:GetThemeSysColorBrush=uxtheme.GetThemeSysColorBrush") // XP
#pragma comment(linker, "/export:GetThemeSysFont=uxtheme.GetThemeSysFont") // XP
#pragma comment(linker, "/export:GetThemeSysInt=uxtheme.GetThemeSysInt") // XP
#pragma comment(linker, "/export:GetThemeSysSize=uxtheme.GetThemeSysSize") // XP
#pragma comment(linker, "/export:GetThemeSysString=uxtheme.GetThemeSysString") // XP
#pragma comment(linker, "/export:GetThemeTextExtent=uxtheme.GetThemeTextExtent") // XP
#pragma comment(linker, "/export:GetThemeTextMetrics=uxtheme.GetThemeTextMetrics") // XP
#pragma comment(linker, "/export:GetThemeTimingFunction=uxtheme.GetThemeTimingFunction")
#pragma comment(linker, "/export:GetThemeTransitionDuration=uxtheme.GetThemeTransitionDuration")
#pragma comment(linker, "/export:GetUserColorPreference=uxtheme.GetUserColorPreference")
#pragma comment(linker, "/export:GetWindowTheme=uxtheme.GetWindowTheme") // XP
#pragma comment(linker, "/export:HitTestThemeBackground=uxtheme.HitTestThemeBackground") // XP
#pragma comment(linker, "/export:IsAppThemed=uxtheme.IsAppThemed") // XP
#pragma comment(linker, "/export:IsCompositionActive=uxtheme.IsCompositionActive")
#pragma comment(linker, "/export:IsThemeActive=uxtheme.IsThemeActive") // XP
#pragma comment(linker, "/export:IsThemeBackgroundPartiallyTransparent=uxtheme.IsThemeBackgroundPartiallyTransparent") // XP
#pragma comment(linker, "/export:IsThemeDialogTextureEnabled=uxtheme.IsThemeDialogTextureEnabled") // XP
#pragma comment(linker, "/export:IsThemePartDefined=uxtheme.IsThemePartDefined") // XP
#pragma comment(linker, "/export:OpenThemeData=uxtheme.OpenThemeData") // XP
#pragma comment(linker, "/export:OpenThemeDataEx=uxtheme.OpenThemeDataEx")
#pragma comment(linker, "/export:SetThemeAppProperties=uxtheme.SetThemeAppProperties") // XP
#pragma comment(linker, "/export:SetWindowTheme=uxtheme.SetWindowTheme") // XP
#pragma comment(linker, "/export:SetWindowThemeAttribute=uxtheme.SetWindowThemeAttribute")
#pragma comment(linker, "/export:ThemeInitApiHook=uxtheme.ThemeInitApiHook")
#pragma comment(linker, "/export:UpdatePanningFeedback=uxtheme.UpdatePanningFeedback")
