#include <WinDef.h>

#pragma comment(linker, "/export:FreeAddrInfoEx=ws2_32.FreeAddrInfoEx")
#pragma comment(linker, "/export:FreeAddrInfoExW=ws2_32.FreeAddrInfoExW")
#pragma comment(linker, "/export:FreeAddrInfoW=ws2_32.FreeAddrInfoW") // XP
#pragma comment(linker, "/export:GetAddrInfoExA=ws2_32.GetAddrInfoExA")
#pragma comment(linker, "/export:GetAddrInfoExCancel=ws2_32.GetAddrInfoExCancel")
#pragma comment(linker, "/export:GetAddrInfoExOverlappedResult=ws2_32.GetAddrInfoExOverlappedResult")
#pragma comment(linker, "/export:GetAddrInfoExW=ws2_32.GetAddrInfoExW")
#pragma comment(linker, "/export:GetAddrInfoW=ws2_32.GetAddrInfoW") // XP
#pragma comment(linker, "/export:GetHostNameW=ws2_32.GetHostNameW")
#pragma comment(linker, "/export:GetNameInfoW=ws2_32.GetNameInfoW") // XP
#pragma comment(linker, "/export:InetNtopW=ws2_32.InetNtopW")
#pragma comment(linker, "/export:InetPtonW=ws2_32.InetPtonW")
#pragma comment(linker, "/export:SetAddrInfoExA=ws2_32.SetAddrInfoExA")
#pragma comment(linker, "/export:SetAddrInfoExW=ws2_32.SetAddrInfoExW")
#pragma comment(linker, "/export:WEP=ws2_32.WEP") // XP
#pragma comment(linker, "/export:WPUCompleteOverlappedRequest=ws2_32.WPUCompleteOverlappedRequest") // XP
#pragma comment(linker, "/export:WPUGetProviderPathEx=ws2_32.WPUGetProviderPathEx")
#pragma comment(linker, "/export:WSAAccept=ws2_32.WSAAccept") // XP
#pragma comment(linker, "/export:WSAAddressToStringA=ws2_32.WSAAddressToStringA") // XP
#pragma comment(linker, "/export:WSAAddressToStringW=ws2_32.WSAAddressToStringW") // XP
#pragma comment(linker, "/export:WSAAdvertiseProvider=ws2_32.WSAAdvertiseProvider")
#pragma comment(linker, "/export:WSAAsyncGetHostByAddr=ws2_32.WSAAsyncGetHostByAddr") // XP
#pragma comment(linker, "/export:WSAAsyncGetHostByName=ws2_32.WSAAsyncGetHostByName") // XP
#pragma comment(linker, "/export:WSAAsyncGetProtoByName=ws2_32.WSAAsyncGetProtoByName") // XP
#pragma comment(linker, "/export:WSAAsyncGetProtoByNumber=ws2_32.WSAAsyncGetProtoByNumber") // XP
#pragma comment(linker, "/export:WSAAsyncGetServByName=ws2_32.WSAAsyncGetServByName") // XP
#pragma comment(linker, "/export:WSAAsyncGetServByPort=ws2_32.WSAAsyncGetServByPort") // XP
#pragma comment(linker, "/export:WSAAsyncSelect=ws2_32.WSAAsyncSelect") // XP
#pragma comment(linker, "/export:WSACancelAsyncRequest=ws2_32.WSACancelAsyncRequest") // XP
#pragma comment(linker, "/export:WSACancelBlockingCall=ws2_32.WSACancelBlockingCall") // XP
#pragma comment(linker, "/export:WSACleanup=ws2_32.WSACleanup") // XP
#pragma comment(linker, "/export:WSACloseEvent=ws2_32.WSACloseEvent") // XP
#pragma comment(linker, "/export:WSAConnect=ws2_32.WSAConnect") // XP
#pragma comment(linker, "/export:WSAConnectByList=ws2_32.WSAConnectByList")
#pragma comment(linker, "/export:WSAConnectByNameA=ws2_32.WSAConnectByNameA")
#pragma comment(linker, "/export:WSAConnectByNameW=ws2_32.WSAConnectByNameW")
#pragma comment(linker, "/export:WSACreateEvent=ws2_32.WSACreateEvent") // XP
#pragma comment(linker, "/export:WSADuplicateSocketA=ws2_32.WSADuplicateSocketA") // XP
#pragma comment(linker, "/export:WSADuplicateSocketW=ws2_32.WSADuplicateSocketW") // XP
#pragma comment(linker, "/export:WSAEnumNameSpaceProvidersA=ws2_32.WSAEnumNameSpaceProvidersA") // XP
#pragma comment(linker, "/export:WSAEnumNameSpaceProvidersExA=ws2_32.WSAEnumNameSpaceProvidersExA")
#pragma comment(linker, "/export:WSAEnumNameSpaceProvidersExW=ws2_32.WSAEnumNameSpaceProvidersExW")
#pragma comment(linker, "/export:WSAEnumNameSpaceProvidersW=ws2_32.WSAEnumNameSpaceProvidersW") // XP
#pragma comment(linker, "/export:WSAEnumNetworkEvents=ws2_32.WSAEnumNetworkEvents") // XP
#pragma comment(linker, "/export:WSAEnumProtocolsA=ws2_32.WSAEnumProtocolsA") // XP
#pragma comment(linker, "/export:WSAEnumProtocolsW=ws2_32.WSAEnumProtocolsW") // XP
#pragma comment(linker, "/export:WSAEventSelect=ws2_32.WSAEventSelect") // XP
#pragma comment(linker, "/export:WSAGetLastError=ws2_32.WSAGetLastError") // XP
#pragma comment(linker, "/export:WSAGetOverlappedResult=ws2_32.WSAGetOverlappedResult") // XP
#pragma comment(linker, "/export:WSAGetQOSByName=ws2_32.WSAGetQOSByName") // XP
#pragma comment(linker, "/export:WSAGetServiceClassInfoA=ws2_32.WSAGetServiceClassInfoA") // XP
#pragma comment(linker, "/export:WSAGetServiceClassInfoW=ws2_32.WSAGetServiceClassInfoW") // XP
#pragma comment(linker, "/export:WSAGetServiceClassNameByClassIdA=ws2_32.WSAGetServiceClassNameByClassIdA") // XP
#pragma comment(linker, "/export:WSAGetServiceClassNameByClassIdW=ws2_32.WSAGetServiceClassNameByClassIdW") // XP
#pragma comment(linker, "/export:WSAHtonl=ws2_32.WSAHtonl") // XP
#pragma comment(linker, "/export:WSAHtons=ws2_32.WSAHtons") // XP
#pragma comment(linker, "/export:WSAInstallServiceClassA=ws2_32.WSAInstallServiceClassA") // XP
#pragma comment(linker, "/export:WSAInstallServiceClassW=ws2_32.WSAInstallServiceClassW") // XP
#pragma comment(linker, "/export:WSAIoctl=ws2_32.WSAIoctl") // XP
#pragma comment(linker, "/export:WSAIsBlocking=ws2_32.WSAIsBlocking") // XP
#pragma comment(linker, "/export:WSAJoinLeaf=ws2_32.WSAJoinLeaf") // XP
#pragma comment(linker, "/export:WSALookupServiceBeginA=ws2_32.WSALookupServiceBeginA") // XP
#pragma comment(linker, "/export:WSALookupServiceBeginW=ws2_32.WSALookupServiceBeginW") // XP
#pragma comment(linker, "/export:WSALookupServiceEnd=ws2_32.WSALookupServiceEnd") // XP
#pragma comment(linker, "/export:WSALookupServiceNextA=ws2_32.WSALookupServiceNextA") // XP
#pragma comment(linker, "/export:WSALookupServiceNextW=ws2_32.WSALookupServiceNextW") // XP
#pragma comment(linker, "/export:WSANSPIoctl=ws2_32.WSANSPIoctl") // XP
#pragma comment(linker, "/export:WSANtohl=ws2_32.WSANtohl") // XP
#pragma comment(linker, "/export:WSANtohs=ws2_32.WSANtohs") // XP
#pragma comment(linker, "/export:WSAPoll=ws2_32.WSAPoll")
#pragma comment(linker, "/export:WSAProviderCompleteAsyncCall=ws2_32.WSAProviderCompleteAsyncCall")
#pragma comment(linker, "/export:WSAProviderConfigChange=ws2_32.WSAProviderConfigChange") // XP
#pragma comment(linker, "/export:WSARecv=ws2_32.WSARecv") // XP
#pragma comment(linker, "/export:WSARecvDisconnect=ws2_32.WSARecvDisconnect") // XP
#pragma comment(linker, "/export:WSARecvFrom=ws2_32.WSARecvFrom") // XP
#pragma comment(linker, "/export:WSARemoveServiceClass=ws2_32.WSARemoveServiceClass") // XP
#pragma comment(linker, "/export:WSAResetEvent=ws2_32.WSAResetEvent") // XP
#pragma comment(linker, "/export:WSASend=ws2_32.WSASend") // XP
#pragma comment(linker, "/export:WSASendDisconnect=ws2_32.WSASendDisconnect") // XP
#pragma comment(linker, "/export:WSASendMsg=ws2_32.WSASendMsg")
#pragma comment(linker, "/export:WSASendTo=ws2_32.WSASendTo") // XP
#pragma comment(linker, "/export:WSASetBlockingHook=ws2_32.WSASetBlockingHook") // XP
#pragma comment(linker, "/export:WSASetEvent=ws2_32.WSASetEvent") // XP
#pragma comment(linker, "/export:WSASetLastError=ws2_32.WSASetLastError") // XP
#pragma comment(linker, "/export:WSASetServiceA=ws2_32.WSASetServiceA") // XP
#pragma comment(linker, "/export:WSASetServiceW=ws2_32.WSASetServiceW") // XP
#pragma comment(linker, "/export:WSASocketA=ws2_32.WSASocketA") // XP
#pragma comment(linker, "/export:WSASocketW=ws2_32.WSASocketW") // XP
#pragma comment(linker, "/export:WSAStartup=ws2_32.WSAStartup") // XP
#pragma comment(linker, "/export:WSAStringToAddressA=ws2_32.WSAStringToAddressA") // XP
#pragma comment(linker, "/export:WSAStringToAddressW=ws2_32.WSAStringToAddressW") // XP
#pragma comment(linker, "/export:WSAUnadvertiseProvider=ws2_32.WSAUnadvertiseProvider")
#pragma comment(linker, "/export:WSAUnhookBlockingHook=ws2_32.WSAUnhookBlockingHook") // XP
#pragma comment(linker, "/export:WSAWaitForMultipleEvents=ws2_32.WSAWaitForMultipleEvents") // XP
#pragma comment(linker, "/export:WSApSetPostRoutine=ws2_32.WSApSetPostRoutine") // XP
#pragma comment(linker, "/export:WSCDeinstallProvider=ws2_32.WSCDeinstallProvider") // XP
#pragma comment(linker, "/export:WSCDeinstallProviderEx=ws2_32.WSCDeinstallProviderEx")
#pragma comment(linker, "/export:WSCEnableNSProvider=ws2_32.WSCEnableNSProvider") // XP
#pragma comment(linker, "/export:WSCEnumProtocols=ws2_32.WSCEnumProtocols") // XP
#pragma comment(linker, "/export:WSCEnumProtocolsEx=ws2_32.WSCEnumProtocolsEx")
#pragma comment(linker, "/export:WSCGetApplicationCategory=ws2_32.WSCGetApplicationCategory")
#pragma comment(linker, "/export:WSCGetApplicationCategoryEx=ws2_32.WSCGetApplicationCategoryEx")
#pragma comment(linker, "/export:WSCGetProviderInfo=ws2_32.WSCGetProviderInfo")
#pragma comment(linker, "/export:WSCGetProviderPath=ws2_32.WSCGetProviderPath") // XP
#pragma comment(linker, "/export:WSCInstallNameSpace=ws2_32.WSCInstallNameSpace") // XP
#pragma comment(linker, "/export:WSCInstallNameSpaceEx=ws2_32.WSCInstallNameSpaceEx")
#pragma comment(linker, "/export:WSCInstallNameSpaceEx2=ws2_32.WSCInstallNameSpaceEx2")
#pragma comment(linker, "/export:WSCInstallProvider=ws2_32.WSCInstallProvider") // XP
#pragma comment(linker, "/export:WSCInstallProviderAndChains=ws2_32.WSCInstallProviderAndChains")
#pragma comment(linker, "/export:WSCInstallProviderEx=ws2_32.WSCInstallProviderEx")
#pragma comment(linker, "/export:WSCSetApplicationCategory=ws2_32.WSCSetApplicationCategory")
#pragma comment(linker, "/export:WSCSetApplicationCategoryEx=ws2_32.WSCSetApplicationCategoryEx")
#pragma comment(linker, "/export:WSCSetProviderInfo=ws2_32.WSCSetProviderInfo")
#pragma comment(linker, "/export:WSCUnInstallNameSpace=ws2_32.WSCUnInstallNameSpace") // XP
#pragma comment(linker, "/export:WSCUnInstallNameSpaceEx2=ws2_32.WSCUnInstallNameSpaceEx2")
#pragma comment(linker, "/export:WSCUpdateProvider=ws2_32.WSCUpdateProvider") // XP
#pragma comment(linker, "/export:WSCUpdateProviderEx=ws2_32.WSCUpdateProviderEx")
#pragma comment(linker, "/export:WSCWriteNameSpaceOrder=ws2_32.WSCWriteNameSpaceOrder") // XP
#pragma comment(linker, "/export:WSCWriteProviderOrder=ws2_32.WSCWriteProviderOrder") // XP
#pragma comment(linker, "/export:WSCWriteProviderOrderEx=ws2_32.WSCWriteProviderOrderEx")
#pragma comment(linker, "/export:WahCloseApcHelper=ws2_32.WahCloseApcHelper")
#pragma comment(linker, "/export:WahCloseHandleHelper=ws2_32.WahCloseHandleHelper")
#pragma comment(linker, "/export:WahCloseNotificationHandleHelper=ws2_32.WahCloseNotificationHandleHelper")
#pragma comment(linker, "/export:WahCloseSocketHandle=ws2_32.WahCloseSocketHandle")
#pragma comment(linker, "/export:WahCloseThread=ws2_32.WahCloseThread")
#pragma comment(linker, "/export:WahCompleteRequest=ws2_32.WahCompleteRequest")
#pragma comment(linker, "/export:WahCreateHandleContextTable=ws2_32.WahCreateHandleContextTable")
#pragma comment(linker, "/export:WahCreateNotificationHandle=ws2_32.WahCreateNotificationHandle")
#pragma comment(linker, "/export:WahCreateSocketHandle=ws2_32.WahCreateSocketHandle")
#pragma comment(linker, "/export:WahDestroyHandleContextTable=ws2_32.WahDestroyHandleContextTable")
#pragma comment(linker, "/export:WahDisableNonIFSHandleSupport=ws2_32.WahDisableNonIFSHandleSupport")
#pragma comment(linker, "/export:WahEnableNonIFSHandleSupport=ws2_32.WahEnableNonIFSHandleSupport")
#pragma comment(linker, "/export:WahEnumerateHandleContexts=ws2_32.WahEnumerateHandleContexts")
#pragma comment(linker, "/export:WahInsertHandleContext=ws2_32.WahInsertHandleContext")
#pragma comment(linker, "/export:WahNotifyAllProcesses=ws2_32.WahNotifyAllProcesses")
#pragma comment(linker, "/export:WahOpenApcHelper=ws2_32.WahOpenApcHelper")
#pragma comment(linker, "/export:WahOpenCurrentThread=ws2_32.WahOpenCurrentThread")
#pragma comment(linker, "/export:WahOpenHandleHelper=ws2_32.WahOpenHandleHelper")
#pragma comment(linker, "/export:WahOpenNotificationHandleHelper=ws2_32.WahOpenNotificationHandleHelper")
#pragma comment(linker, "/export:WahQueueUserApc=ws2_32.WahQueueUserApc")
#pragma comment(linker, "/export:WahReferenceContextByHandle=ws2_32.WahReferenceContextByHandle")
#pragma comment(linker, "/export:WahRemoveHandleContext=ws2_32.WahRemoveHandleContext")
#pragma comment(linker, "/export:WahWaitForNotification=ws2_32.WahWaitForNotification")
#pragma comment(linker, "/export:WahWriteLSPEvent=ws2_32.WahWriteLSPEvent")
#pragma comment(linker, "/export:__WSAFDIsSet=ws2_32.__WSAFDIsSet") // XP
#pragma comment(linker, "/export:accept=ws2_32.accept") // XP
#pragma comment(linker, "/export:bind=ws2_32.bind") // XP
#pragma comment(linker, "/export:closesocket=ws2_32.closesocket") // XP
#pragma comment(linker, "/export:connect=ws2_32.connect") // XP
#pragma comment(linker, "/export:freeaddrinfo=ws2_32.freeaddrinfo") // XP
#pragma comment(linker, "/export:getaddrinfo=ws2_32.getaddrinfo") // XP
#pragma comment(linker, "/export:gethostbyaddr=ws2_32.gethostbyaddr") // XP
#pragma comment(linker, "/export:gethostbyname=ws2_32.gethostbyname") // XP
#pragma comment(linker, "/export:gethostname=ws2_32.gethostname") // XP
#pragma comment(linker, "/export:getnameinfo=ws2_32.getnameinfo") // XP
#pragma comment(linker, "/export:getpeername=ws2_32.getpeername") // XP
#pragma comment(linker, "/export:getprotobyname=ws2_32.getprotobyname") // XP
#pragma comment(linker, "/export:getprotobynumber=ws2_32.getprotobynumber") // XP
#pragma comment(linker, "/export:getservbyname=ws2_32.getservbyname") // XP
#pragma comment(linker, "/export:getservbyport=ws2_32.getservbyport") // XP
#pragma comment(linker, "/export:getsockname=ws2_32.getsockname") // XP
#pragma comment(linker, "/export:getsockopt=ws2_32.getsockopt") // XP
#pragma comment(linker, "/export:htonl=ws2_32.htonl") // XP
#pragma comment(linker, "/export:htons=ws2_32.htons") // XP
#pragma comment(linker, "/export:inet_addr=ws2_32.inet_addr") // XP
#pragma comment(linker, "/export:inet_ntoa=ws2_32.inet_ntoa") // XP
#pragma comment(linker, "/export:inet_ntop=ws2_32.inet_ntop")
#pragma comment(linker, "/export:inet_pton=ws2_32.inet_pton")
#pragma comment(linker, "/export:ioctlsocket=ws2_32.ioctlsocket") // XP
#pragma comment(linker, "/export:listen=ws2_32.listen") // XP
#pragma comment(linker, "/export:ntohl=ws2_32.ntohl") // XP
#pragma comment(linker, "/export:ntohs=ws2_32.ntohs") // XP
#pragma comment(linker, "/export:recv=ws2_32.recv") // XP
#pragma comment(linker, "/export:recvfrom=ws2_32.recvfrom") // XP
#pragma comment(linker, "/export:select=ws2_32.select") // XP
#pragma comment(linker, "/export:send=ws2_32.send") // XP
#pragma comment(linker, "/export:sendto=ws2_32.sendto") // XP
#pragma comment(linker, "/export:setsockopt=ws2_32.setsockopt") // XP
#pragma comment(linker, "/export:shutdown=ws2_32.shutdown") // XP
#pragma comment(linker, "/export:socket=ws2_32.socket") // XP
